-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260509082719_fix_inventory_balances_trigger_on_project_cascade.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Fix: deleting a project failed with FK violation
-- (inventory_balances_project_id_fkey) when inventory_movements existed.
--
-- Root cause: AFTER DELETE trigger sync_inventory_balances on
-- inventory_movements re-runs apply_inventory_balance_delta for each cascaded
-- row. That helper does an upsert into inventory_balances with the parent
-- project_id, which is already gone by the time per-row cascade triggers run,
-- so the FK from inventory_balances.project_id to projects.id rejects the
-- insert and the entire cascade aborts (PostgREST surfaces a 409).
--
-- Fix: in the DELETE branch, short-circuit when the parent project no longer
-- exists. The cascade is already wiping inventory_balances for the project,
-- so there is nothing to maintain. Normal "user deleted a single movement"
-- flow is unchanged because the project still exists in that path.

create or replace function public.sync_inventory_balances()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_row jsonb;
  v_old_row jsonb;
  v_new_project_id uuid;
  v_new_inventory_item_id uuid;
  v_new_inventory_location_id uuid;
  v_old_project_id uuid;
  v_old_inventory_item_id uuid;
  v_old_inventory_location_id uuid;
  v_new_delta numeric;
  v_old_delta numeric;
begin
  if tg_op in ('INSERT', 'UPDATE') then
    v_new_row := to_jsonb(new);
    v_new_project_id := (v_new_row ->> 'project_id')::uuid;
    v_new_inventory_item_id := (v_new_row ->> 'inventory_item_id')::uuid;
    v_new_inventory_location_id := coalesce(
      (v_new_row ->> 'inventory_location_id')::uuid,
      (v_new_row ->> 'location_id')::uuid
    );
    v_new_delta := (v_new_row ->> 'delta_qty')::numeric;
  end if;

  if tg_op in ('UPDATE', 'DELETE') then
    v_old_row := to_jsonb(old);
    v_old_project_id := (v_old_row ->> 'project_id')::uuid;
    v_old_inventory_item_id := (v_old_row ->> 'inventory_item_id')::uuid;
    v_old_inventory_location_id := coalesce(
      (v_old_row ->> 'inventory_location_id')::uuid,
      (v_old_row ->> 'location_id')::uuid
    );
    v_old_delta := (v_old_row ->> 'delta_qty')::numeric;
  end if;

  if tg_op = 'INSERT' then
    perform public.apply_inventory_balance_delta(
      v_new_project_id,
      v_new_inventory_item_id,
      v_new_inventory_location_id,
      v_new_delta
    );
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if v_old_project_id is distinct from v_new_project_id
       or v_old_inventory_item_id is distinct from v_new_inventory_item_id
       or v_old_inventory_location_id is distinct from v_new_inventory_location_id then
      perform public.apply_inventory_balance_delta(
        v_old_project_id,
        v_old_inventory_item_id,
        v_old_inventory_location_id,
        -v_old_delta
      );
      perform public.apply_inventory_balance_delta(
        v_new_project_id,
        v_new_inventory_item_id,
        v_new_inventory_location_id,
        v_new_delta
      );
    else
      perform public.apply_inventory_balance_delta(
        v_new_project_id,
        v_new_inventory_item_id,
        v_new_inventory_location_id,
        v_new_delta - v_old_delta
      );
    end if;

    return new;
  end if;

  -- DELETE: skip the rebalance if the parent project is being cascade-deleted.
  if not exists (select 1 from public.projects where id = v_old_project_id) then
    return old;
  end if;

  perform public.apply_inventory_balance_delta(
    v_old_project_id,
    v_old_inventory_item_id,
    v_old_inventory_location_id,
    -v_old_delta
  );

  return old;
end;
$$;
