-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260325120000_doc_media_visibility_write_enforcement.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Launch-sensitive visibility: enforce write-time control over documents/project_media visibility_class.
-- Prevent otherwise-capable project writers from widening who can read by flipping:
-- - internal -> shared_project
-- - shared_project -> internal

create or replace function public.guard_documents_visibility_class_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Allow creating/updating shared_project without internal-doc authority.
  if tg_op = 'INSERT' then
    if new.visibility_class = 'internal' then
      if not public.can_view_internal_documents(new.project_id) then
        raise exception 'Only users with internal-doc visibility can set documents.visibility_class = internal';
      end if;
    end if;
    return new;
  end if;

  -- Only triggered when visibility_class changes (see CREATE TRIGGER ... UPDATE OF visibility_class).
  if tg_op = 'UPDATE' then
    if new.visibility_class is distinct from old.visibility_class then
      if not public.can_view_internal_documents(new.project_id) then
        raise exception 'Only users with internal-doc visibility can change documents.visibility_class';
      end if;
    end if;
    return new;
  end if;

  return new;
end;
$$;

create trigger guard_documents_visibility_class_change
before insert or update of visibility_class on public.documents
for each row execute function public.guard_documents_visibility_class_change();

create or replace function public.guard_project_media_visibility_class_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Allow creating/updating shared_project without internal-doc authority.
  if tg_op = 'INSERT' then
    if new.visibility_class = 'internal' then
      if not public.can_view_internal_documents(new.project_id) then
        raise exception 'Only users with internal-doc visibility can set project_media.visibility_class = internal';
      end if;
    end if;
    return new;
  end if;

  -- Only triggered when visibility_class changes (see CREATE TRIGGER ... UPDATE OF visibility_class).
  if tg_op = 'UPDATE' then
    if new.visibility_class is distinct from old.visibility_class then
      if not public.can_view_internal_documents(new.project_id) then
        raise exception 'Only users with internal-doc visibility can change project_media.visibility_class';
      end if;
    end if;
    return new;
  end if;

  return new;
end;
$$;

create trigger guard_project_media_visibility_class_change
before insert or update of visibility_class on public.project_media
for each row execute function public.guard_project_media_visibility_class_change();

