-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260306162500_estimates_core.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create table public.project_estimates (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  title text not null,
  description text,
  status text not null default 'draft' check (status in ('draft', 'approved', 'archived')),
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_project_estimates_project_id on public.project_estimates(project_id);

create table public.estimate_versions (
  id uuid primary key default gen_random_uuid(),
  estimate_id uuid not null references public.project_estimates(id) on delete cascade,
  version_number integer not null,
  is_current boolean not null default false,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique (estimate_id, version_number)
);

create index idx_estimate_versions_estimate_id on public.estimate_versions(estimate_id);
create unique index idx_estimate_versions_current_per_estimate
  on public.estimate_versions(estimate_id)
  where is_current = true;

create table public.estimate_works (
  id uuid primary key default gen_random_uuid(),
  estimate_version_id uuid not null references public.estimate_versions(id) on delete cascade,
  project_stage_id uuid references public.project_stages(id) on delete set null,
  title text not null,
  description text,
  sort_order integer not null check (sort_order > 0),
  planned_cost_cents bigint check (planned_cost_cents is null or planned_cost_cents >= 0),
  created_at timestamptz not null default now()
);

create index idx_estimate_works_estimate_version_id on public.estimate_works(estimate_version_id);
create index idx_estimate_works_project_stage_id on public.estimate_works(project_stage_id);

create table public.estimate_resource_lines (
  id uuid primary key default gen_random_uuid(),
  estimate_work_id uuid not null references public.estimate_works(id) on delete cascade,
  resource_type text not null check (resource_type in ('material', 'labor', 'equipment', 'other')),
  title text not null,
  quantity numeric(14,3) not null check (quantity >= 0),
  unit text,
  unit_price_cents bigint check (unit_price_cents is null or unit_price_cents >= 0),
  total_price_cents bigint check (total_price_cents is null or total_price_cents >= 0),
  created_at timestamptz not null default now()
);

create index idx_estimate_resource_lines_estimate_work_id on public.estimate_resource_lines(estimate_work_id);

create table public.estimate_dependencies (
  id uuid primary key default gen_random_uuid(),
  estimate_version_id uuid not null references public.estimate_versions(id) on delete cascade,
  from_work_id uuid not null references public.estimate_works(id) on delete cascade,
  to_work_id uuid not null references public.estimate_works(id) on delete cascade,
  dependency_type text not null default 'finish_to_start' check (
    dependency_type in ('finish_to_start', 'start_to_start', 'finish_to_finish', 'start_to_finish')
  ),
  created_at timestamptz not null default now()
);

create index idx_estimate_dependencies_estimate_version_id on public.estimate_dependencies(estimate_version_id);
create index idx_estimate_dependencies_from_work_id on public.estimate_dependencies(from_work_id);
create index idx_estimate_dependencies_to_work_id on public.estimate_dependencies(to_work_id);

create trigger set_project_estimates_updated_at
before update on public.project_estimates
for each row execute function public.set_updated_at();
