-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260306161500_project_planning_tasks_and_comments.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create table public.project_stages (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  title text not null,
  description text not null default '',
  sort_order integer not null check (sort_order > 0),
  status text not null default 'open' check (status in ('open', 'completed', 'archived')),
  discount_bps integer not null default 0 check (discount_bps >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_project_stages_project_id on public.project_stages(project_id);
create unique index idx_project_stages_sort_order
  on public.project_stages(project_id, sort_order);

alter table public.project_stages
  add constraint project_stages_project_id_sort_order_key
  unique using index idx_project_stages_sort_order;

alter table public.projects
  add constraint projects_current_stage_id_fkey
  foreign key (current_stage_id)
  references public.project_stages(id)
  on delete set null;

create table public.tasks (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  stage_id uuid not null references public.project_stages(id) on delete restrict,
  title text not null,
  description text not null default '',
  status text not null default 'not_started' check (status in ('not_started', 'in_progress', 'done', 'blocked')),
  assignee_profile_id uuid references public.profiles(id) on delete set null,
  created_by uuid not null references public.profiles(id) on delete restrict,
  start_at timestamptz,
  due_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_tasks_project_id on public.tasks(project_id);
create index idx_tasks_stage_id on public.tasks(stage_id);
create index idx_tasks_assignee_profile_id on public.tasks(assignee_profile_id);

create table public.task_comments (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  author_profile_id uuid not null references public.profiles(id) on delete restrict,
  body text not null,
  created_at timestamptz not null default now()
);

create trigger set_project_stages_updated_at
before update on public.project_stages
for each row execute function public.set_updated_at();

create trigger set_tasks_updated_at
before update on public.tasks
for each row execute function public.set_updated_at();
