-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260306165000_billing_launch_tables.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create table public.billing_customers (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null check (provider in ('stripe')),
  external_customer_id text not null,
  email text,
  full_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, external_customer_id),
  unique (profile_id, provider)
);

create index idx_billing_customers_profile_id on public.billing_customers(profile_id);

create table public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  billing_customer_id uuid not null references public.billing_customers(id) on delete cascade,
  provider text not null check (provider in ('stripe')),
  external_subscription_id text not null,
  plan_code text not null,
  status text not null check (
    status in ('trialing', 'active', 'past_due', 'paused', 'canceled', 'incomplete', 'incomplete_expired')
  ),
  is_current boolean not null default false,
  currency text not null default 'RUB' check (currency in ('RUB', 'USD', 'EUR', 'GBP')),
  amount_cents bigint check (amount_cents is null or amount_cents >= 0),
  trial_starts_at timestamptz,
  trial_ends_at timestamptz,
  current_period_starts_at timestamptz,
  current_period_ends_at timestamptz,
  canceled_at timestamptz,
  provider_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (provider, external_subscription_id)
);

create index idx_subscriptions_profile_id on public.subscriptions(profile_id);
create index idx_subscriptions_billing_customer_id on public.subscriptions(billing_customer_id);
create unique index idx_subscriptions_current_per_profile
  on public.subscriptions(profile_id)
  where is_current = true;

create trigger set_billing_customers_updated_at
before update on public.billing_customers
for each row execute function public.set_updated_at();

create trigger set_subscriptions_updated_at
before update on public.subscriptions
for each row execute function public.set_updated_at();
