-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260330160000_wave2_hr_lineage_and_projection_uniqueness.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
alter table public.hr_items
  add column estimate_resource_line_id uuid
  references public.estimate_resource_lines(id)
  on delete set null;

with normalized_hr as (
  select
    hi.id as hr_item_id,
    hi.estimate_work_id,
    lower(trim(regexp_replace(hi.title, '\s+', ' ', 'g'))) as normalized_title
  from public.hr_items hi
  where hi.estimate_work_id is not null
    and hi.estimate_resource_line_id is null
),
normalized_lines as (
  select
    erl.id as estimate_resource_line_id,
    erl.estimate_work_id,
    lower(trim(regexp_replace(erl.title, '\s+', ' ', 'g'))) as normalized_title
  from public.estimate_resource_lines erl
  where erl.resource_type in ('labor', 'other')
),
candidate_pairs as (
  select
    hr.hr_item_id,
    nl.estimate_resource_line_id
  from normalized_hr hr
  join normalized_lines nl
    on nl.estimate_work_id = hr.estimate_work_id
   and nl.normalized_title = hr.normalized_title
),
unique_hr_matches as (
  select
    hr_item_id,
    min(estimate_resource_line_id::text)::uuid as estimate_resource_line_id
  from candidate_pairs
  group by hr_item_id
  having count(*) = 1
),
unique_line_matches as (
  select
    estimate_resource_line_id,
    min(hr_item_id::text)::uuid as hr_item_id
  from candidate_pairs
  group by estimate_resource_line_id
  having count(*) = 1
),
resolved_matches as (
  select
    uhm.hr_item_id,
    uhm.estimate_resource_line_id
  from unique_hr_matches uhm
  join unique_line_matches ulm
    on ulm.hr_item_id = uhm.hr_item_id
   and ulm.estimate_resource_line_id = uhm.estimate_resource_line_id
)
update public.hr_items hi
set estimate_resource_line_id = rm.estimate_resource_line_id
from resolved_matches rm
where hi.id = rm.hr_item_id
  and hi.estimate_resource_line_id is null;

create unique index idx_hr_items_estimate_resource_line_id_unique
  on public.hr_items(estimate_resource_line_id)
  where estimate_resource_line_id is not null;

create or replace function public.enforce_hr_item_estimate_lineage_scope()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_line_estimate_work_id uuid;
  v_line_project_id uuid;
  v_task_estimate_work_id uuid;
  v_task_project_id uuid;
begin
  if new.estimate_resource_line_id is not null then
    select
      erl.estimate_work_id,
      pe.project_id
    into
      v_line_estimate_work_id,
      v_line_project_id
    from public.estimate_resource_lines erl
    join public.estimate_works ew
      on ew.id = erl.estimate_work_id
    join public.estimate_versions ev
      on ev.id = ew.estimate_version_id
    join public.project_estimates pe
      on pe.id = ev.estimate_id
    where erl.id = new.estimate_resource_line_id;

    if not found then
      raise exception 'HR estimate_resource_line_id must reference an existing estimate resource line';
    end if;

    if v_line_project_id is distinct from new.project_id then
      raise exception 'HR estimate_resource_line_id must belong to the same project';
    end if;

    if new.estimate_work_id is not null
       and new.estimate_work_id is distinct from v_line_estimate_work_id then
      raise exception 'HR estimate_resource_line_id must match estimate_work_id';
    end if;
  end if;

  if new.task_id is not null then
    select
      t.project_id,
      t.estimate_work_id
    into
      v_task_project_id,
      v_task_estimate_work_id
    from public.tasks t
    where t.id = new.task_id;

    if not found then
      raise exception 'HR task_id must reference an existing task';
    end if;

    if v_task_project_id is distinct from new.project_id then
      raise exception 'HR task_id must belong to the same project';
    end if;

    if new.estimate_resource_line_id is not null
       and v_task_estimate_work_id is not null
       and v_task_estimate_work_id is distinct from v_line_estimate_work_id then
      raise exception 'HR task_id must match estimate resource line work lineage';
    end if;

    if new.estimate_work_id is not null
       and v_task_estimate_work_id is not null
       and v_task_estimate_work_id is distinct from new.estimate_work_id then
      raise exception 'HR task_id must match estimate_work_id';
    end if;
  end if;

  return new;
end;
$$;

create trigger enforce_hr_item_estimate_lineage_scope
before insert or update of project_id, estimate_work_id, estimate_resource_line_id, task_id on public.hr_items
for each row execute function public.enforce_hr_item_estimate_lineage_scope();

create unique index idx_procurement_items_estimate_resource_line_id_unique
  on public.procurement_items(estimate_resource_line_id)
  where estimate_resource_line_id is not null;
