-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260613120300_get_resource_article_detail.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 4 — get_resource_article_detail: powers the universal resource modal
-- ("Описание" / "Артикул" tabs) and the constructor's chevron "upgrade"
-- (subcategory siblings).
--
--   get_resource_article_detail(p_article_id)
--     Returns jsonb { article, siblings } or NULL when the article does not
--     exist / is archived.
--
--   article  — the canonical fields shown in the modal: name, canonical_name,
--              category_path, subcategory, kind, units, conversion_factor,
--              okpd2_code, rovno_sku, default_resource_type, source.
--   siblings — other curated leaf articles in the SAME subcategory (the chevron
--              "alternatives" list), ordered by display name, capped at 50.
--
-- Subcategory-null guard (critical): in wave-1 only the ~821 rovno_seed leaves
-- carry `subcategory` text; the ~987 curated KSR leaves have subcategory = NULL.
-- Without the `v_article.subcategory is not null` guard, every NULL-subcategory
-- leaf would match every other NULL-subcategory leaf and return a meaningless
-- 900-row sibling set. So siblings are only returned for articles that actually
-- belong to a named subcategory.
--
-- Out of scope here (handled elsewhere):
--   * in-estimate price history sparkline — derived client-side from version
--     snapshots; this RPC has no estimate/project context.
--   * cross-project median/avg finance comparison — a separate stretch RPC
--     (needs per-project can_access_project gating).
--
-- Authorization: canonical library is global read for signed-in users →
-- security definer + grant to authenticated.

create or replace function public.get_resource_article_detail(p_article_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_article record;
begin
  select *
    into v_article
  from public.system_resource_articles
  where id = p_article_id
    and archived = false;

  if v_article.id is null then
    return null;
  end if;

  return jsonb_build_object(
    'article', jsonb_build_object(
      'id', v_article.id,
      'name', v_article.name,
      'canonical_name', v_article.canonical_name,
      'category_path', v_article.category_path,
      'subcategory', v_article.subcategory,
      'kind', v_article.kind,
      'unit_display', v_article.unit_display,
      'unit_original', v_article.unit_original,
      'conversion_factor', v_article.conversion_factor,
      'okpd2_code', v_article.okpd2_code,
      'rovno_sku', v_article.rovno_sku,
      'default_resource_type', v_article.default_resource_type,
      'source', v_article.source,
      'is_residential_curated', v_article.is_residential_curated
    ),
    'siblings', (
      select coalesce(jsonb_agg(obj order by nm), '[]'::jsonb)
      from (
        select
          jsonb_build_object(
            'id', sib.id,
            'name', coalesce(sib.canonical_name, sib.name),
            'default_resource_type', sib.default_resource_type,
            'unit_display', sib.unit_display,
            'rovno_sku', sib.rovno_sku,
            'subcategory', sib.subcategory
          ) as obj,
          coalesce(sib.canonical_name, sib.name) as nm
        from public.system_resource_articles sib
        where v_article.subcategory is not null
          and sib.subcategory = v_article.subcategory
          and sib.kind = 'leaf'
          and sib.archived = false
          and sib.is_residential_curated = true
          and sib.id <> v_article.id
        order by coalesce(sib.canonical_name, sib.name)
        limit 50
      ) sibs
    )
  );
end;
$$;

revoke all on function public.get_resource_article_detail(uuid) from public;
grant execute on function public.get_resource_article_detail(uuid) to authenticated;
