-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260306165500_auth_bootstrap_and_domain_rpc.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create function public.handle_profile_defaults()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profile_settings (profile_id)
  values (new.id)
  on conflict (profile_id) do nothing;

  insert into public.notification_preferences (profile_id)
  values (new.id)
  on conflict (profile_id) do nothing;

  return new;
end;
$$;

create function public.handle_auth_user_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    email,
    full_name,
    avatar_url
  )
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      new.raw_user_meta_data ->> 'name',
      new.raw_user_meta_data ->> 'display_name'
    ),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do update
    set email = coalesce(excluded.email, public.profiles.email),
        full_name = coalesce(excluded.full_name, public.profiles.full_name),
        avatar_url = coalesce(excluded.avatar_url, public.profiles.avatar_url),
        updated_at = now();

  insert into public.profile_settings (profile_id)
  values (new.id)
  on conflict (profile_id) do nothing;

  insert into public.notification_preferences (profile_id)
  values (new.id)
  on conflict (profile_id) do nothing;

  return new;
end;
$$;

create function public.current_profile_id()
returns uuid
language sql
stable
as $$
  select auth.uid()
$$;

create function public.project_role(p_project_id uuid)
returns text
language sql
stable
as $$
  select case
    when auth.uid() is null then null
    when exists (
      select 1
      from public.projects p
      where p.id = p_project_id
        and p.owner_profile_id = auth.uid()
    ) then 'owner'
    else (
      select pm.role
      from public.project_members pm
      where pm.project_id = p_project_id
        and pm.profile_id = auth.uid()
      limit 1
    )
  end
$$;

create function public.is_project_member(p_project_id uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.projects p
    where p.id = p_project_id
      and p.owner_profile_id = auth.uid()
  )
  or exists (
    select 1
    from public.project_members pm
    where pm.project_id = p_project_id
      and pm.profile_id = auth.uid()
  )
$$;

create function public.has_project_role(p_project_id uuid, p_roles text[])
returns boolean
language sql
stable
as $$
  select coalesce(public.project_role(p_project_id) = any (p_roles), false)
$$;

create function public.can_access_project(p_project_id uuid)
returns boolean
language sql
stable
as $$
  select public.is_project_member(p_project_id)
$$;

create function public.can_manage_project(p_project_id uuid)
returns boolean
language sql
stable
as $$
  select public.has_project_role(p_project_id, array['owner', 'co_owner'])
$$;

create function public.can_write_project_content(p_project_id uuid)
returns boolean
language sql
stable
as $$
  select public.has_project_role(p_project_id, array['owner', 'co_owner', 'contractor'])
$$;

create function public.can_see_profile(p_profile_id uuid)
returns boolean
language sql
stable
as $$
  select p_profile_id = auth.uid()
  or exists (
    select 1
    from public.projects p
    where (
      p.owner_profile_id = auth.uid()
      or exists (
        select 1
        from public.project_members pm_current
        where pm_current.project_id = p.id
          and pm_current.profile_id = auth.uid()
      )
    )
      and (
        p.owner_profile_id = p_profile_id
        or exists (
          select 1
          from public.project_members pm_target
          where pm_target.project_id = p.id
            and pm_target.profile_id = p_profile_id
        )
      )
  )
$$;

create function public.can_access_storage_object(p_storage_object_id uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.document_versions dv
    join public.documents d
      on d.id = dv.document_id
    where dv.storage_object_id = p_storage_object_id
      and dv.is_current = true
      and public.can_access_project(d.project_id)
  )
  or exists (
    select 1
    from public.project_media pm
    where pm.storage_object_id = p_storage_object_id
      and public.can_access_project(pm.project_id)
  )
$$;

create function public.accept_project_invite(p_invite_token text)
returns public.project_invites
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite public.project_invites%rowtype;
  v_profile_email text;
  v_owner_profile_id uuid;
  v_already_accepted_by_current_user boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_invite
  from public.project_invites
  where invite_token = p_invite_token
  for update;

  if not found then
    raise exception 'Invite not found';
  end if;

  if v_invite.status = 'accepted' and v_invite.accepted_profile_id = auth.uid() then
    v_already_accepted_by_current_user := true;
  elsif v_invite.status <> 'pending' then
    raise exception 'Invite is no longer pending';
  end if;

  select p.email
  into v_profile_email
  from public.profiles p
  where p.id = auth.uid();

  if not found then
    raise exception 'Profile not found';
  end if;

  if not v_already_accepted_by_current_user
     and (v_profile_email is null or lower(v_profile_email) <> lower(v_invite.email)) then
    raise exception 'Invite email does not match the current account';
  end if;

  select p.owner_profile_id
  into v_owner_profile_id
  from public.projects p
  where p.id = v_invite.project_id;

  if not found then
    raise exception 'Project not found';
  end if;

  if v_invite.role = 'owner'
     and v_owner_profile_id is distinct from auth.uid() then
    raise exception 'Owner invites are not supported without a project ownership transfer';
  end if;

  insert into public.project_members (
    project_id,
    profile_id,
    role,
    ai_access,
    viewer_regime,
    credit_limit,
    used_credits
  )
  values (
    v_invite.project_id,
    auth.uid(),
    v_invite.role,
    v_invite.ai_access,
    v_invite.viewer_regime,
    v_invite.credit_limit,
    0
  )
  on conflict (project_id, profile_id) do update
    set role = excluded.role,
        ai_access = excluded.ai_access,
        viewer_regime = excluded.viewer_regime,
        credit_limit = excluded.credit_limit;

  if v_already_accepted_by_current_user then
    return v_invite;
  end if;

  update public.project_invites
  set status = 'accepted',
      accepted_profile_id = auth.uid(),
      accepted_at = coalesce(accepted_at, now())
  where id = v_invite.id
  returning * into v_invite;

  return v_invite;
end;
$$;

create function public.get_shared_estimate_version(p_share_token text)
returns public.estimate_versions
language plpgsql
as $$
begin
  raise exception 'estimate sharing is not yet implemented in current schema';
end;
$$;

create function public.approve_estimate_version_by_share_token(
  p_share_token text,
  p_payload jsonb
)
returns uuid
language plpgsql
as $$
begin
  raise exception 'estimate sharing is not yet implemented in current schema';
end;
$$;

create trigger on_profile_created_defaults
after insert on public.profiles
for each row execute function public.handle_profile_defaults();

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_auth_user_created();
