-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260416140000_session21_estimate_assignee_display_name.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 2.1 QA: humanize assignee on estimate operational resource_lines (join profiles via linked task).

create or replace function public.get_estimate_operational_summary(
  p_project_id uuid,
  p_estimate_version_id uuid default null,
  p_limit integer default 500,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 500), 1), 1000);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_allowed boolean;
  v_finance text;
  v_works jsonb := '[]'::jsonb;
  v_resource_lines jsonb := '[]'::jsonb;
  v_upper_block jsonb;
  v_ev_id uuid;
  v_ev_number integer;
  v_ev_created_at timestamptz;
  v_client_vat_bps integer;
  v_client_total_cents bigint;
  v_discount_bps integer;
  v_breakdown jsonb;
begin
  v_allowed := public.can_access_project(p_project_id);

  if not v_allowed then
    return jsonb_build_object(
      'works', '[]'::jsonb,
      'resource_lines', '[]'::jsonb,
      'upper_block', jsonb_build_object(
        'effective_finance_visibility', null,
        'timing', jsonb_build_object(
          'estimate_version_id', null,
          'estimate_version_number', null,
          'estimate_version_created_at', null
        )
      )
    );
  end if;

  v_finance := coalesce(public.effective_finance_visibility(p_project_id), 'none');

  select
    ev.id,
    ev.version_number,
    ev.created_at,
    ev.client_vat_bps
  into v_ev_id, v_ev_number, v_ev_created_at, v_client_vat_bps
  from public.estimate_versions ev
  join public.project_estimates pe
    on pe.id = ev.estimate_id
  where pe.project_id = p_project_id
    and (
      (p_estimate_version_id is not null and ev.id = p_estimate_version_id)
      or (p_estimate_version_id is null and ev.is_current)
    )
  order by ev.created_at desc
  limit 1;

  if v_finance in ('summary', 'detail') then
    select coalesce(sum(erl.client_total_price_cents), 0)::bigint
    into v_client_total_cents
    from public.estimate_resource_lines erl
    join public.estimate_works ew
      on ew.id = erl.estimate_work_id
    join public.estimate_versions ev
      on ev.id = ew.estimate_version_id
    join public.project_estimates pe
      on pe.id = ev.estimate_id
    where pe.project_id = p_project_id
      and (
        p_estimate_version_id is null
        or ew.estimate_version_id = p_estimate_version_id
      );

    select coalesce(max(ps.discount_bps), 0)
    into v_discount_bps
    from public.estimate_resource_lines erl
    join public.estimate_works ew
      on ew.id = erl.estimate_work_id
    join public.estimate_versions ev
      on ev.id = ew.estimate_version_id
    join public.project_estimates pe
      on pe.id = ev.estimate_id
    left join public.project_stages ps
      on ps.id = ew.project_stage_id
    where pe.project_id = p_project_id
      and (
        p_estimate_version_id is null
        or ew.estimate_version_id = p_estimate_version_id
      );

    select coalesce(
      (
        select jsonb_object_agg(resource_type, to_jsonb(cents))
        from (
          select
            erl.resource_type,
            sum(erl.client_total_price_cents)::bigint as cents
          from public.estimate_resource_lines erl
          join public.estimate_works ew
            on ew.id = erl.estimate_work_id
          join public.estimate_versions ev
            on ev.id = ew.estimate_version_id
          join public.project_estimates pe
            on pe.id = ev.estimate_id
          where pe.project_id = p_project_id
            and (
              p_estimate_version_id is null
              or ew.estimate_version_id = p_estimate_version_id
            )
          group by erl.resource_type
        ) agg
      ),
      '{}'::jsonb
    )
    into v_breakdown;
  end if;

  if v_finance = 'none' then
    v_upper_block := jsonb_build_object(
      'effective_finance_visibility', v_finance,
      'timing', jsonb_build_object(
        'estimate_version_id', v_ev_id,
        'estimate_version_number', v_ev_number,
        'estimate_version_created_at', v_ev_created_at
      )
    );
  else
    v_upper_block := jsonb_build_object(
      'effective_finance_visibility', v_finance,
      'timing', jsonb_build_object(
        'estimate_version_id', v_ev_id,
        'estimate_version_number', v_ev_number,
        'estimate_version_created_at', v_ev_created_at
      ),
      'client_total_cents', v_client_total_cents,
      'vat_bps', v_client_vat_bps,
      'discount_bps', v_discount_bps,
      'resource_cost_breakdown_client_safe_only', coalesce(v_breakdown, '{}'::jsonb)
    );
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'estimate_work_id', rows.estimate_work_id,
        'estimate_version_id', rows.estimate_version_id,
        'project_stage_id', rows.project_stage_id,
        'title', rows.title,
        'description', rows.description,
        'sort_order', rows.sort_order,
        'created_at', rows.created_at
      )
      order by rows.sort_order asc, rows.estimate_work_id
    ),
    '[]'::jsonb
  )
  into v_works
  from (
    select
      ew.id as estimate_work_id,
      ew.estimate_version_id,
      ew.project_stage_id,
      ew.title,
      ew.description,
      ew.sort_order,
      ew.created_at
    from public.estimate_works ew
    join public.estimate_versions ev
      on ev.id = ew.estimate_version_id
    join public.project_estimates pe
      on pe.id = ev.estimate_id
    where pe.project_id = p_project_id
      and (
        p_estimate_version_id is null
        or ew.estimate_version_id = p_estimate_version_id
      )
    order by ew.sort_order asc, ew.id
    offset v_offset
    limit v_limit
  ) rows;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'estimate_resource_line_id', rows.estimate_resource_line_id,
        'estimate_work_id', rows.estimate_work_id,
        'estimate_work_title', rows.estimate_work_title,
        'estimate_version_id', rows.estimate_version_id,
        'project_stage_title', rows.project_stage_title,
        'resource_type', rows.resource_type,
        'title', rows.title,
        'quantity', rows.quantity,
        'unit', rows.unit,
        'assignee_profile_id', rows.assignee_profile_id,
        'assignee_display_name', rows.assignee_display_name,
        'created_at', rows.created_at
      )
      || case
        when v_finance in ('summary', 'detail') then
          jsonb_build_object(
            'client_unit_price_cents', rows.client_unit_price_cents,
            'client_total_price_cents', rows.client_total_price_cents,
            'discounted_client_total_price_cents', rows.discounted_client_total_price_cents
          )
        else '{}'::jsonb
      end
      order by rows.estimate_work_sort_order asc, rows.estimate_resource_line_id
    ),
    '[]'::jsonb
  )
  into v_resource_lines
  from (
    select
      erl.id as estimate_resource_line_id,
      erl.estimate_work_id,
      ew.title as estimate_work_title,
      ew.estimate_version_id,
      ew.sort_order as estimate_work_sort_order,
      ps.title as project_stage_title,
      erl.resource_type,
      erl.title,
      erl.quantity,
      erl.unit,
      erl.client_unit_price_cents,
      erl.client_total_price_cents,
      erl.discounted_client_total_price_cents,
      erl.created_at,
      t.assignee_profile_id,
      left(coalesce(ap.full_name, ''), 120) as assignee_display_name
    from public.estimate_resource_lines erl
    join public.estimate_works ew
      on ew.id = erl.estimate_work_id
    join public.estimate_versions ev
      on ev.id = ew.estimate_version_id
    join public.project_estimates pe
      on pe.id = ev.estimate_id
    left join public.project_stages ps
      on ps.id = ew.project_stage_id
    left join public.tasks t
      on t.estimate_work_id = ew.id
    left join public.profiles ap
      on ap.id = t.assignee_profile_id
    where pe.project_id = p_project_id
      and (
        p_estimate_version_id is null
        or ew.estimate_version_id = p_estimate_version_id
      )
    order by ew.sort_order asc, erl.id
    offset v_offset
    limit v_limit
  ) rows;

  return jsonb_build_object(
    'works', v_works,
    'resource_lines', v_resource_lines,
    'upper_block', v_upper_block
  );
end;
$$;

revoke all on function public.get_estimate_operational_summary(uuid, uuid, integer, integer) from public;
grant execute on function public.get_estimate_operational_summary(uuid, uuid, integer, integer) to authenticated;
