-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260511120000_system_resource_articles_and_unit_conversions.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 3.0 — SystemResourceArticle registry (КСР seed foundation).
--
-- `system_resource_articles` is the internal master-registry of construction
-- resources. Future tables (CatalogProduct, TemplateResourceLine,
-- ResourceLine) will optionally reference an article by `rovno_sku` so that
-- a single article identity unifies vendor comparisons, price history, and
-- regional averages across user catalogs and templates.
--
-- Hierarchy (Книга → Часть → Раздел → Группа) is stored as a flat
-- `category_path text` for MVP. A parent_article_id tree may be added
-- later once the table grows past ~5K rows.
--
-- Unit handling follows Variant C from the iterations-1–4 discovery:
--   * `unit_original` keeps the raw КСР unit string ("1000 м", "маш.-ч"…).
--   * `unit_display` is the user-facing unit ("м", "ч"…).
--   * `conversion_factor` is the multiplier such that
--     quantity_in_display = quantity_in_original × conversion_factor.
--
-- The companion `unit_conversions` lookup is the source of truth for known
-- mappings; the import script applies them at seed time. Conversions seed
-- data lands in the following migration (20260511120100) so it can be
-- re-applied independently if mapping rules evolve.
--
-- Indexes are kept to b-tree only in this wave. A plain btree on `name`
-- covers equality and prefix lookup ("Газоб%") which is enough for the
-- 500–1500 row wave-1 registry.
-- TODO: switch `idx_system_resource_articles_name` to `using gin
-- (name gin_trgm_ops)` for fuzzy autocomplete once the curated-mirror
-- generator (`scripts/generate-backend-truth.mjs`) grows `pg_trgm`
-- support. Planned for Session 3 (templates UI) or Session 6 (catalogs)
-- — whichever first introduces autocomplete-by-name.

create table public.system_resource_articles (
  id uuid primary key default gen_random_uuid(),
  rovno_sku text not null unique,
  name text not null,
  category_path text not null,
  unit_display text not null,
  unit_original text not null,
  conversion_factor numeric(14,4) not null default 1,
  okpd2_code text,
  source text not null default 'fgis_ksr',
  source_version text,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint system_resource_articles_rovno_sku_nonempty
    check (length(trim(rovno_sku)) > 0),
  constraint system_resource_articles_name_nonempty
    check (length(trim(name)) > 0),
  constraint system_resource_articles_category_path_nonempty
    check (length(trim(category_path)) > 0),
  constraint system_resource_articles_unit_factor_positive
    check (conversion_factor > 0)
);

create index idx_system_resource_articles_rovno_sku
  on public.system_resource_articles(rovno_sku);

create index idx_system_resource_articles_name
  on public.system_resource_articles(name);

create index idx_system_resource_articles_category_path
  on public.system_resource_articles(category_path text_pattern_ops);

create index idx_system_resource_articles_source_version
  on public.system_resource_articles(source_version);

create index idx_system_resource_articles_archived
  on public.system_resource_articles(archived)
  where archived = false;

create trigger set_system_resource_articles_updated_at
before update on public.system_resource_articles
for each row execute function public.set_updated_at();

create table public.unit_conversions (
  unit_original text primary key,
  unit_display text not null,
  factor numeric(14,4) not null,
  constraint unit_conversions_unit_display_nonempty
    check (length(trim(unit_display)) > 0),
  constraint unit_conversions_factor_positive
    check (factor > 0)
);

grant select on table
  public.system_resource_articles,
  public.unit_conversions
to authenticated;

alter table public.system_resource_articles enable row level security;
alter table public.unit_conversions enable row level security;

-- Articles and unit conversions are a global registry: any authenticated
-- user may read. Writes happen only via service_role (CI migrations or
-- scheduled imports), so no INSERT/UPDATE/DELETE policies are defined.
create policy system_resource_articles_select on public.system_resource_articles
for select
to authenticated
using (true);

create policy unit_conversions_select on public.unit_conversions
for select
to authenticated
using (true);
