-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260504013553_layer_a_snapshot_enrichment.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 1.A — Layer A snapshot enrichment.
--
-- Replaces public.get_ai_project_snapshot to return useful operational facts
-- (stage / task / procurement / hr / participants / activity counts and a
-- short blockers slice) inside the same JSONB envelope, so the AI no longer
-- has to fall back to "I have no detail" when Layer C gating doesn't fire.
--
-- All new fields are additive. The existing keys (snapshotVersion, identity,
-- authority, summary.shortProjectDescription, summary.estimatePresence,
-- summary.estimateStatus, summary.procurementCountsByStatus,
-- summary.hrCountsByStatus, summary.participantsSummary,
-- summary.recentActivitySlice) keep their semantics — three of those four
-- nullable summary fields are now populated with real data on every project
-- that has rows. snapshotVersion bumps to 2 so consumers can detect the
-- richer payload, but the V1 contract is preserved.
--
-- Visibility envelopes:
--   * effective_finance_visibility = 'none'    -> omit estimateFinanceSummary
--                                               and hrCountsAndPaid entirely.
--   * effective_finance_visibility = 'summary' -> include cents amounts but
--                                               omit margin percent (margin
--                                               leaks the cost basis).
--   * effective_finance_visibility = 'detail'  -> include everything.
--
-- The frontend (`rovno/src/lib/ai-project-context.ts`) does not consume this
-- RPC directly today; only `supabase/functions/ai-inference` calls it. So
-- additive schema changes are safe.

create or replace function public.get_ai_project_snapshot(p_project_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_role text;
  v_ai text;
  v_fin text;
  v_docs text;
  v_title text;
  v_ptype text;
  v_pmode text;
  v_ai_desc text;
  v_current_stage_id uuid;
  v_estimate_present boolean := false;
  v_estimate_status text;
  v_assistant_estimate_status text;
  v_summary jsonb;
  v_stage_stats jsonb;
  v_work_stats jsonb;
  v_proc_counts jsonb;
  v_task_counts jsonb;
  v_blockers jsonb;
  v_hr_counts jsonb;
  v_participants jsonb;
  v_activity jsonb;
  v_doc_counts jsonb;
  v_finance_summary jsonb;
begin
  if v_uid is null then
    return null;
  end if;

  if not public.can_access_project(p_project_id) then
    return null;
  end if;

  v_ai := public.effective_ai_access_for_profile(p_project_id);
  if v_ai is null or v_ai = 'none' then
    return null;
  end if;

  v_role := public.project_role_for_profile(p_project_id, v_uid);
  if v_role is null then
    return null;
  end if;

  v_fin := coalesce(public.effective_finance_visibility(p_project_id), 'none');
  v_docs := coalesce(public.effective_internal_docs_visibility(p_project_id), 'none');

  select p.title, p.project_type, p.project_mode, p.ai_description, p.current_stage_id
  into v_title, v_ptype, v_pmode, v_ai_desc, v_current_stage_id
  from public.projects p
  where p.id = p_project_id;

  if not found then
    return null;
  end if;

  -- Estimate presence + status (unchanged from V1).
  select exists (
    select 1 from public.project_estimates pe where pe.project_id = p_project_id
  ) into v_estimate_present;

  select pe.status
  into v_estimate_status
  from public.project_estimates pe
  where pe.project_id = p_project_id
  order by pe.updated_at desc, pe.created_at desc
  limit 1;

  v_assistant_estimate_status := case
    when not coalesce(v_estimate_present, false) then null::text
    when v_estimate_status = 'draft' then 'draft'
    when v_estimate_status = 'approved' then 'approved'
    when v_estimate_status = 'archived' then 'archived'
    else coalesce(v_estimate_status, 'unknown')
  end;

  -- ---- stageStats: total / completed / inProgress / open + currentStageTitle ----
  with s as (
    select id, title, status from public.project_stages where project_id = p_project_id
  )
  select jsonb_build_object(
    'total', count(*),
    'completed', count(*) filter (where status = 'completed'),
    'inProgress', count(*) filter (where status = 'in_progress'),
    'open', count(*) filter (where status = 'open'),
    'currentStageId', v_current_stage_id,
    'currentStageTitle', (select title from s where id = v_current_stage_id)
  )
  into v_stage_stats
  from s;

  -- ---- workStats: count of estimate_works for the current/most-recent estimate version ----
  with cur_ev as (
    select ev.id
    from public.estimate_versions ev
    join public.project_estimates pe on pe.id = ev.estimate_id
    where pe.project_id = p_project_id and ev.is_current = true
    order by ev.created_at desc
    limit 1
  )
  select jsonb_build_object('total', count(*))
  into v_work_stats
  from public.estimate_works ew
  where ew.estimate_version_id in (select id from cur_ev);

  -- ---- procurementCountsByStatus ----
  select jsonb_object_agg(status, n)
  into v_proc_counts
  from (
    select status, count(*)::int as n
    from public.procurement_items
    where project_id = p_project_id
    group by status
  ) t;

  -- ---- taskCountsByStatus ----
  select jsonb_object_agg(status, n)
  into v_task_counts
  from (
    select status, count(*)::int as n
    from public.tasks
    where project_id = p_project_id
    group by status
  ) t;

  -- ---- blockers: at most 5 currently-blocked tasks; reason from description prefix when present ----
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'taskId', t.id,
      'taskTitle', t.title,
      -- Conventionally task descriptions for blocked tasks start with "Заблокирована: <reason>".
      -- Strip that prefix where present so the assistant gets a clean reason string.
      'reason', regexp_replace(coalesce(t.description, ''), '^[Зз]аблокирован[аоы]?:\s*', ''),
      'dueAt', t.due_at
    )
    order by t.due_at nulls last, t.updated_at desc
  ), '[]'::jsonb)
  into v_blockers
  from (
    select id, title, description, due_at, updated_at
    from public.tasks
    where project_id = p_project_id and status = 'blocked'
    order by due_at nulls last, updated_at desc
    limit 5
  ) t;

  -- ---- hrCountsAndPaid: items + status histogram + paid sum + planned sum
  --      (finance-gated — null when visibility = 'none').
  --      Cents amounts are rounded to nearest 100₽ when visibility = 'summary'.
  if v_fin <> 'none' then
    with items as (
      select id, planned_cost_cents, status from public.hr_items where project_id = p_project_id
    ), paid as (
      select coalesce(sum(amount_cents), 0)::bigint as paid_cents
      from public.hr_payments where project_id = p_project_id and status = 'paid'
    ), planned as (
      select coalesce(sum(planned_cost_cents), 0)::bigint as planned_cents from items
    ), by_status as (
      select coalesce(jsonb_object_agg(status, n), '{}'::jsonb) as bs
      from (select status, count(*)::int as n from items group by status) t
    )
    select jsonb_build_object(
      'items', (select count(*) from items),
      'byStatus', (select bs from by_status),
      'paidCents', case when v_fin = 'detail' then (select paid_cents from paid)
                       else round((select paid_cents from paid)::numeric / 10000) * 10000 end,
      'plannedTotalCents', case when v_fin = 'detail' then (select planned_cents from planned)
                                else round((select planned_cents from planned)::numeric / 10000) * 10000 end
    )
    into v_hr_counts;
  end if;

  -- ---- estimateFinanceSummary: planned cost from current estimate version ----
  if v_fin <> 'none' and coalesce(v_estimate_present, false) then
    with cur_ev as (
      select ev.id
      from public.estimate_versions ev
      join public.project_estimates pe on pe.id = ev.estimate_id
      where pe.project_id = p_project_id and ev.is_current = true
      order by ev.created_at desc
      limit 1
    ), w_total as (
      select coalesce(sum(planned_cost_cents), 0)::bigint as total
      from public.estimate_works
      where estimate_version_id in (select id from cur_ev)
    ), rl_totals as (
      select coalesce(sum(rl.total_price_cents), 0)::bigint as cost_total,
             coalesce(sum(coalesce(rl.discounted_client_total_price_cents, rl.client_total_price_cents)), 0)::bigint as client_total
      from public.estimate_resource_lines rl
      join public.estimate_works ew on ew.id = rl.estimate_work_id
      where ew.estimate_version_id in (select id from cur_ev)
    )
    select jsonb_build_object(
      'plannedCostCents', case when v_fin = 'detail' then (select total from w_total)
                              else round((select total from w_total)::numeric / 10000) * 10000 end,
      'clientTotalCents', case when v_fin = 'detail' then (select client_total from rl_totals)
                              else round((select client_total from rl_totals)::numeric / 10000) * 10000 end,
      'costTotalCents',   case when v_fin = 'detail' then (select cost_total from rl_totals)
                              else round((select cost_total from rl_totals)::numeric / 10000) * 10000 end,
      'marginPct', case when v_fin = 'detail' and (select client_total from rl_totals) > 0
                       then round(((select client_total from rl_totals) - (select cost_total from rl_totals))::numeric * 100
                                  / (select client_total from rl_totals), 1)
                       else null end
    )
    into v_finance_summary;
  end if;

  -- ---- participantsSummary: roles + invitation status ----
  with members as (
    select role, 'accepted'::text as bucket from public.project_members where project_id = p_project_id
    union all
    select role,
           case when status in ('accepted', 'redeemed') then 'accepted'
                when status in ('pending', 'sent') then 'pending'
                else status end as bucket
    from public.project_invites
    where project_id = p_project_id and accepted_at is null
  )
  select jsonb_build_object(
    'total', count(*),
    'byRole', coalesce((
      select jsonb_object_agg(role || '_' || bucket, n)
      from (select role, bucket, count(*)::int as n from members group by role, bucket) g
    ), '{}'::jsonb)
  )
  into v_participants
  from members;

  -- ---- recentActivitySlice: last 5 events with type + when ----
  select coalesce(jsonb_agg(
    jsonb_build_object(
      'at', a.created_at,
      'type', a.action_type,
      'entityType', a.entity_type,
      'entityId', a.entity_id
    )
    order by a.created_at desc
  ), '[]'::jsonb)
  into v_activity
  from (
    select created_at, action_type, entity_type, entity_id
    from public.activity_events
    where project_id = p_project_id
    order by created_at desc
    limit 5
  ) a;

  -- ---- documentCounts: documents + media (visibility-aware) ----
  with d as (
    select count(*)::int as n
    from public.documents
    where project_id = p_project_id
      and (v_docs in ('view', 'edit') or visibility_class <> 'internal')
  ), m as (
    select count(*)::int as n
    from public.project_media
    where project_id = p_project_id
      and (v_docs in ('view', 'edit') or visibility_class <> 'internal')
  )
  select jsonb_build_object(
    'documents', (select n from d),
    'media',     (select n from m)
  )
  into v_doc_counts;

  -- ---- Assemble summary object ----
  v_summary := jsonb_build_object(
    'shortProjectDescription', v_ai_desc,
    'estimatePresence', coalesce(v_estimate_present, false),
    'estimateStatus', v_assistant_estimate_status,
    'stageStats', v_stage_stats,
    'workStats', v_work_stats,
    'procurementCountsByStatus', v_proc_counts,
    'taskCountsByStatus', v_task_counts,
    'blockers', v_blockers,
    'participantsSummary', v_participants,
    'recentActivitySlice', v_activity,
    'documentCounts', v_doc_counts,
    -- V1-compat: hrCountsByStatus is the bare status histogram. The richer
    -- hrCountsAndPaid lives in its own key. Both are derived from the same
    -- v_hr_counts source so the gate-flip semantics stay consistent.
    'hrCountsByStatus', case when v_hr_counts is null then null
                             else (v_hr_counts->'byStatus') end
  );

  if v_finance_summary is not null then
    v_summary := v_summary || jsonb_build_object('estimateFinanceSummary', v_finance_summary);
  end if;
  if v_hr_counts is not null then
    v_summary := v_summary || jsonb_build_object('hrCountsAndPaid', v_hr_counts);
  end if;

  return jsonb_build_object(
    'snapshotVersion', 2,
    'identity', jsonb_build_object(
      'projectId', p_project_id,
      'title', v_title,
      'projectType', v_ptype,
      'projectMode', v_pmode
    ),
    'authority', jsonb_build_object(
      'userRole', v_role,
      'aiAccessEnvelope', v_ai,
      'effectiveVisibilityEnvelope', jsonb_build_object(
        'financeVisibility', v_fin,
        'internalDocsVisibility', v_docs
      )
    ),
    'summary', v_summary
  );
end;
$$;

revoke all on function public.get_ai_project_snapshot(uuid) from public;
grant execute on function public.get_ai_project_snapshot(uuid) to authenticated;
