-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260507160000_org_policy_resilience.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Investigation continues: 42501 returned even though 20260507120000
-- rebuilt the INSERT policy and a fresh JWT briefly succeeded. Re-rebuild
-- ALL 4 organizations policies defensively in one transaction, plus
-- expose a fresh diagnostic RPC so we can re-inspect live state without
-- manual psql.

drop policy if exists organizations_select on public.organizations;
drop policy if exists organizations_insert on public.organizations;
drop policy if exists organizations_update on public.organizations;
drop policy if exists organizations_delete on public.organizations;

create policy organizations_select on public.organizations
for select
to authenticated
using (public.is_org_member(id));

create policy organizations_insert on public.organizations
for insert
to authenticated
with check (owner_profile_id = auth.uid());

create policy organizations_update on public.organizations
for update
to authenticated
using (public.can_manage_org(id))
with check (true);

create policy organizations_delete on public.organizations
for delete
to authenticated
using (owner_profile_id = auth.uid());

-- Diagnostic: returns the live state of organizations RLS plus an
-- inline INSERT-test (under SECURITY DEFINER context) for comparison.
create or replace function public.__debug_org_rls_state2()
returns jsonb
language sql
stable
security definer
set search_path = public, pg_catalog
as $$
  select jsonb_build_object(
    'policies', (
      select coalesce(jsonb_agg(jsonb_build_object(
        'policyname', policyname,
        'permissive', permissive,
        'roles', roles,
        'cmd', cmd,
        'qual', qual,
        'with_check', with_check
      ) order by policyname), '[]'::jsonb)
      from pg_policies
      where schemaname = 'public' and tablename = 'organizations'
    ),
    'rls_enabled', (
      select c.relrowsecurity
      from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relname = 'organizations'
    ),
    'projects_insert_policy', (
      select with_check
      from pg_policies
      where schemaname = 'public' and tablename = 'projects' and policyname = 'projects_insert'
    ),
    'auth_uid_in_definer_context', auth.uid()
  );
$$;
revoke all on function public.__debug_org_rls_state2() from public;
grant execute on function public.__debug_org_rls_state2() to authenticated;
grant execute on function public.__debug_org_rls_state2() to anon;
