-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260611120000_project_estimates_execution_status.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Server-side execution status for estimates (finance-suite Phase 4 prerequisite).
--
-- The frontend's execution status (planning | in_work | paused | finished) lives only in
-- the browser store today: project_estimates.status is the approval lifecycle
-- (draft | approved | archived), and "finished"/"paused" are unrepresentable server-side.
-- The portfolio finance rollup (get_portfolio_finance_snapshot) needs the real status for
-- its pipeline buckets and finished-project semantics.
--
-- Nullable by design, no backfill: the frontend writes it on status transitions going
-- forward; readers fall back to the historical inference
--   coalesce(execution_status, case when status = 'approved' then 'in_work' else 'planning' end)
-- which matches the remote-persisted part of the browser-side inference (root status
-- 'approved' → in_work). The browser additionally infers in_work from local task-activity
-- signals that are not persisted server-side; those are not mirrored here.

alter table public.project_estimates
  add column execution_status text
  check (
    execution_status is null
    or execution_status in ('planning', 'in_work', 'paused', 'finished')
  );
