-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260320130000_codex_review_findings_fixes.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create or replace function public.enforce_tasks_estimate_lineage_scope()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.project_stages ps
    where ps.id = new.stage_id
      and ps.project_id = new.project_id
  ) then
    raise exception 'Task stage must belong to the same project';
  end if;

  if new.estimate_work_id is not null then
    if not exists (
      select 1
      from public.estimate_works ew
      join public.estimate_versions ev
        on ev.id = ew.estimate_version_id
      join public.project_estimates pe
        on pe.id = ev.estimate_id
      where ew.id = new.estimate_work_id
        and ew.project_stage_id = new.stage_id
        and pe.project_id = new.project_id
    ) then
      raise exception 'Task estimate_work_id must match task project and stage';
    end if;
  end if;

  return new;
end;
$$;

create trigger enforce_tasks_estimate_lineage_scope
before insert or update of project_id, stage_id, estimate_work_id on public.tasks
for each row execute function public.enforce_tasks_estimate_lineage_scope();

create or replace function public.guard_estimate_work_stage_reassignment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.project_stage_id is distinct from old.project_stage_id
     and exists (
       select 1
       from public.tasks t
       where t.estimate_work_id = old.id
     ) then
    raise exception 'Cannot reassign estimate work stage while linked tasks exist';
  end if;

  return new;
end;
$$;

create trigger guard_estimate_work_stage_reassignment
before update of project_stage_id on public.estimate_works
for each row execute function public.guard_estimate_work_stage_reassignment();

drop policy if exists projects_update on public.projects;

create policy projects_update on public.projects
for update
to authenticated
using (
  owner_profile_id = auth.uid()
)
with check (
  owner_profile_id = auth.uid()
  or exists (
    select 1
    from public.project_members pm
    where pm.project_id = id
      and pm.profile_id = owner_profile_id
      and pm.role in ('owner', 'co_owner')
  )
);

create or replace function public.finalize_project_media_upload(
  p_upload_intent_id uuid,
  p_task_id uuid default null,
  p_is_final boolean default null
)
returns table (
  project_media_id uuid,
  storage_object_id uuid,
  project_id uuid,
  bucket text,
  object_path text,
  filename text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_intent public.project_media_upload_intents%rowtype;
  v_storage_object_id uuid;
  v_project_media_id uuid;
  v_object_exists boolean;
  v_effective_task_id uuid;
  v_effective_is_final boolean;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_intent
  from public.project_media_upload_intents
  where id = p_upload_intent_id
  for update;

  if not found then
    raise exception 'Upload intent not found';
  end if;

  if v_intent.created_by <> auth.uid() then
    raise exception 'Upload intent does not belong to current user';
  end if;

  if not public.can_write_project_content(v_intent.project_id) then
    raise exception 'Project write access required';
  end if;

  v_effective_task_id := coalesce(p_task_id, v_intent.task_id);
  v_effective_is_final := coalesce(p_is_final, v_intent.is_final, false);

  if v_effective_is_final and v_effective_task_id is null then
    raise exception 'Final media requires task_id';
  end if;

  if v_effective_task_id is not null then
    if not exists (
      select 1
      from public.tasks t
      where t.id = v_effective_task_id
        and t.project_id = v_intent.project_id
    ) then
      raise exception 'Task must belong to project';
    end if;
  end if;

  if v_intent.project_media_id is not null then
    update public.project_media
    set task_id = v_effective_task_id,
        is_final = v_effective_is_final
    where id = v_intent.project_media_id;

    update public.project_media_upload_intents
    set task_id = v_effective_task_id,
        is_final = v_effective_is_final,
        finalized_at = coalesce(finalized_at, now())
    where id = v_intent.id;

    return query
    select
      pm.id,
      pm.storage_object_id,
      pm.project_id,
      so.bucket,
      so.object_path,
      so.filename
    from public.project_media pm
    join public.storage_objects so
      on so.id = pm.storage_object_id
    where pm.id = v_intent.project_media_id
      and so.bucket = v_intent.bucket
      and so.object_path = v_intent.object_path;

    if found then
      return;
    end if;

    raise exception 'Upload intent is finalized but linked project media is unavailable';
  end if;

  select exists (
    select 1
    from storage.objects so
    where so.bucket_id = v_intent.bucket
      and so.name = v_intent.object_path
  )
  into v_object_exists;

  if not v_object_exists then
    raise exception 'Storage object is not accessible';
  end if;

  insert into public.storage_objects (
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    uploaded_by
  )
  values (
    v_intent.bucket,
    v_intent.object_path,
    v_intent.filename,
    v_intent.mime_type,
    v_intent.size_bytes,
    v_intent.created_by
  )
  on conflict (bucket, object_path) do nothing;

  select so.id
  into v_storage_object_id
  from public.storage_objects so
  where so.bucket = v_intent.bucket
    and so.object_path = v_intent.object_path;

  if v_storage_object_id is null then
    raise exception 'Storage object linkage could not be resolved';
  end if;

  insert into public.project_media (
    project_id,
    storage_object_id,
    uploaded_by,
    media_type,
    caption,
    task_id,
    is_final
  )
  values (
    v_intent.project_id,
    v_storage_object_id,
    v_intent.created_by,
    v_intent.media_type,
    v_intent.caption,
    v_effective_task_id,
    v_effective_is_final
  )
  returning id
  into v_project_media_id;

  update public.project_media_upload_intents
  set project_media_id = v_project_media_id,
      task_id = v_effective_task_id,
      is_final = v_effective_is_final,
      finalized_at = coalesce(finalized_at, now())
  where id = v_intent.id;

  return query
  select
    pm.id,
    pm.storage_object_id,
    pm.project_id,
    so.bucket,
    so.object_path,
    so.filename
  from public.project_media pm
  join public.storage_objects so
    on so.id = pm.storage_object_id
  where pm.id = v_project_media_id;
end;
$$;
