-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260613120500_browse_canonical_catalog.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 4 — browse_canonical_catalog: the resource-library browse tree for the
-- estimate constructor's "Каталоги" tab (and autocomplete subcategory drill-down).
--
--   browse_canonical_catalog(p_subcategory default null)
--     p_subcategory NULL  → tree mode: { groups:[ { group, subcategories:[ { subcategory, leaf_count } ] } ] }
--     p_subcategory given → drill mode: { subcategory, resources:[ { id, name, default_resource_type, unit_display, rovno_sku, subcategory } ] }
--
-- Why this shape (verified against live data):
--   * kind='subcategory' rows are NOT reliable headers — only 28 of ~1,959 have
--     names matching a real leaf grouping; most carry product-like names. So the
--     browse tree is derived from the CURATED LEAVES' category_path + subcategory,
--     not from kind='subcategory' rows.
--   * For the 821 curated rovno_seed leaves, category_path is
--     "rovno_seed / <group> / <subcategory>" and the `subcategory` column equals
--     the last path segment (821/821). The group is the middle segment
--     (split_part(category_path, ' / ', 2)) — e.g. Материалы / Инструменты /
--     Логистика и накладные.
--   * The 987 curated fgis_ksr leaves have NULL subcategory and a different
--     "Книга > Часть > Раздел" path, so they are intentionally OUT of the wave-1
--     browse tree. They remain reachable via search_canonical_library and
--     get_resource_article_detail.
--
-- Authorization: canonical library is global read for signed-in users →
-- security definer + grant to authenticated.

create or replace function public.browse_canonical_catalog(
  p_subcategory text default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  if p_subcategory is null then
    -- Tree mode: group -> subcategory (+ leaf counts), no leaf rows.
    select jsonb_build_object(
      'groups', coalesce(jsonb_agg(group_obj order by grp), '[]'::jsonb)
    )
      into v_result
    from (
      select
        grp,
        jsonb_build_object(
          'group', grp,
          'subcategories', jsonb_agg(
            jsonb_build_object('subcategory', subcategory, 'leaf_count', leaf_count)
            order by subcategory
          )
        ) as group_obj
      from (
        select
          coalesce(nullif(split_part(category_path, ' / ', 2), ''), 'Прочее') as grp,
          subcategory,
          count(*)::int as leaf_count
        from public.system_resource_articles
        where kind = 'leaf'
          and archived = false
          and is_residential_curated = true
          and subcategory is not null
        group by 1, subcategory
      ) per_subcat
      group by grp
    ) per_group;
  else
    -- Drill mode: curated leaves in the given subcategory.
    select jsonb_build_object(
      'subcategory', p_subcategory,
      'resources', coalesce(jsonb_agg(obj order by nm), '[]'::jsonb)
    )
      into v_result
    from (
      select
        jsonb_build_object(
          'id', ra.id,
          'name', coalesce(ra.canonical_name, ra.name),
          'default_resource_type', ra.default_resource_type,
          'unit_display', ra.unit_display,
          'rovno_sku', ra.rovno_sku,
          'subcategory', ra.subcategory
        ) as obj,
        coalesce(ra.canonical_name, ra.name) as nm
      from public.system_resource_articles ra
      where ra.kind = 'leaf'
        and ra.archived = false
        and ra.is_residential_curated = true
        and ra.subcategory = p_subcategory
    ) leaves;
  end if;

  return coalesce(v_result, jsonb_build_object('groups', '[]'::jsonb));
end;
$$;

revoke all on function public.browse_canonical_catalog(text) from public;
grant execute on function public.browse_canonical_catalog(text) to authenticated;
