-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260613120400_add_library_work_to_estimate.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 4 — add_library_work_to_estimate: granular "add one library work into
-- an existing project stage" for the sequential apply workflow.
--
-- apply_template_stage_to_estimate copies a whole template stage subtree. This
-- RPC is its single-work counterpart: it copies ONE template_work (with its
-- default template_resource_lines) into an existing project_stage on a live
-- estimate version. It backs:
--   * the work-level autocomplete "Применить" button (type a work name inside a
--     stage, apply just that work), and
--   * the sequential constructor flow (stage → work → resource), where the user
--     adds an empty/partial stage then fills in individual works.
--
--   add_library_work_to_estimate(
--     p_estimate_version_id,
--     p_project_stage_id,
--     p_template_work_id,
--     p_sort_position default null
--   ) returns jsonb { work_id, project_stage_id, resource_line_ids[], total_planned_cost_cents }
--
-- It mirrors apply_template_stage_to_estimate's library-FK propagation: the new
-- estimate_work carries system_work_article_id and each new estimate_resource_line
-- carries system_resource_article_id, so the row indicator + resource modal work.
--
-- Authorization (same model as apply_template_stage_to_estimate):
--   * can_write_project_content on the destination project, and
--   * can_read_template on the source template.
-- The destination project_stage must belong to the same project as the estimate
-- version (prevents grafting a work onto another project's stage).

create or replace function public.add_library_work_to_estimate(
  p_estimate_version_id uuid,
  p_project_stage_id uuid,
  p_template_work_id uuid,
  p_sort_position integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_project_id uuid;
  v_stage_project_id uuid;
  v_work_record record;
  v_new_work_id uuid;
  v_new_resource_line_ids uuid[] := '{}';
  v_max_existing_sort int;
  v_target_sort int;
  v_resource_record record;
  v_new_resource_id uuid;
  v_resource_total_cents bigint;
  v_total_planned_cost bigint := 0;
begin
  -- Resolve + authorize the destination project via the estimate version.
  select pe.project_id
    into v_project_id
  from public.estimate_versions ev
  join public.project_estimates pe on pe.id = ev.estimate_id
  where ev.id = p_estimate_version_id;

  if v_project_id is null then
    raise exception 'Estimate version % not found', p_estimate_version_id
      using errcode = 'P0002';
  end if;
  if not public.can_write_project_content(v_project_id) then
    raise exception 'Forbidden: cannot write project content'
      using errcode = '42501';
  end if;

  -- The destination stage must belong to the same project.
  select ps.project_id
    into v_stage_project_id
  from public.project_stages ps
  where ps.id = p_project_stage_id;

  if v_stage_project_id is null then
    raise exception 'Project stage % not found', p_project_stage_id
      using errcode = 'P0002';
  end if;
  if v_stage_project_id <> v_project_id then
    raise exception 'Project stage % does not belong to this estimate version''s project', p_project_stage_id
      using errcode = '22023';
  end if;

  -- Resolve + authorize the source template work (and its owning template).
  select tw.id,
         tw.title,
         tw.description,
         tw.system_work_article_id,
         et.owner_kind,
         et.owner_id
    into v_work_record
  from public.template_works tw
  join public.template_stages ts on ts.id = tw.template_stage_id
  join public.estimate_templates et on et.id = ts.estimate_template_id
  where tw.id = p_template_work_id;

  if v_work_record.id is null then
    raise exception 'Template work % not found', p_template_work_id
      using errcode = 'P0002';
  end if;
  if not public.can_read_template(v_work_record.owner_kind, v_work_record.owner_id) then
    raise exception 'Forbidden: cannot read source template'
      using errcode = '42501';
  end if;

  -- Place the new work after existing works in the destination stage.
  select coalesce(max(sort_order), 0)
    into v_max_existing_sort
  from public.estimate_works
  where estimate_version_id = p_estimate_version_id
    and project_stage_id = p_project_stage_id;

  v_target_sort := coalesce(p_sort_position, v_max_existing_sort + 1);
  if v_target_sort <= 0 then
    raise exception 'sort_position must be positive (got %)', v_target_sort
      using errcode = '22023';
  end if;

  -- When an explicit position is given, shift existing works in this stage down
  -- to open the slot (insert-at-position). estimate_works has no
  -- unique(project_stage_id, sort_order) constraint, so without this an explicit
  -- p_sort_position would silently duplicate an existing work's order. The
  -- default (append: max+1) path matches nothing here and needs no shift.
  -- Estimate edits are serialized per editing user, so concurrent same-stage
  -- inserts racing on max(sort_order) are not a practical concern.
  if p_sort_position is not null then
    update public.estimate_works
       set sort_order = sort_order + 1
     where estimate_version_id = p_estimate_version_id
       and project_stage_id = p_project_stage_id
       and sort_order >= v_target_sort;
  end if;

  insert into public.estimate_works (
    estimate_version_id,
    project_stage_id,
    title,
    description,
    sort_order,
    planned_cost_cents,
    system_work_article_id
  )
  values (
    p_estimate_version_id,
    p_project_stage_id,
    v_work_record.title,
    v_work_record.description,
    v_target_sort,
    0,
    v_work_record.system_work_article_id
  )
  returning id into v_new_work_id;

  -- Copy the template work's default resource lines.
  for v_resource_record in
    select *
    from public.template_resource_lines
    where template_work_id = p_template_work_id
    order by sort_hint, title
  loop
    -- round() before cast avoids truncating fractional cents on non-integer
    -- quantities (matches apply_template_stage_to_estimate).
    v_resource_total_cents := case
      when v_resource_record.default_cost_unit_cents is not null
        then round(v_resource_record.qty_default * v_resource_record.default_cost_unit_cents)::bigint
      else null
    end;

    insert into public.estimate_resource_lines (
      estimate_work_id,
      resource_type,
      title,
      quantity,
      unit,
      unit_price_cents,
      total_price_cents,
      markup_bps,
      discount_bps_override,
      system_resource_article_id
    )
    values (
      v_new_work_id,
      v_resource_record.resource_type,
      v_resource_record.title,
      v_resource_record.qty_default,
      v_resource_record.unit_display,
      v_resource_record.default_cost_unit_cents,
      v_resource_total_cents,
      v_resource_record.default_markup_bps,
      v_resource_record.default_discount_bps,
      v_resource_record.system_resource_article_id
    )
    returning id into v_new_resource_id;

    v_new_resource_line_ids := v_new_resource_line_ids || v_new_resource_id;

    if v_resource_total_cents is not null then
      v_total_planned_cost := v_total_planned_cost + v_resource_total_cents;
    end if;
  end loop;

  update public.estimate_works
     set planned_cost_cents = (
       select coalesce(sum(total_price_cents), 0)::bigint
       from public.estimate_resource_lines
       where estimate_work_id = v_new_work_id
     )
   where id = v_new_work_id;

  return jsonb_build_object(
    'work_id', v_new_work_id,
    'project_stage_id', p_project_stage_id,
    'resource_line_ids', to_jsonb(v_new_resource_line_ids),
    'total_planned_cost_cents', v_total_planned_cost
  );
end;
$$;

revoke all on function public.add_library_work_to_estimate(uuid, uuid, uuid, integer) from public;
grant execute on function public.add_library_work_to_estimate(uuid, uuid, uuid, integer) to authenticated;
