-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260506150000_fix_org_rls_recursion.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 2 hotfix #3 — addresses runtime RLS recursion (42P17) on
-- organizations / org_members.
--
-- Bug: the original policies in 20260506120100 inlined cross-table EXISTS
-- subqueries:
--   organizations_select  → SELECT 1 FROM org_members …
--   org_members_select    → SELECT 1 FROM organizations …  (recursive!)
-- Postgres invokes RLS on each subquery; the org_members → organizations
-- branch re-enters organizations_select, which re-enters org_members,
-- producing "infinite recursion detected in policy for relation
-- 'organizations'" on the very first INSERT (the post-insert SELECT).
--
-- Fix: replace the inline subqueries with the existing security-definer
-- helpers (is_org_member / can_manage_org). SECURITY DEFINER functions
-- bypass caller RLS for their internal queries, breaking the recursion.

drop policy if exists organizations_select on public.organizations;
drop policy if exists organizations_update on public.organizations;
drop policy if exists org_members_select on public.org_members;
drop policy if exists org_members_insert on public.org_members;
drop policy if exists org_members_update on public.org_members;
drop policy if exists org_members_delete on public.org_members;

create policy organizations_select on public.organizations
for select
to authenticated
using (public.is_org_member(id));

create policy organizations_update on public.organizations
for update
to authenticated
using (public.can_manage_org(id))
with check (true);

-- A user always sees their own membership row (cheap direct check, no
-- helper call). Otherwise they see fellow members of an org they belong to.
create policy org_members_select on public.org_members
for select
to authenticated
using (
  profile_id = auth.uid()
  or public.is_org_member(org_id)
);

create policy org_members_insert on public.org_members
for insert
to authenticated
with check (public.can_manage_org(org_id));

create policy org_members_update on public.org_members
for update
to authenticated
using (public.can_manage_org(org_id))
with check (public.can_manage_org(org_id));

-- Self-removal is always allowed (subject to last-owner trigger);
-- otherwise owner/admin can remove members.
create policy org_members_delete on public.org_members
for delete
to authenticated
using (
  profile_id = auth.uid()
  or public.can_manage_org(org_id)
);
