-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260507150000_drop_org_debug_rpcs.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Drop the diagnostic RPCs introduced by 20260507130000 and 20260507140000.
--
-- Used to root-cause the 42501 / "new row violates row-level security policy"
-- on organizations after the rebuild fix. Confirmed: the rebuild migration
-- (20260507120000) was the right fix; the failing INSERTs we observed
-- happened before the policy reload took effect end-to-end. Once we
-- re-tested with fresh JWTs after the deploy chain finished, INSERT
-- returns 201 and the AFTER trigger creates the org_members owner row
-- as designed.
--
-- These functions were always meant to be temporary; dropping them so
-- the schema doesn't carry permanent debug surface.

drop function if exists public.__debug_org_rls_state();
drop function if exists public.__debug_try_insert_org(text);
