-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260512140000_template_check_constraints_and_apply_rpc_hardening.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 3.1 follow-up — code-review hardening on the template tree.
--
-- Four changes:
--
--   1. `sort_hint > 0` invariant on the three template tables, so a template
--      author cannot save a row that later breaks `apply_template_stage_to_estimate`
--      against `estimate_works.sort_order > 0` and (for stages) the
--      `(project_id, sort_order)` unique constraint via project_stages.
--
--   2. `scope_tag` enum check on template_stages, mirroring the parent
--      `estimate_templates.scope` vocabulary so child rows cannot drift
--      into free-text values that the picker UI would have to special-case.
--      All seeded values fall inside the parent enum.
--
--   3. `apply_template_stage_to_estimate` re-issued with three fixes:
--        a. Pre-validate `p_sort_position` against existing project_stages so
--           a caller-supplied collision raises a clear 23505 with a message
--           pointing at the offending position, instead of bubbling up a
--           generic unique-constraint violation from the INSERT.
--        b. Use `round(...)::bigint` for the qty * unit-cost cents math so
--           fractional quantities (e.g. 1.5 × 99 = 148.5) round half-up to
--           149 cents instead of truncating to 148.
--        c. Skip the per-work `update planned_cost_cents = sum(...)` when
--           zero resource lines were inserted for that work — the row
--           already carries planned_cost_cents = 0 from the INSERT, so the
--           recompute would write the same value.
--
-- Function signature is preserved verbatim — body-only change via
-- `create or replace function`. Existing grants and revokes stay attached
-- (Postgres preserves them across create-or-replace for the same signature;
-- the backend-truth generator test #11 covers exactly this case).

alter table public.template_stages
  add constraint template_stages_sort_hint_positive
  check (sort_hint > 0);

alter table public.template_works
  add constraint template_works_sort_hint_positive
  check (sort_hint > 0);

alter table public.template_resource_lines
  add constraint template_resource_lines_sort_hint_positive
  check (sort_hint > 0);

alter table public.template_stages
  add constraint template_stages_scope_tag_enum
  check (scope_tag in ('ИЖС','ремонт','ландшафт','баня','гараж','инженерка','коммерческое','general'));

create or replace function public.apply_template_stage_to_estimate(
  p_estimate_version_id uuid,
  p_template_stage_id uuid,
  p_sort_position integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_project_id uuid;
  v_template_id uuid;
  v_owner_kind text;
  v_owner_id uuid;
  v_stage_record record;
  v_new_stage_id uuid;
  v_new_work_ids uuid[] := '{}';
  v_new_resource_line_ids uuid[] := '{}';
  v_max_existing_sort int;
  v_target_sort int;
  v_work_record record;
  v_new_work_id uuid;
  v_work_resource_count int;
  v_resource_record record;
  v_new_resource_id uuid;
  v_resource_total_cents bigint;
  v_total_planned_cost bigint := 0;
begin
  -- Resolve and authorize the destination project.
  select pe.project_id
    into v_project_id
  from public.estimate_versions ev
  join public.project_estimates pe on pe.id = ev.estimate_id
  where ev.id = p_estimate_version_id;

  if v_project_id is null then
    raise exception 'Estimate version % not found', p_estimate_version_id
      using errcode = 'P0002';
  end if;
  if not public.can_write_project_content(v_project_id) then
    raise exception 'Forbidden: cannot write project content'
      using errcode = '42501';
  end if;

  -- Resolve and authorize the source template stage.
  select ts.estimate_template_id, et.owner_kind, et.owner_id
    into v_template_id, v_owner_kind, v_owner_id
  from public.template_stages ts
  join public.estimate_templates et on et.id = ts.estimate_template_id
  where ts.id = p_template_stage_id;

  if v_template_id is null then
    raise exception 'Template stage % not found', p_template_stage_id
      using errcode = 'P0002';
  end if;
  if not public.can_read_template(v_owner_kind, v_owner_id) then
    raise exception 'Forbidden: cannot read source template'
      using errcode = '42501';
  end if;

  select * into v_stage_record
  from public.template_stages
  where id = p_template_stage_id;

  -- Choose a sort_order that does not collide with existing project_stages.
  -- The unique (project_id, sort_order) constraint on project_stages would
  -- otherwise surface as a generic 23505 from the INSERT below; raise a
  -- targeted error with the offending position instead.
  select coalesce(max(sort_order), 0)
    into v_max_existing_sort
  from public.project_stages
  where project_id = v_project_id;

  if p_sort_position is not null then
    if p_sort_position <= 0 then
      raise exception 'sort_position must be positive (got %)', p_sort_position
        using errcode = '22023';
    end if;
    if exists (
      select 1
      from public.project_stages
      where project_id = v_project_id
        and sort_order = p_sort_position
    ) then
      raise exception 'sort_position % collides with an existing project_stage', p_sort_position
        using errcode = '23505';
    end if;
    v_target_sort := p_sort_position;
  else
    v_target_sort := v_max_existing_sort + 1;
  end if;

  insert into public.project_stages (project_id, title, description, sort_order, status)
  values (
    v_project_id,
    v_stage_record.title,
    v_stage_record.description,
    v_target_sort,
    'open'
  )
  returning id into v_new_stage_id;

  -- Copy works and their resource lines, preserving sort_hint as sort_order.
  for v_work_record in
    select *
    from public.template_works
    where template_stage_id = p_template_stage_id
    order by sort_hint, title
  loop
    insert into public.estimate_works (
      estimate_version_id,
      project_stage_id,
      title,
      description,
      sort_order,
      planned_cost_cents
    )
    values (
      p_estimate_version_id,
      v_new_stage_id,
      v_work_record.title,
      v_work_record.description,
      v_work_record.sort_hint,
      0
    )
    returning id into v_new_work_id;

    v_new_work_ids := v_new_work_ids || v_new_work_id;

    v_work_resource_count := 0;

    for v_resource_record in
      select *
      from public.template_resource_lines
      where template_work_id = v_work_record.id
      order by sort_hint, title
    loop
      v_work_resource_count := v_work_resource_count + 1;

      -- round() before cast avoids truncating fractional cents on non-integer
      -- quantities (e.g. qty=1.5 * price=99 = 148.5 → 149, not 148).
      v_resource_total_cents := case
        when v_resource_record.default_cost_unit_cents is not null
          then round(v_resource_record.qty_default * v_resource_record.default_cost_unit_cents)::bigint
        else null
      end;

      insert into public.estimate_resource_lines (
        estimate_work_id,
        resource_type,
        title,
        quantity,
        unit,
        unit_price_cents,
        total_price_cents,
        markup_bps,
        discount_bps_override
      )
      values (
        v_new_work_id,
        v_resource_record.resource_type,
        v_resource_record.title,
        v_resource_record.qty_default,
        v_resource_record.unit_display,
        v_resource_record.default_cost_unit_cents,
        v_resource_total_cents,
        v_resource_record.default_markup_bps,
        v_resource_record.default_discount_bps
      )
      returning id into v_new_resource_id;

      v_new_resource_line_ids := v_new_resource_line_ids || v_new_resource_id;

      if v_resource_total_cents is not null then
        v_total_planned_cost := v_total_planned_cost + v_resource_total_cents;
      end if;
    end loop;

    -- Skip the no-op recompute when this work copied zero resource lines:
    -- the INSERT above already set planned_cost_cents = 0, and the UPDATE
    -- would write the same value via coalesce(sum(...), 0).
    if v_work_resource_count > 0 then
      update public.estimate_works
         set planned_cost_cents = (
           select coalesce(sum(total_price_cents), 0)::bigint
           from public.estimate_resource_lines
           where estimate_work_id = v_new_work_id
         )
       where id = v_new_work_id;
    end if;
  end loop;

  return jsonb_build_object(
    'project_stage_id', v_new_stage_id,
    'work_ids', to_jsonb(v_new_work_ids),
    'resource_line_ids', to_jsonb(v_new_resource_line_ids),
    'total_planned_cost_cents', v_total_planned_cost
  );
end;
$$;
