-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260602150100_instance_tables_library_fks.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 3.4 — Nullable FK columns linking instance tables to the library.
--
-- template_resource_lines.system_resource_article_id already exists from
-- Session 3.1 (20260512132310_estimate_templates_schema.sql); this migration
-- adds the missing FKs on the four other instance tables plus the matching
-- live-estimate resource line FK, with their partial indexes.
--
-- All FKs are nullable (an instance row need not be backed by a library
-- article — a free-form stage/work/resource is valid) and use ON DELETE SET
-- NULL so archiving/removing a library article never orphans or drops an
-- instance row; it simply loses the back-reference.
--
-- Every statement is idempotent (`add column if not exists` /
-- `create index if not exists`) so re-application is a no-op. `add column if
-- not exists` with an inline `references ... on delete set null` is the same
-- construct family already used by curated-mirror source files
-- (e.g. 20260502120000_estimate_planned_dates_and_lag.sql for the idempotent
-- add, 20260417120000_estimate_resource_line_assignee_profile.sql for the
-- inline set-null FK), so this migration is includable in DEFAULT_SOURCE_FILES.

-- Template layer
alter table public.template_stages
  add column if not exists system_stage_article_id uuid
    references public.system_stage_articles(id) on delete set null;

create index if not exists idx_template_stages_canonical
  on public.template_stages(system_stage_article_id)
  where system_stage_article_id is not null;

alter table public.template_works
  add column if not exists system_work_article_id uuid
    references public.system_work_articles(id) on delete set null;

create index if not exists idx_template_works_canonical
  on public.template_works(system_work_article_id)
  where system_work_article_id is not null;

-- Live estimate layer
alter table public.project_stages
  add column if not exists system_stage_article_id uuid
    references public.system_stage_articles(id) on delete set null;

create index if not exists idx_project_stages_canonical
  on public.project_stages(system_stage_article_id)
  where system_stage_article_id is not null;

alter table public.estimate_works
  add column if not exists system_work_article_id uuid
    references public.system_work_articles(id) on delete set null;

create index if not exists idx_estimate_works_canonical
  on public.estimate_works(system_work_article_id)
  where system_work_article_id is not null;

alter table public.estimate_resource_lines
  add column if not exists system_resource_article_id uuid
    references public.system_resource_articles(id) on delete set null;

create index if not exists idx_estimate_resource_lines_canonical
  on public.estimate_resource_lines(system_resource_article_id)
  where system_resource_article_id is not null;
