-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260325130000_remove_co_owner_project_members_policy_branch.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Fallback recursion fix:
-- Even after switching to project_role_for_profile(...), runtime still reports:
--   infinite recursion detected in policy for relation "project_members"
-- This migration removes co_owner role-derivation branches from project_members RLS policies
-- to guarantee non-recursive evaluation for profile/current-user reads.

drop policy if exists project_members_select on public.project_members;

create policy project_members_select on public.project_members
for select
to authenticated
using (
  profile_id = auth.uid()
  or exists (
    select 1
    from public.projects p
    where p.id = project_id
      and p.owner_profile_id = auth.uid()
  )
);

drop policy if exists project_members_update on public.project_members;

create policy project_members_update on public.project_members
for update
to authenticated
using (
  exists (
    select 1
    from public.projects p
    where p.id = project_id
      and p.owner_profile_id = auth.uid()
  )
  and profile_id <> (
    select p.owner_profile_id
    from public.projects p
    where p.id = project_id
  )
)
with check (
  exists (
    select 1
    from public.projects p
    where p.id = project_id
      and p.owner_profile_id = auth.uid()
  )
  and profile_id <> (
    select p.owner_profile_id
    from public.projects p
    where p.id = project_id
  )
);

drop policy if exists project_members_delete on public.project_members;

create policy project_members_delete on public.project_members
for delete
to authenticated
using (
  exists (
    select 1
    from public.projects p
    where p.id = project_id
      and p.owner_profile_id = auth.uid()
  )
  and profile_id <> (
    select p.owner_profile_id
    from public.projects p
    where p.id = project_id
  )
);

