-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260324140000_project_launch_authority.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Launch permissions: bounded visibility columns, delegation invariants, co_owner member management RLS.

alter table public.project_members
  add column finance_visibility text not null default 'none'
    check (finance_visibility in ('none', 'summary', 'detail')),
  add column internal_docs_visibility text not null default 'none'
    check (internal_docs_visibility in ('none', 'view', 'edit'));

alter table public.project_invites
  add column finance_visibility text not null default 'none'
    check (finance_visibility in ('none', 'summary', 'detail')),
  add column internal_docs_visibility text not null default 'none'
    check (internal_docs_visibility in ('none', 'view', 'edit'));

-- Existing rows receive the additive default ('none').
-- Role-aligned defaults are enforced for new/updated rows via owner-membership
-- synchronization, invite/member delegation checks, and invite acceptance flow below.

-- ---------------------------------------------------------------------------
-- Rank helpers (higher = more privilege).
-- ---------------------------------------------------------------------------

create or replace function public.ai_access_rank(p_access text)
returns integer
language sql
immutable
as $$
  select case p_access
    when 'none' then 0
    when 'consult_only' then 1
    when 'project_pool' then 2
    else -1
  end
$$;

create or replace function public.finance_visibility_rank(p_level text)
returns integer
language sql
immutable
as $$
  select case p_level
    when 'none' then 0
    when 'summary' then 1
    when 'detail' then 2
    else -1
  end
$$;

create or replace function public.internal_docs_visibility_rank(p_level text)
returns integer
language sql
immutable
as $$
  select case p_level
    when 'none' then 0
    when 'view' then 1
    when 'edit' then 2
    else -1
  end
$$;

-- Role for any profile on a project (owner from projects row wins).
create or replace function public.project_role_for_profile(p_project_id uuid, p_profile_id uuid)
returns text
language sql
stable
security definer
set search_path = public
as $$
  select case
    when exists (
      select 1
      from public.projects p
      where p.id = p_project_id
        and p.owner_profile_id = p_profile_id
    ) then 'owner'
    else (
      select pm.role
      from public.project_members pm
      where pm.project_id = p_project_id
        and pm.profile_id = p_profile_id
      limit 1
    )
  end
$$;

-- Maximum capability ranks an actor may delegate (from their stored member row or owner defaults).
create or replace function public.actor_ai_access_delegate_cap(p_project_id uuid, p_actor uuid)
returns integer
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_role text;
  v_ai text;
begin
  v_role := public.project_role_for_profile(p_project_id, p_actor);
  if v_role is null then
    return -1;
  end if;
  if v_role = 'owner' then
    return public.ai_access_rank('project_pool');
  end if;
  select pm.ai_access
  into v_ai
  from public.project_members pm
  where pm.project_id = p_project_id
    and pm.profile_id = p_actor;
  return coalesce(public.ai_access_rank(v_ai), -1);
end;
$$;

create or replace function public.actor_finance_visibility_delegate_cap(p_project_id uuid, p_actor uuid)
returns integer
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_role text;
  v_fin text;
begin
  v_role := public.project_role_for_profile(p_project_id, p_actor);
  if v_role is null then
    return -1;
  end if;
  if v_role = 'owner' then
    return public.finance_visibility_rank('detail');
  end if;
  select pm.finance_visibility
  into v_fin
  from public.project_members pm
  where pm.project_id = p_project_id
    and pm.profile_id = p_actor;
  return coalesce(public.finance_visibility_rank(v_fin), -1);
end;
$$;

create or replace function public.actor_internal_docs_delegate_cap(p_project_id uuid, p_actor uuid)
returns integer
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_role text;
  v_doc text;
begin
  v_role := public.project_role_for_profile(p_project_id, p_actor);
  if v_role is null then
    return -1;
  end if;
  if v_role = 'owner' then
    return public.internal_docs_visibility_rank('edit');
  end if;
  select pm.internal_docs_visibility
  into v_doc
  from public.project_members pm
  where pm.project_id = p_project_id
    and pm.profile_id = p_actor;
  return coalesce(public.internal_docs_visibility_rank(v_doc), -1);
end;
$$;

-- Central delegation check: actor must be owner or co_owner; role and caps must not exceed actor's.
create or replace function public.assert_project_participant_delegate_ok(
  p_actor uuid,
  p_project_id uuid,
  p_role text,
  p_ai_access text,
  p_finance_visibility text,
  p_internal_docs_visibility text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_role text;
  v_ai_cap int;
  v_fin_cap int;
  v_doc_cap int;
begin
  if p_actor is null then
    raise exception 'Delegation check requires an actor';
  end if;

  v_actor_role := public.project_role_for_profile(p_project_id, p_actor);
  if v_actor_role is null then
    raise exception 'Actor is not a participant on this project';
  end if;

  if v_actor_role in ('viewer', 'contractor') then
    raise exception 'Insufficient authority to assign participants';
  end if;

  if p_role = 'owner' then
    raise exception 'Owner role cannot be assigned through invites or member grants';
  end if;

  if p_role = 'co_owner' and v_actor_role <> 'owner' then
    raise exception 'Only the project owner may create or promote co_owners';
  end if;

  if v_actor_role = 'co_owner' and p_role not in ('contractor', 'viewer') then
    raise exception 'Co-owners may only invite or assign contractor or viewer roles';
  end if;

  v_ai_cap := public.actor_ai_access_delegate_cap(p_project_id, p_actor);
  v_fin_cap := public.actor_finance_visibility_delegate_cap(p_project_id, p_actor);
  v_doc_cap := public.actor_internal_docs_delegate_cap(p_project_id, p_actor);

  if public.ai_access_rank(p_ai_access) > v_ai_cap then
    raise exception 'Cannot grant AI access above the actor''s own level';
  end if;

  if public.finance_visibility_rank(p_finance_visibility) > v_fin_cap then
    raise exception 'Cannot grant finance visibility above the actor''s own level';
  end if;

  if public.internal_docs_visibility_rank(p_internal_docs_visibility) > v_doc_cap then
    raise exception 'Cannot grant internal document access above the actor''s own level';
  end if;
end;
$$;

-- Effective values for the current user (stored row; owner without row uses max preset).
create or replace function public.effective_finance_visibility(p_project_id uuid)
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_fin text;
  v_role text;
begin
  if v_uid is null then
    return null;
  end if;
  v_role := public.project_role_for_profile(p_project_id, v_uid);
  if v_role is null then
    return null;
  end if;
  select pm.finance_visibility
  into v_fin
  from public.project_members pm
  where pm.project_id = p_project_id
    and pm.profile_id = v_uid;
  if v_fin is not null then
    return v_fin;
  end if;
  if v_role = 'owner' then
    return 'detail';
  end if;
  return 'none';
end;
$$;

create or replace function public.effective_internal_docs_visibility(p_project_id uuid)
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_doc text;
  v_role text;
begin
  if v_uid is null then
    return null;
  end if;
  v_role := public.project_role_for_profile(p_project_id, v_uid);
  if v_role is null then
    return null;
  end if;
  select pm.internal_docs_visibility
  into v_doc
  from public.project_members pm
  where pm.project_id = p_project_id
    and pm.profile_id = v_uid;
  if v_doc is not null then
    return v_doc;
  end if;
  if v_role = 'owner' then
    return 'edit';
  end if;
  return 'none';
end;
$$;

create or replace function public.effective_ai_access_for_profile(p_project_id uuid)
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_ai text;
  v_role text;
begin
  if v_uid is null then
    return null;
  end if;
  v_role := public.project_role_for_profile(p_project_id, v_uid);
  if v_role is null then
    return null;
  end if;
  select pm.ai_access
  into v_ai
  from public.project_members pm
  where pm.project_id = p_project_id
    and pm.profile_id = v_uid;
  if v_ai is not null then
    return v_ai;
  end if;
  if v_role = 'owner' then
    return 'project_pool';
  end if;
  return 'none';
end;
$$;

-- ---------------------------------------------------------------------------
-- Triggers: invites and member rows.
-- ---------------------------------------------------------------------------

create or replace function public.enforce_project_invite_delegation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    return new;
  end if;

  perform public.assert_project_participant_delegate_ok(
    auth.uid(),
    new.project_id,
    new.role,
    new.ai_access,
    new.finance_visibility,
    new.internal_docs_visibility
  );

  return new;
end;
$$;

create trigger enforce_project_invite_delegation
before insert or update on public.project_invites
for each row execute function public.enforce_project_invite_delegation();

create or replace function public.enforce_project_member_delegation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid;
  v_owner uuid;
  v_setting text;
begin
  select p.owner_profile_id
  into v_owner
  from public.projects p
  where p.id = new.project_id;

  -- Canonical owner membership row: enforced elsewhere; skip delegation.
  if new.role = 'owner'
     and v_owner is not null
     and new.profile_id = v_owner then
    return new;
  end if;

  -- Ownership transfer: demote former owner member row to co_owner.
  if tg_op = 'UPDATE'
     and old.role = 'owner'
     and new.role = 'co_owner'
     and old.profile_id is distinct from v_owner then
    return new;
  end if;

  v_setting := current_setting('app.member_delegate_actor', true);

  if v_setting is not null and length(trim(v_setting)) > 0 then
    v_actor := v_setting::uuid;
  else
    v_actor := auth.uid();
  end if;

  if v_actor is null then
    raise exception 'Member delegation check could not resolve actor';
  end if;

  if tg_op = 'UPDATE' then
    if old.role is not distinct from new.role
       and old.ai_access is not distinct from new.ai_access
       and old.finance_visibility is not distinct from new.finance_visibility
       and old.internal_docs_visibility is not distinct from new.internal_docs_visibility
       and old.viewer_regime is not distinct from new.viewer_regime
       and old.credit_limit is not distinct from new.credit_limit then
      return new;
    end if;
  end if;

  perform public.assert_project_participant_delegate_ok(
    v_actor,
    new.project_id,
    new.role,
    new.ai_access,
    new.finance_visibility,
    new.internal_docs_visibility
  );

  return new;
end;
$$;

create trigger enforce_project_member_delegation
before insert or update on public.project_members
for each row execute function public.enforce_project_member_delegation();

-- Owner membership sync: set visibility columns on promote/demote.
create or replace function public.handle_project_owner_membership()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.project_members
  set role = 'co_owner',
      finance_visibility = 'summary',
      internal_docs_visibility = 'view'
  where project_id = new.id
    and role = 'owner'
    and profile_id <> new.owner_profile_id;

  insert into public.project_members (
    project_id,
    profile_id,
    role,
    ai_access,
    viewer_regime,
    credit_limit,
    used_credits,
    finance_visibility,
    internal_docs_visibility
  )
  values (
    new.id,
    new.owner_profile_id,
    'owner',
    'project_pool',
    null,
    0,
    0,
    'detail',
    'edit'
  )
  on conflict (project_id, profile_id) do update
    set role = 'owner',
        ai_access = case
          when public.project_members.ai_access = 'none' then 'project_pool'
          else public.project_members.ai_access
        end,
        viewer_regime = null,
        finance_visibility = 'detail',
        internal_docs_visibility = 'edit';

  return new;
end;
$$;

create or replace function public.accept_project_invite(p_invite_token text)
returns public.project_invites
language plpgsql
security definer
set search_path = public
as $$
declare
  v_invite public.project_invites%rowtype;
  v_profile_email text;
  v_owner_profile_id uuid;
  v_already_accepted_by_current_user boolean := false;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_invite
  from public.project_invites
  where invite_token = p_invite_token
  for update;

  if not found then
    raise exception 'Invite not found';
  end if;

  if v_invite.status = 'accepted' and v_invite.accepted_profile_id = auth.uid() then
    v_already_accepted_by_current_user := true;
  elsif v_invite.status <> 'pending' then
    raise exception 'Invite is no longer pending';
  end if;

  select p.email
  into v_profile_email
  from public.profiles p
  where p.id = auth.uid();

  if not found then
    raise exception 'Profile not found';
  end if;

  if not v_already_accepted_by_current_user
     and (v_profile_email is null or lower(v_profile_email) <> lower(v_invite.email)) then
    raise exception 'Invite email does not match the current account';
  end if;

  select p.owner_profile_id
  into v_owner_profile_id
  from public.projects p
  where p.id = v_invite.project_id;

  if not found then
    raise exception 'Project not found';
  end if;

  if v_invite.role = 'owner'
     and v_owner_profile_id is distinct from auth.uid() then
    raise exception 'Owner invites are not supported without a project ownership transfer';
  end if;

  perform public.assert_project_participant_delegate_ok(
    v_invite.invited_by,
    v_invite.project_id,
    v_invite.role,
    v_invite.ai_access,
    v_invite.finance_visibility,
    v_invite.internal_docs_visibility
  );

  perform set_config('app.member_delegate_actor', v_invite.invited_by::text, true);

  begin
    insert into public.project_members (
      project_id,
      profile_id,
      role,
      ai_access,
      viewer_regime,
      credit_limit,
      used_credits,
      finance_visibility,
      internal_docs_visibility
    )
    values (
      v_invite.project_id,
      auth.uid(),
      v_invite.role,
      v_invite.ai_access,
      v_invite.viewer_regime,
      v_invite.credit_limit,
      0,
      v_invite.finance_visibility,
      v_invite.internal_docs_visibility
    )
    on conflict (project_id, profile_id) do update
      set role = excluded.role,
          ai_access = excluded.ai_access,
          viewer_regime = excluded.viewer_regime,
          credit_limit = excluded.credit_limit,
          finance_visibility = excluded.finance_visibility,
          internal_docs_visibility = excluded.internal_docs_visibility;
  exception
    when others then
      perform set_config('app.member_delegate_actor', '', true);
      raise;
  end;

  perform set_config('app.member_delegate_actor', '', true);

  if v_already_accepted_by_current_user then
    return v_invite;
  end if;

  update public.project_invites
  set status = 'accepted',
      accepted_profile_id = auth.uid(),
      accepted_at = coalesce(accepted_at, now())
  where id = v_invite.id
  returning * into v_invite;

  return v_invite;
end;
$$;

-- ---------------------------------------------------------------------------
-- RLS: project_members (co_owner roster + manage contractor/viewer).
-- ---------------------------------------------------------------------------

drop policy if exists project_members_select on public.project_members;
drop policy if exists project_members_insert on public.project_members;
drop policy if exists project_members_update on public.project_members;
drop policy if exists project_members_delete on public.project_members;

create policy project_members_select on public.project_members
for select
to authenticated
using (
  profile_id = auth.uid()
  or exists (
    select 1
    from public.projects p
    where p.id = project_id
      and p.owner_profile_id = auth.uid()
  )
  or public.has_project_role(project_id, array['co_owner'])
);

create policy project_members_insert on public.project_members
for insert
to authenticated
with check (
  exists (
    select 1
    from public.projects p
    where p.id = project_id
      and p.owner_profile_id = auth.uid()
  )
  and (
    role <> 'owner'
    or profile_id = (
      select p.owner_profile_id
      from public.projects p
      where p.id = project_id
    )
  )
);

create policy project_members_update on public.project_members
for update
to authenticated
using (
  (
    exists (
      select 1
      from public.projects p
      where p.id = project_id
        and p.owner_profile_id = auth.uid()
    )
    and profile_id <> (
      select p.owner_profile_id
      from public.projects p
      where p.id = project_id
    )
  )
  or (
    public.has_project_role(project_id, array['co_owner'])
    and role in ('contractor', 'viewer')
    and profile_id <> (
      select p.owner_profile_id
      from public.projects p
      where p.id = project_id
    )
  )
)
with check (
  (
    exists (
      select 1
      from public.projects p
      where p.id = project_id
        and p.owner_profile_id = auth.uid()
    )
    and profile_id <> (
      select p.owner_profile_id
      from public.projects p
      where p.id = project_id
    )
  )
  or (
    public.has_project_role(project_id, array['co_owner'])
    and role in ('contractor', 'viewer')
    and profile_id <> (
      select p.owner_profile_id
      from public.projects p
      where p.id = project_id
    )
  )
);

create policy project_members_delete on public.project_members
for delete
to authenticated
using (
  (
    exists (
      select 1
      from public.projects p
      where p.id = project_id
        and p.owner_profile_id = auth.uid()
    )
    and profile_id <> (
      select p.owner_profile_id
      from public.projects p
      where p.id = project_id
    )
  )
  or (
    public.has_project_role(project_id, array['co_owner'])
    and role in ('contractor', 'viewer')
    and profile_id <> (
      select p.owner_profile_id
      from public.projects p
      where p.id = project_id
    )
  )
);

-- ---------------------------------------------------------------------------
-- Grants (mirror existing helper pattern).
-- ---------------------------------------------------------------------------

revoke all on function public.ai_access_rank(text) from public;
revoke all on function public.finance_visibility_rank(text) from public;
revoke all on function public.internal_docs_visibility_rank(text) from public;
revoke all on function public.project_role_for_profile(uuid, uuid) from public;
revoke all on function public.actor_ai_access_delegate_cap(uuid, uuid) from public;
revoke all on function public.actor_finance_visibility_delegate_cap(uuid, uuid) from public;
revoke all on function public.actor_internal_docs_delegate_cap(uuid, uuid) from public;
revoke all on function public.assert_project_participant_delegate_ok(uuid, uuid, text, text, text, text) from public;
revoke all on function public.effective_finance_visibility(uuid) from public;
revoke all on function public.effective_internal_docs_visibility(uuid) from public;
revoke all on function public.effective_ai_access_for_profile(uuid) from public;
revoke all on function public.enforce_project_invite_delegation() from public;
revoke all on function public.enforce_project_member_delegation() from public;

grant execute on function public.ai_access_rank(text) to authenticated;
grant execute on function public.finance_visibility_rank(text) to authenticated;
grant execute on function public.internal_docs_visibility_rank(text) to authenticated;
grant execute on function public.effective_finance_visibility(uuid) to authenticated;
grant execute on function public.effective_internal_docs_visibility(uuid) to authenticated;
grant execute on function public.effective_ai_access_for_profile(uuid) to authenticated;
