-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260416100000_wave9_closeout_hardening.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Wave 9: closeout / hardening (no new capabilities).
-- A) Procurement AI RPC: SQL-level effective_ai_access_for_profile parity with other AI RPCs.
-- B) Session continuity: atomic first-write via INSERT ... ON CONFLICT (chat_id).
-- C) Planning: index to support per-task recent comment lookups in get_tasks_ai_operational_evidence.

-- ---------------------------------------------------------------------------
-- A) Procurement AI evidence: defense-in-depth gates (auth.uid, project, AI tier).
-- ---------------------------------------------------------------------------

create or replace function public.get_procurement_ai_operational_evidence(
  p_project_id uuid,
  p_limit integer default 40,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 40), 1), 80);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_ai text;
  v_finance text;
  v_ordered_lines jsonb := '[]'::jsonb;
  v_procurement_items jsonb := '[]'::jsonb;
begin
  if v_uid is null then
    return jsonb_build_object(
      'effective_finance_visibility', null,
      'ordered_lines', '[]'::jsonb,
      'procurement_items', '[]'::jsonb
    );
  end if;

  if not public.can_access_project(p_project_id) then
    return jsonb_build_object(
      'effective_finance_visibility', null,
      'ordered_lines', '[]'::jsonb,
      'procurement_items', '[]'::jsonb
    );
  end if;

  v_ai := public.effective_ai_access_for_profile(p_project_id);
  if v_ai is null or v_ai = 'none' then
    return jsonb_build_object(
      'effective_finance_visibility', null,
      'ordered_lines', '[]'::jsonb,
      'procurement_items', '[]'::jsonb
    );
  end if;

  v_finance := coalesce(public.effective_finance_visibility(p_project_id), 'none');

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'order_line_id', rows.order_line_id,
        'order_id', rows.order_id,
        'order_status', rows.order_status,
        'ordered_at', rows.ordered_at,
        'delivery_due_at', rows.delivery_due_at,
        'procurement_item_id', rows.procurement_item_id,
        'procurement_item_title', rows.procurement_item_title,
        'estimate_resource_line_id', rows.estimate_resource_line_id,
        'estimate_resource_line_resource_type', rows.estimate_resource_line_resource_type,
        'title', rows.title,
        'quantity', rows.quantity,
        'unit', rows.unit,
        'created_at', rows.created_at
      )
      order by rows.sort_order_ts desc, rows.created_at desc, rows.order_line_id
    ),
    '[]'::jsonb
  )
  into v_ordered_lines
  from (
    select
      ol.id as order_line_id,
      o.id as order_id,
      o.status as order_status,
      o.ordered_at,
      o.delivery_due_at,
      ol.procurement_item_id,
      pi.title as procurement_item_title,
      pi.estimate_resource_line_id,
      erl.resource_type as estimate_resource_line_resource_type,
      ol.title,
      ol.quantity,
      ol.unit,
      ol.created_at,
      coalesce(o.ordered_at, o.created_at) as sort_order_ts
    from public.order_lines ol
    join public.orders o
      on o.id = ol.order_id
    left join public.procurement_items pi
      on pi.id = ol.procurement_item_id
    left join public.estimate_resource_lines erl
      on erl.id = pi.estimate_resource_line_id
    where o.project_id = p_project_id
    order by coalesce(o.ordered_at, o.created_at) desc, ol.created_at desc, ol.id
    offset v_offset
    limit v_limit
  ) rows;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'procurement_item_id', rows.procurement_item_id,
        'estimate_resource_line_id', rows.estimate_resource_line_id,
        'estimate_resource_line_resource_type', rows.estimate_resource_line_resource_type,
        'task_id', rows.task_id,
        'title', rows.title,
        'category', rows.category,
        'quantity', rows.quantity,
        'unit', rows.unit,
        'status', rows.status,
        'created_at', rows.created_at,
        'updated_at', rows.updated_at
      )
      order by rows.updated_at desc, rows.procurement_item_id
    ),
    '[]'::jsonb
  )
  into v_procurement_items
  from (
    select
      pi.id as procurement_item_id,
      pi.estimate_resource_line_id,
      erl.resource_type as estimate_resource_line_resource_type,
      pi.task_id,
      pi.title,
      pi.category,
      pi.quantity,
      pi.unit,
      pi.status,
      pi.created_at,
      pi.updated_at
    from public.procurement_items pi
    left join public.estimate_resource_lines erl
      on erl.id = pi.estimate_resource_line_id
    where pi.project_id = p_project_id
      and pi.status <> 'cancelled'
    order by pi.updated_at desc, pi.id
    offset v_offset
    limit v_limit
  ) rows;

  return jsonb_build_object(
    'effective_finance_visibility', v_finance,
    'ordered_lines', v_ordered_lines,
    'procurement_items', v_procurement_items
  );
end;
$$;

revoke all on function public.get_procurement_ai_operational_evidence(uuid, integer, integer) from public;
grant execute on function public.get_procurement_ai_operational_evidence(uuid, integer, integer) to authenticated;

-- ---------------------------------------------------------------------------
-- B) Session continuity append: atomic upsert (concurrent first-writes).
-- ---------------------------------------------------------------------------

create or replace function public.append_ai_chat_session_turns(
  p_project_id uuid,
  p_chat_id uuid,
  p_user_text text,
  p_assistant_text text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_ai text;
  v_max_msg_len integer := 2000;
  v_max_turns integer := 10;
  v_user text;
  v_asst text;
  v_append jsonb;
  v_trimmed jsonb;
begin
  if v_uid is null then
    return;
  end if;

  if not public.can_access_project(p_project_id) then
    return;
  end if;

  v_ai := public.effective_ai_access_for_profile(p_project_id);
  if v_ai is null or v_ai = 'none' then
    return;
  end if;

  v_user := left(coalesce(p_user_text, ''), v_max_msg_len);
  v_asst := left(coalesce(p_assistant_text, ''), v_max_msg_len);
  v_append := jsonb_build_array(
    jsonb_build_object('role', 'user', 'text', v_user),
    jsonb_build_object('role', 'assistant', 'text', v_asst)
  );
  v_trimmed := public._trim_session_turns_jsonb(v_append, v_max_turns);

  insert into public.project_ai_chat_sessions (
    chat_id,
    project_id,
    profile_id,
    recent_turns,
    rolling_summary,
    updated_at
  )
  values (
    p_chat_id,
    p_project_id,
    v_uid,
    v_trimmed,
    null,
    now()
  )
  on conflict (chat_id) do update set
    recent_turns = public._trim_session_turns_jsonb(
      coalesce(project_ai_chat_sessions.recent_turns, '[]'::jsonb) || v_append,
      v_max_turns
    ),
    updated_at = now()
  where project_ai_chat_sessions.project_id = excluded.project_id
    and project_ai_chat_sessions.profile_id = excluded.profile_id;
end;
$$;

revoke all on function public.append_ai_chat_session_turns(uuid, uuid, text, text) from public;
grant execute on function public.append_ai_chat_session_turns(uuid, uuid, text, text) to authenticated;

-- ---------------------------------------------------------------------------
-- C) Task comments: index for lateral "order by created_at desc limit 3" per task_id.
-- ---------------------------------------------------------------------------

create index idx_task_comments_task_id_created_at_desc
  on public.task_comments (task_id, created_at desc);
