-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260512132340_template_rpcs.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 3.1 — RPCs for template browsing and stage-apply.
--
-- Three functions:
--
--   list_estimate_templates(p_scope_filter)       — top-level listing for
--     the template-picker UI. Returns one row per template the caller can
--     read (RLS via can_read_template). Sort: system → org → profile,
--     then alphabetic by title.
--
--   get_estimate_template_detail(p_template_id)   — full nested tree
--     (template → stages → works → resource_lines) as jsonb. Returns NULL
--     when the template does not exist OR the caller cannot read it,
--     keeping the "not found vs forbidden" distinction opaque.
--
--   apply_template_stage_to_estimate(...)         — copies one
--     template_stage's subtree onto a real ProjectEstimate version.
--     Creates a new project_stage and the corresponding estimate_works +
--     estimate_resource_lines. Returns the new IDs and the rolled-up
--     planned cost. Frontend is responsible for downstream syncs
--     (project_tasks, etc.) — this RPC only writes the estimate tree.
--
-- Authorization:
--   * read RPCs gate on can_read_template (and the existing project
--     visibility chain for the apply RPC's destination)
--   * apply RPC additionally requires can_write_project_content on the
--     destination project
--   * All three are security definer + explicit grants to authenticated.

create or replace function public.list_estimate_templates(p_scope_filter text default null)
returns table (
  id uuid,
  owner_kind text,
  owner_label text,
  title text,
  description text,
  scope text,
  published_to_public boolean,
  cover_image_url text,
  stage_count integer,
  is_manageable boolean,
  updated_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    et.id,
    et.owner_kind,
    case
      when et.owner_kind = 'system' then 'rovno.ai'
      when et.owner_kind = 'org' then coalesce(
        (select o.name from public.organizations o where o.id = et.owner_id),
        'org'
      )
      when et.owner_kind = 'profile' then 'My templates'
      else 'unknown'
    end as owner_label,
    et.title,
    et.description,
    et.scope,
    et.published_to_public,
    et.cover_image_url,
    (
      select count(*)::int
      from public.template_stages ts
      where ts.estimate_template_id = et.id
    ) as stage_count,
    public.can_manage_template(et.owner_kind, et.owner_id) as is_manageable,
    et.updated_at
  from public.estimate_templates et
  where public.can_read_template(et.owner_kind, et.owner_id)
    and (p_scope_filter is null or et.scope = p_scope_filter)
  order by
    case et.owner_kind
      when 'system' then 1
      when 'org' then 2
      when 'profile' then 3
      else 4
    end,
    et.title;
$$;

create or replace function public.get_estimate_template_detail(p_template_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_owner_kind text;
  v_owner_id uuid;
begin
  select owner_kind, owner_id
    into v_owner_kind, v_owner_id
  from public.estimate_templates
  where id = p_template_id;

  if v_owner_kind is null then
    return null;
  end if;
  if not public.can_read_template(v_owner_kind, v_owner_id) then
    return null;
  end if;

  return jsonb_build_object(
    'template', (
      select to_jsonb(et)
      from public.estimate_templates et
      where et.id = p_template_id
    ),
    'stages', (
      select coalesce(jsonb_agg(stage_obj order by sort_hint, title), '[]'::jsonb)
      from (
        select
          ts.sort_hint,
          ts.title,
          jsonb_build_object(
            'id', ts.id,
            'title', ts.title,
            'description', ts.description,
            'scope_tag', ts.scope_tag,
            'sort_hint', ts.sort_hint,
            'parameter_definitions', ts.parameter_definitions,
            'work_count', (
              select count(*)::int
              from public.template_works tw
              where tw.template_stage_id = ts.id
            ),
            'resource_count', (
              select count(*)::int
              from public.template_resource_lines trl
              join public.template_works tw2 on tw2.id = trl.template_work_id
              where tw2.template_stage_id = ts.id
            ),
            'works', (
              select coalesce(jsonb_agg(work_obj order by sort_hint, title), '[]'::jsonb)
              from (
                select
                  tw.sort_hint,
                  tw.title,
                  jsonb_build_object(
                    'id', tw.id,
                    'title', tw.title,
                    'description', tw.description,
                    'sort_hint', tw.sort_hint,
                    'parameter_definitions', tw.parameter_definitions,
                    'resource_lines', (
                      select coalesce(jsonb_agg(line_obj order by sort_hint, title), '[]'::jsonb)
                      from (
                        select
                          trl.sort_hint,
                          trl.title,
                          jsonb_build_object(
                            'id', trl.id,
                            'title', trl.title,
                            'resource_type', trl.resource_type,
                            'unit_display', trl.unit_display,
                            'qty_default', trl.qty_default,
                            'default_cost_unit_cents', trl.default_cost_unit_cents,
                            'default_markup_bps', trl.default_markup_bps,
                            'default_discount_bps', trl.default_discount_bps,
                            'system_resource_article_id', trl.system_resource_article_id,
                            'sort_hint', trl.sort_hint
                          ) as line_obj
                        from public.template_resource_lines trl
                        where trl.template_work_id = tw.id
                      ) lines
                    )
                  ) as work_obj
                from public.template_works tw
                where tw.template_stage_id = ts.id
              ) works
            )
          ) as stage_obj
        from public.template_stages ts
        where ts.estimate_template_id = p_template_id
      ) stages
    )
  );
end;
$$;

create or replace function public.apply_template_stage_to_estimate(
  p_estimate_version_id uuid,
  p_template_stage_id uuid,
  p_sort_position integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_project_id uuid;
  v_template_id uuid;
  v_owner_kind text;
  v_owner_id uuid;
  v_stage_record record;
  v_new_stage_id uuid;
  v_new_work_ids uuid[] := '{}';
  v_new_resource_line_ids uuid[] := '{}';
  v_max_existing_sort int;
  v_target_sort int;
  v_work_record record;
  v_new_work_id uuid;
  v_resource_record record;
  v_new_resource_id uuid;
  v_resource_total_cents bigint;
  v_total_planned_cost bigint := 0;
begin
  -- Resolve and authorize the destination project.
  select pe.project_id
    into v_project_id
  from public.estimate_versions ev
  join public.project_estimates pe on pe.id = ev.estimate_id
  where ev.id = p_estimate_version_id;

  if v_project_id is null then
    raise exception 'Estimate version % not found', p_estimate_version_id
      using errcode = 'P0002';
  end if;
  if not public.can_write_project_content(v_project_id) then
    raise exception 'Forbidden: cannot write project content'
      using errcode = '42501';
  end if;

  -- Resolve and authorize the source template stage.
  select ts.estimate_template_id, et.owner_kind, et.owner_id
    into v_template_id, v_owner_kind, v_owner_id
  from public.template_stages ts
  join public.estimate_templates et on et.id = ts.estimate_template_id
  where ts.id = p_template_stage_id;

  if v_template_id is null then
    raise exception 'Template stage % not found', p_template_stage_id
      using errcode = 'P0002';
  end if;
  if not public.can_read_template(v_owner_kind, v_owner_id) then
    raise exception 'Forbidden: cannot read source template'
      using errcode = '42501';
  end if;

  select * into v_stage_record
  from public.template_stages
  where id = p_template_stage_id;

  -- Choose a sort_order that does not collide with existing project_stages
  -- (table has a unique (project_id, sort_order) constraint).
  select coalesce(max(sort_order), 0)
    into v_max_existing_sort
  from public.project_stages
  where project_id = v_project_id;

  v_target_sort := coalesce(p_sort_position, v_max_existing_sort + 1);

  insert into public.project_stages (project_id, title, description, sort_order, status)
  values (
    v_project_id,
    v_stage_record.title,
    v_stage_record.description,
    v_target_sort,
    'open'
  )
  returning id into v_new_stage_id;

  -- Copy works and their resource lines, preserving sort_hint as sort_order.
  for v_work_record in
    select *
    from public.template_works
    where template_stage_id = p_template_stage_id
    order by sort_hint, title
  loop
    insert into public.estimate_works (
      estimate_version_id,
      project_stage_id,
      title,
      description,
      sort_order,
      planned_cost_cents
    )
    values (
      p_estimate_version_id,
      v_new_stage_id,
      v_work_record.title,
      v_work_record.description,
      v_work_record.sort_hint,
      0
    )
    returning id into v_new_work_id;

    v_new_work_ids := v_new_work_ids || v_new_work_id;

    for v_resource_record in
      select *
      from public.template_resource_lines
      where template_work_id = v_work_record.id
      order by sort_hint, title
    loop
      v_resource_total_cents := case
        when v_resource_record.default_cost_unit_cents is not null
          then (v_resource_record.qty_default * v_resource_record.default_cost_unit_cents)::bigint
        else null
      end;

      insert into public.estimate_resource_lines (
        estimate_work_id,
        resource_type,
        title,
        quantity,
        unit,
        unit_price_cents,
        total_price_cents,
        markup_bps,
        discount_bps_override
      )
      values (
        v_new_work_id,
        v_resource_record.resource_type,
        v_resource_record.title,
        v_resource_record.qty_default,
        v_resource_record.unit_display,
        v_resource_record.default_cost_unit_cents,
        v_resource_total_cents,
        v_resource_record.default_markup_bps,
        v_resource_record.default_discount_bps
      )
      returning id into v_new_resource_id;

      v_new_resource_line_ids := v_new_resource_line_ids || v_new_resource_id;

      if v_resource_total_cents is not null then
        v_total_planned_cost := v_total_planned_cost + v_resource_total_cents;
      end if;
    end loop;

    update public.estimate_works
       set planned_cost_cents = (
         select coalesce(sum(total_price_cents), 0)::bigint
         from public.estimate_resource_lines
         where estimate_work_id = v_new_work_id
       )
     where id = v_new_work_id;
  end loop;

  return jsonb_build_object(
    'project_stage_id', v_new_stage_id,
    'work_ids', to_jsonb(v_new_work_ids),
    'resource_line_ids', to_jsonb(v_new_resource_line_ids),
    'total_planned_cost_cents', v_total_planned_cost
  );
end;
$$;

revoke all on function public.list_estimate_templates(text) from public;
revoke all on function public.get_estimate_template_detail(uuid) from public;
revoke all on function public.apply_template_stage_to_estimate(uuid, uuid, integer) from public;

grant execute on function public.list_estimate_templates(text) to authenticated;
grant execute on function public.get_estimate_template_detail(uuid) to authenticated;
grant execute on function public.apply_template_stage_to_estimate(uuid, uuid, integer) to authenticated;
