-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260306163500_procurement_orders_and_inventory_movements.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create table public.procurement_items (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  estimate_resource_line_id uuid references public.estimate_resource_lines(id) on delete set null,
  task_id uuid references public.tasks(id) on delete set null,
  title text not null,
  description text,
  category text,
  quantity numeric(14,3) not null check (quantity >= 0),
  unit text,
  planned_unit_price_cents bigint check (planned_unit_price_cents is null or planned_unit_price_cents >= 0),
  planned_total_price_cents bigint check (planned_total_price_cents is null or planned_total_price_cents >= 0),
  status text not null default 'requested' check (
    status in ('requested', 'ordered', 'partially_received', 'received', 'cancelled')
  ),
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_procurement_items_project_id on public.procurement_items(project_id);
create index idx_procurement_items_estimate_resource_line_id on public.procurement_items(estimate_resource_line_id);
create index idx_procurement_items_task_id on public.procurement_items(task_id);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  supplier_name text not null,
  supplier_contact text,
  status text not null default 'draft' check (
    status in ('draft', 'placed', 'partially_received', 'received', 'cancelled')
  ),
  ordered_at timestamptz,
  delivery_due_at timestamptz,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_orders_project_id on public.orders(project_id);

create table public.order_lines (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  procurement_item_id uuid references public.procurement_items(id) on delete set null,
  title text not null,
  quantity numeric(14,3) not null check (quantity >= 0),
  unit text,
  unit_price_cents bigint check (unit_price_cents is null or unit_price_cents >= 0),
  total_price_cents bigint check (total_price_cents is null or total_price_cents >= 0),
  created_at timestamptz not null default now()
);

create index idx_order_lines_order_id on public.order_lines(order_id);
create index idx_order_lines_procurement_item_id on public.order_lines(procurement_item_id);

create table public.inventory_movements (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  inventory_item_id uuid not null references public.inventory_items(id) on delete cascade,
  inventory_location_id uuid references public.inventory_locations(id) on delete set null,
  order_line_id uuid references public.order_lines(id) on delete set null,
  procurement_item_id uuid references public.procurement_items(id) on delete set null,
  movement_type text not null check (movement_type in ('receipt', 'issue', 'transfer', 'adjustment')),
  delta_qty numeric(14,3) not null,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index idx_inventory_movements_project_id on public.inventory_movements(project_id);
create index idx_inventory_movements_inventory_item_id on public.inventory_movements(inventory_item_id);
create index idx_inventory_movements_inventory_location_id on public.inventory_movements(inventory_location_id);
create index idx_inventory_movements_order_line_id on public.inventory_movements(order_line_id);
create index idx_inventory_movements_procurement_item_id on public.inventory_movements(procurement_item_id);

create table public.task_checklist_items (
  id uuid primary key default gen_random_uuid(),
  task_id uuid not null references public.tasks(id) on delete cascade,
  title text not null,
  is_done boolean not null default false,
  procurement_item_id uuid references public.procurement_items(id) on delete set null,
  estimate_resource_line_id uuid references public.estimate_resource_lines(id) on delete set null,
  estimate_work_id uuid references public.estimate_works(id) on delete set null,
  sort_order integer not null check (sort_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (task_id, sort_order)
);

create index idx_task_checklist_items_task_id on public.task_checklist_items(task_id);
create index idx_task_checklist_items_procurement_item_id on public.task_checklist_items(procurement_item_id);
create index idx_task_checklist_items_estimate_resource_line_id on public.task_checklist_items(estimate_resource_line_id);
create index idx_task_checklist_items_estimate_work_id on public.task_checklist_items(estimate_work_id);

create trigger set_procurement_items_updated_at
before update on public.procurement_items
for each row execute function public.set_updated_at();

create trigger set_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

create trigger on_inventory_movements_sync_balances
after insert or update or delete on public.inventory_movements
for each row execute function public.sync_inventory_balances();

create trigger set_task_checklist_items_updated_at
before update on public.task_checklist_items
for each row execute function public.set_updated_at();
