-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260403103000_phase6_operational_summary_read_rpcs.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Phase 6: summary-safe operational read models.
-- Scope:
-- - add narrow RPCs for procurement/estimate summary users
-- - do not widen base-table RLS policies on money-bearing tables
-- - return explicit non-monetary payloads only

create or replace function public.get_procurement_operational_summary(
  p_project_id uuid,
  p_limit integer default 200,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 200), 1), 500);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_allowed boolean;
  v_ordered_lines jsonb := '[]'::jsonb;
  v_procurement_items jsonb := '[]'::jsonb;
begin
  v_allowed := public.can_access_project(p_project_id)
    and public.effective_finance_visibility(p_project_id) in ('summary', 'detail');

  if not v_allowed then
    return jsonb_build_object(
      'ordered_lines', '[]'::jsonb,
      'procurement_items', '[]'::jsonb
    );
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'order_line_id', rows.order_line_id,
        'order_id', rows.order_id,
        'order_status', rows.order_status,
        'ordered_at', rows.ordered_at,
        'delivery_due_at', rows.delivery_due_at,
        'procurement_item_id', rows.procurement_item_id,
        'procurement_item_title', rows.procurement_item_title,
        'title', rows.title,
        'quantity', rows.quantity,
        'unit', rows.unit,
        'created_at', rows.created_at
      )
      order by rows.sort_order_ts desc, rows.created_at desc, rows.order_line_id
    ),
    '[]'::jsonb
  )
  into v_ordered_lines
  from (
    select
      ol.id as order_line_id,
      o.id as order_id,
      o.status as order_status,
      o.ordered_at,
      o.delivery_due_at,
      ol.procurement_item_id,
      pi.title as procurement_item_title,
      ol.title,
      ol.quantity,
      ol.unit,
      ol.created_at,
      coalesce(o.ordered_at, o.created_at) as sort_order_ts
    from public.order_lines ol
    join public.orders o
      on o.id = ol.order_id
    left join public.procurement_items pi
      on pi.id = ol.procurement_item_id
    where o.project_id = p_project_id
    order by coalesce(o.ordered_at, o.created_at) desc, ol.created_at desc, ol.id
    offset v_offset
    limit v_limit
  ) rows;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'procurement_item_id', rows.procurement_item_id,
        'estimate_resource_line_id', rows.estimate_resource_line_id,
        'task_id', rows.task_id,
        'title', rows.title,
        'description', rows.description,
        'category', rows.category,
        'quantity', rows.quantity,
        'unit', rows.unit,
        'status', rows.status,
        'created_at', rows.created_at,
        'updated_at', rows.updated_at
      )
      order by rows.updated_at desc, rows.procurement_item_id
    ),
    '[]'::jsonb
  )
  into v_procurement_items
  from (
    select
      pi.id as procurement_item_id,
      pi.estimate_resource_line_id,
      pi.task_id,
      pi.title,
      pi.description,
      pi.category,
      pi.quantity,
      pi.unit,
      pi.status,
      pi.created_at,
      pi.updated_at
    from public.procurement_items pi
    where pi.project_id = p_project_id
      and pi.status <> 'requested'
    order by pi.updated_at desc, pi.id
    offset v_offset
    limit v_limit
  ) rows;

  return jsonb_build_object(
    'ordered_lines', v_ordered_lines,
    'procurement_items', v_procurement_items
  );
end;
$$;

create or replace function public.get_estimate_operational_summary(
  p_project_id uuid,
  p_estimate_version_id uuid default null,
  p_limit integer default 500,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 500), 1), 1000);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_allowed boolean;
  v_works jsonb := '[]'::jsonb;
  v_resource_lines jsonb := '[]'::jsonb;
begin
  v_allowed := public.can_access_project(p_project_id)
    and public.effective_finance_visibility(p_project_id) in ('summary', 'detail');

  if not v_allowed then
    return jsonb_build_object(
      'works', '[]'::jsonb,
      'resource_lines', '[]'::jsonb
    );
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'estimate_work_id', rows.estimate_work_id,
        'estimate_version_id', rows.estimate_version_id,
        'project_stage_id', rows.project_stage_id,
        'title', rows.title,
        'description', rows.description,
        'sort_order', rows.sort_order,
        'created_at', rows.created_at
      )
      order by rows.sort_order asc, rows.estimate_work_id
    ),
    '[]'::jsonb
  )
  into v_works
  from (
    select
      ew.id as estimate_work_id,
      ew.estimate_version_id,
      ew.project_stage_id,
      ew.title,
      ew.description,
      ew.sort_order,
      ew.created_at
    from public.estimate_works ew
    join public.estimate_versions ev
      on ev.id = ew.estimate_version_id
    join public.project_estimates pe
      on pe.id = ev.estimate_id
    where pe.project_id = p_project_id
      and (p_estimate_version_id is null or ew.estimate_version_id = p_estimate_version_id)
    order by ew.sort_order asc, ew.id
    offset v_offset
    limit v_limit
  ) rows;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'estimate_resource_line_id', rows.estimate_resource_line_id,
        'estimate_work_id', rows.estimate_work_id,
        'estimate_work_title', rows.estimate_work_title,
        'estimate_version_id', rows.estimate_version_id,
        'resource_type', rows.resource_type,
        'title', rows.title,
        'quantity', rows.quantity,
        'unit', rows.unit,
        'created_at', rows.created_at
      )
      order by rows.estimate_work_sort_order asc, rows.estimate_resource_line_id
    ),
    '[]'::jsonb
  )
  into v_resource_lines
  from (
    select
      erl.id as estimate_resource_line_id,
      erl.estimate_work_id,
      ew.title as estimate_work_title,
      ew.estimate_version_id,
      ew.sort_order as estimate_work_sort_order,
      erl.resource_type,
      erl.title,
      erl.quantity,
      erl.unit,
      erl.created_at
    from public.estimate_resource_lines erl
    join public.estimate_works ew
      on ew.id = erl.estimate_work_id
    join public.estimate_versions ev
      on ev.id = ew.estimate_version_id
    join public.project_estimates pe
      on pe.id = ev.estimate_id
    where pe.project_id = p_project_id
      and (p_estimate_version_id is null or ew.estimate_version_id = p_estimate_version_id)
    order by ew.sort_order asc, erl.id
    offset v_offset
    limit v_limit
  ) rows;

  return jsonb_build_object(
    'works', v_works,
    'resource_lines', v_resource_lines
  );
end;
$$;

revoke all on function public.get_procurement_operational_summary(uuid, integer, integer) from public;
revoke all on function public.get_estimate_operational_summary(uuid, uuid, integer, integer) from public;

grant execute on function public.get_procurement_operational_summary(uuid, integer, integer) to authenticated;
grant execute on function public.get_estimate_operational_summary(uuid, uuid, integer, integer) to authenticated;
