-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260706120000_blog_schema.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Built-in blog (rovno.ai/blog) — content-marketing / SEO surface.
--
-- Goal: raise citability and search visibility (classic SEO + GPT-search).
-- Articles are authored in the web admin (TipTap editor), stored as TipTap
-- JSON (source of truth for editing) plus pre-rendered sanitized HTML
-- (content_html) that the public pages and the build-time prerenderer emit
-- verbatim. The frontend prerender step (rovno/scripts/prerender-blog.mjs)
-- reads published rows anonymously at build time to emit static
-- dist/blog/<slug>/index.html + sitemap.xml + RSS, so ANONYMOUS SELECT of
-- published rows is a hard requirement of the design, not an oversight.
--
-- Authorship model: a global editorial allowlist (blog_authors), NOT a
-- per-project role — the blog is a site-wide marketing surface with no
-- project context. There is deliberately no self-service signup path:
-- rows in blog_authors are managed manually (Studio/SQL; see the seed
-- migration 20260706120200). Any registered author can edit any post
-- (single trusted editorial team, mirrors how small company blogs work);
-- INSERT is still pinned to the caller's own author row so attribution
-- can't be forged at creation time.
--
-- No SECURITY DEFINER helper is needed: blog_authors is publicly readable
-- (author bios render on public articles), so RLS policies on blog_posts
-- subquery it directly under the calling role.
--
-- Draft privacy: drafts are visible only to authors (the authenticated
-- SELECT policy ORs in the author check); anon sees status = 'published'
-- only. `status` is a two-state text check — scheduled publishing is a
-- deliberate non-goal for v1.
--
-- Reserved slugs: the SPA mounts the admin under /blog/admin and the
-- prerenderer emits /blog/feed.xml — the CHECK keeps content slugs from
-- colliding with those surfaces.

-- 1) Editorial allowlist ------------------------------------------------------

create table public.blog_authors (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  display_name text not null,
  bio text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_blog_authors_updated_at
before update on public.blog_authors
for each row execute function public.set_updated_at();

alter table public.blog_authors enable row level security;

-- Public read: author name/bio/avatar render on public article pages (anon
-- included). No INSERT/UPDATE/DELETE policies — writes are service_role /
-- manual SQL only (editorial allowlist is admin-managed by design).
create policy blog_authors_select_public
on public.blog_authors for select to anon, authenticated
using (true);

-- 2) Posts --------------------------------------------------------------------
--
-- Constraint notes (kept out of the table body — the backend-truth parser
-- does not strip comments inside create table):
--   blog_posts_slug_format — URL-safe slug: lowercase latin + digits,
--     single-hyphen separated, 3..120 chars.
--   blog_posts_slug_reserved — keeps content slugs off the admin/feed
--     surfaces of /blog/*.
--   blog_posts_published_has_timestamp — a published post must carry its
--     publication timestamp (sitemap/RSS/JSON-LD key on it); drafts may keep
--     the timestamp from a previous publish so unpublish/republish preserves
--     the original date.

create table public.blog_posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references public.blog_authors(id) on delete restrict,
  slug text not null unique,
  title text not null,
  subtitle text,
  excerpt text,
  content jsonb not null default '{}'::jsonb,
  content_html text not null default '',
  cover_image_url text,
  seo_title text,
  seo_description text,
  tags text[] not null default '{}',
  locale text not null default 'ru' check (locale in ('ru', 'en')),
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_at timestamptz,
  reading_time_minutes integer check (reading_time_minutes is null or reading_time_minutes > 0),
  word_count integer check (word_count is null or word_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint blog_posts_slug_format
    check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(slug) between 3 and 120),
  constraint blog_posts_slug_reserved
    check (slug not in ('admin', 'new', 'edit', 'feed', 'rss', 'sitemap', 'tag', 'tags', 'preview')),
  constraint blog_posts_published_has_timestamp
    check (status <> 'published' or published_at is not null)
);

-- Public listing reads are "published ordered by recency" — one composite
-- index serves both the WHERE and the ORDER BY.
create index idx_blog_posts_status_published_at
  on public.blog_posts (status, published_at desc);

create index idx_blog_posts_author_id on public.blog_posts (author_id);

create trigger set_blog_posts_updated_at
before update on public.blog_posts
for each row execute function public.set_updated_at();

alter table public.blog_posts enable row level security;

-- Anon: published only (public site + build-time prerenderer).
create policy blog_posts_select_published_anon
on public.blog_posts for select to anon
using (status = 'published');

-- Authenticated: published for everyone; drafts for editorial authors.
create policy blog_posts_select_authenticated
on public.blog_posts for select to authenticated
using (
  status = 'published'
  or exists (
    select 1 from public.blog_authors ba
    where ba.profile_id = auth.uid()
  )
);

-- INSERT: only authors, and only as themselves (attribution can't be forged).
create policy blog_posts_insert_authors
on public.blog_posts for insert to authenticated
with check (
  author_id in (
    select ba.id from public.blog_authors ba
    where ba.profile_id = auth.uid()
  )
);

-- UPDATE/DELETE: any registered author, any post (shared editorial team).
-- WITH CHECK keeps author_id pointing at a real author row but allows
-- editorial reassignment between authors.
create policy blog_posts_update_authors
on public.blog_posts for update to authenticated
using (
  exists (
    select 1 from public.blog_authors ba
    where ba.profile_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.blog_authors ba
    where ba.profile_id = auth.uid()
  )
);

create policy blog_posts_delete_authors
on public.blog_posts for delete to authenticated
using (
  exists (
    select 1 from public.blog_authors ba
    where ba.profile_id = auth.uid()
  )
);

-- 3) Grants -------------------------------------------------------------------
--
-- First anon-granted tables in the project — deliberate: the public blog and
-- the build-time prerenderer read published rows without a session (the anon
-- SELECT policies above are the row filter). Writes stay authenticated-only;
-- blog_authors has no write grants at all (service_role bypasses grants+RLS).

grant select on table public.blog_authors to anon;
grant select on table public.blog_authors to authenticated;
grant select on table public.blog_posts to anon;
grant select on table public.blog_posts to authenticated;
grant insert, update, delete on table public.blog_posts to authenticated;
