-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260602075944_can_access_storage_object_workspace_org.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Extend can_access_storage_object() to cover workspace (personal) and org
-- documents, bringing it into parity with the storage.objects SELECT policies
-- that already gate signed-URL access for those scopes.
--
-- Why: public.storage_objects is gated by this SECURITY DEFINER function. It
-- previously authorized only project documents (document_versions -> documents)
-- and project_media. Workspace uploads (workspace_document_versions) and org
-- uploads (org_document_versions) were omitted, so an owner/member could not
-- SELECT the storage_objects row for their own file. The client joins this
-- table to obtain bucket/object_path/mime_type; the omission left those null
-- client-side, so no signed URL was ever created -> no inline preview,
-- open-in-new-tab, or download for ANY personal or org uploaded document.
--
-- Parity note: the project branch filters dv.is_current = true; the workspace
-- and org branches intentionally do NOT, matching the corresponding
-- storage.objects SELECT policies (storage_objects_select_workspace_documents_*
-- and storage_objects_select_org_documents_*), which key off ownership /
-- org membership without an is_current filter. Keeping the app-table gate and
-- the storage-schema policies in lockstep prevents one layer granting while the
-- other denies.

create or replace function public.can_access_storage_object(p_storage_object_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    exists (
      select 1
      from public.document_versions dv
      join public.documents d
        on d.id = dv.document_id
      where dv.storage_object_id = p_storage_object_id
        and dv.is_current = true
        and public.can_access_project(d.project_id)
        and (
          d.visibility_class = 'shared_project'
          or public.can_view_internal_documents(d.project_id)
        )
    )
  or exists (
      select 1
      from public.project_media pm
      where pm.storage_object_id = p_storage_object_id
        and public.can_access_project(pm.project_id)
        and (
          pm.visibility_class = 'shared_project'
          or public.can_view_internal_documents(pm.project_id)
        )
    )
  or exists (
      -- Workspace (personal) documents: readable by their owner.
      select 1
      from public.workspace_document_versions wdv
      join public.workspace_documents wd
        on wd.id = wdv.workspace_document_id
      where wdv.storage_object_id = p_storage_object_id
        and wd.owner_profile_id = auth.uid()
    )
  or exists (
      -- Org documents: readable by members of the owning org.
      select 1
      from public.org_document_versions odv
      join public.org_documents od
        on od.id = odv.org_document_id
      where odv.storage_object_id = p_storage_object_id
        and public.is_org_member(od.org_id)
    );
$$;

-- CREATE OR REPLACE preserves privileges, but re-assert them explicitly to keep
-- the grant surface obvious and self-documenting in migration history.
revoke all on function public.can_access_storage_object(uuid) from public;
grant execute on function public.can_access_storage_object(uuid) to authenticated;
