-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260613120100_search_canonical_library.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 4 — search_canonical_library: autocomplete suggestions for the
-- estimate editor's stage / work / resource name inputs.
--
--   search_canonical_library(p_query, p_kind)
--     p_kind ∈ {'stage','work','resource'}
--     Returns a jsonb array (max 20) of suggestions ordered by relevance.
--
-- Suggestion shape (uniform across kinds; nulls where not applicable):
--   { id, kind, name, badge_type, source, is_personal,
--     template_id, work_stage_name, subcategory, unit, rovno_sku }
--
--   * id          — the system_*_article id (canonical library row). Used to
--                   link an estimate row to the library + open detail.
--   * kind        — 'stage' | 'work' | 'resource' | 'subcategory'.
--   * badge_type  — 'stage' | 'work' | 'subcategory' | <resource_type> (the
--                   leaf's default_resource_type) — drives the dropdown icon.
--   * template_id — the rovno.ai canonical template_stage_id / template_work_id
--                   that corresponds to this article (NULL for resources). The
--                   frontend "Применить" button passes this to
--                   apply_template_stage_to_estimate / add_library_work_to_estimate
--                   to pull the full subtree (incl. default resource lines). The
--                   30 stage + 692 work articles map 1:1 onto the singleton
--                   system template, so this is reliably non-null for stages/works.
--   * is_personal — always false in wave-1 (no org/profile catalogs yet).
--
-- Wave-1 scope: resource suggestions are restricted to the curated set
-- (is_residential_curated = true) — the ~1.8K curated leaves + ~2K subcategory
-- rows (all curated) — NOT the ~83K raw fgis_ksr catalog, which would drown the
-- dropdown. Subcategory rows (kind='subcategory') are surfaced above leaf
-- articles per the locked sort order: exact > subcategory > leaf. supplier_offers
-- are out of scope (table does not exist yet).
--
-- LIKE safety: the user term is matched with ILIKE substring patterns. To keep a
-- literally-typed % or _ from acting as a wildcard, the term is escaped (escape
-- char '\') for the ILIKE patterns; the exact-match and similarity() ranking use
-- the raw term. This is parameterized (no SQL injection) — escaping is purely to
-- make wildcard chars match literally.
--
-- Authorization: the canonical library is global read for any signed-in user, so
-- this is security definer with a plain grant to authenticated (no per-row gate).

create or replace function public.search_canonical_library(
  p_query text,
  p_kind text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_term text := nullif(btrim(coalesce(p_query, '')), '');
  v_like_term text;
  v_sys_template_id uuid;
  v_result jsonb;
begin
  -- Empty query or unknown kind → no suggestions (frontend hides the dropdown).
  if v_term is null or p_kind not in ('stage', 'work', 'resource') then
    return '[]'::jsonb;
  end if;

  -- Escape LIKE metacharacters so a literal % / _ / \ in the term matches itself.
  v_like_term := replace(replace(replace(v_term, '\', '\\'), '%', '\%'), '_', '\_');

  select id
    into v_sys_template_id
  from public.estimate_templates
  where owner_kind = 'system'
  limit 1;

  if p_kind = 'stage' then
    select coalesce(jsonb_agg(obj order by match_rank desc, sim desc, name), '[]'::jsonb)
      into v_result
    from (
      select
        jsonb_build_object(
          'id', sa.id,
          'kind', 'stage',
          'name', sa.name,
          'badge_type', 'stage',
          'source', sa.source,
          'is_personal', false,
          'template_id', (
            select ts.id
            from public.template_stages ts
            where ts.system_stage_article_id = sa.id
              and ts.estimate_template_id = v_sys_template_id
            limit 1
          ),
          'work_stage_name', null,
          'subcategory', null,
          'unit', null,
          'rovno_sku', null
        ) as obj,
        sa.name as name,
        case
          when lower(sa.name) = lower(v_term) then 4
          when sa.name ilike v_like_term || '%' escape '\' then 3
          when sa.name ilike '%' || v_like_term || '%' escape '\' then 2
          else 1
        end as match_rank,
        similarity(sa.name, v_term) as sim
      from public.system_stage_articles sa
      where sa.archived = false
        and (sa.name ilike '%' || v_like_term || '%' escape '\' or similarity(sa.name, v_term) > 0.2)
      order by match_rank desc, sim desc, sa.name
      limit 20
    ) ranked;

  elsif p_kind = 'work' then
    select coalesce(jsonb_agg(obj order by match_rank desc, sim desc, name), '[]'::jsonb)
      into v_result
    from (
      select
        jsonb_build_object(
          'id', wa.id,
          'kind', 'work',
          'name', wa.name,
          'badge_type', 'work',
          'source', wa.source,
          'is_personal', false,
          'template_id', (
            select tw.id
            from public.template_works tw
            join public.template_stages ts on ts.id = tw.template_stage_id
            where tw.system_work_article_id = wa.id
              and ts.estimate_template_id = v_sys_template_id
            limit 1
          ),
          'work_stage_name', parent.name,
          'subcategory', null,
          'unit', wa.default_unit,
          'rovno_sku', null
        ) as obj,
        wa.name as name,
        case
          when lower(wa.name) = lower(v_term) then 4
          when wa.name ilike v_like_term || '%' escape '\' then 3
          when wa.name ilike '%' || v_like_term || '%' escape '\' then 2
          else 1
        end as match_rank,
        similarity(wa.name, v_term) as sim
      from public.system_work_articles wa
      join public.system_stage_articles parent on parent.id = wa.parent_stage_article_id
      where wa.archived = false
        and (wa.name ilike '%' || v_like_term || '%' escape '\' or similarity(wa.name, v_term) > 0.2)
      order by match_rank desc, sim desc, wa.name
      limit 20
    ) ranked;

  else  -- p_kind = 'resource'
    select coalesce(jsonb_agg(obj order by match_rank desc, kind_rank desc, sim desc, name), '[]'::jsonb)
      into v_result
    from (
      select
        jsonb_build_object(
          'id', ra.id,
          'kind', case ra.kind when 'subcategory' then 'subcategory' else 'resource' end,
          'name', coalesce(ra.canonical_name, ra.name),
          'badge_type', case ra.kind when 'subcategory' then 'subcategory' else ra.default_resource_type end,
          'source', ra.source,
          'is_personal', false,
          'template_id', null,
          'work_stage_name', null,
          'subcategory', ra.subcategory,
          'unit', ra.unit_display,
          'rovno_sku', ra.rovno_sku
        ) as obj,
        coalesce(ra.canonical_name, ra.name) as name,
        case
          when lower(coalesce(ra.canonical_name, ra.name)) = lower(v_term) then 4
          when coalesce(ra.canonical_name, ra.name) ilike v_like_term || '%' escape '\' then 3
          when coalesce(ra.canonical_name, ra.name) ilike '%' || v_like_term || '%' escape '\' then 2
          else 1
        end as match_rank,
        -- Subcategories rank above leaf articles (exact > subcategory > leaf).
        case ra.kind when 'subcategory' then 1 else 0 end as kind_rank,
        greatest(
          similarity(ra.name, v_term),
          similarity(coalesce(ra.canonical_name, ''), v_term)
        ) as sim
      from public.system_resource_articles ra
      where ra.archived = false
        and ra.is_residential_curated = true
        and ra.kind in ('subcategory', 'leaf')
        and (
          ra.name ilike '%' || v_like_term || '%' escape '\'
          or coalesce(ra.canonical_name, '') ilike '%' || v_like_term || '%' escape '\'
          or similarity(ra.name, v_term) > 0.2
        )
      order by match_rank desc, kind_rank desc, sim desc, coalesce(ra.canonical_name, ra.name)
      limit 20
    ) ranked;
  end if;

  return coalesce(v_result, '[]'::jsonb);
end;
$$;

revoke all on function public.search_canonical_library(text, text) from public;
grant execute on function public.search_canonical_library(text, text) to authenticated;
