-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260630120000_cross_project_stock_transfer.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- True cross-project stock transfer (warehouse A -> warehouse B).
--
-- Until now inventory is strictly per-project. A same-project transfer
-- (rovno/src/data/orders-source.ts placeStockTransfer, shipped in #130) writes
-- one `orders` row plus two `inventory_movements` per line (-qty at the source
-- location, +qty at the destination), ALL stamped with the same project_id, and
-- the AFTER trigger on_inventory_movements_sync_balances keys each balance on the
-- movement's own project_id.
--
-- The trap this migration closes: nothing forces a movement's referenced
-- item/location to share the movement's project_id, and RLS only checks the
-- movement's own project_id. So a naive frontend "show project B's warehouse and
-- reuse placeStockTransfer" would write a +delta movement stamped project_id = A
-- but pointing at B's location; apply_inventory_balance_delta would then key the
-- balance on (A, item, B-location), and project B would never see the received
-- stock -- silent attribution corruption, no error.
--
-- The sanctioned path: place_cross_project_stock_transfer, a SECURITY DEFINER RPC
-- that re-checks can_use_project_stock on BOTH projects (definer bypasses RLS,
-- so the checks are manual, mirroring accept_project_invite /
-- create_org_with_contractor_profile) and writes a balanced pair of
-- SELF-CONSISTENT movements: the -delta fully under A (A item, A location, A
-- project) and the +delta fully under B (B item, B location, B project). The
-- existing AFTER trigger then upserts each balance under the correct project.
-- Because the whole RPC is one transaction, any failure (e.g. an over-draw caught
-- by inventory_balances.CHECK(quantity >= 0) or by apply_inventory_balance_delta's
-- own raise) rolls back both orders, both order lines, both movements and any
-- auto-created destination item -- no orphan cleanup, unlike the client path.
--
-- History: each project's history reader fetches its own orders by project_id and
-- cannot see the other project's rows (RLS + the per-project React Query fan-out).
-- So we record TWO linked `orders` rows, one per project, each owning its half's
-- movement(s), linked by self-describing columns (transfer_group_id +
-- counterparty_project_id/location_id + transfer_direction). The source ('out')
-- order renders "-> into <B>"; the destination ('in') order renders "<- from <A>",
-- each using ONLY its own row plus these columns.
--
-- Deliberate asymmetry: the source line/movement may reference A's
-- procurement_item_id (it lives in A -- legal, and is validated below to belong
-- to p_from_project), but the destination line/movement set procurement_item_id =
-- NULL. Referencing another project's procurement item from an order would leak
-- that item's metadata through the procurement summary/evidence RPCs, which join
-- order_lines to procurement_items by id only with no project re-check
-- (e.g. get_procurement_ai_operational_evidence). Do NOT "helpfully" copy or trust
-- an unvalidated procurement_item_id in a future refactor.
--
-- Item identity across projects: match/create the destination item by the shared
-- canonical identity (public.inventory_item_identity = normalized title|notes|unit,
-- see 20260630110000_inventory_canonical_identity.sql) -- the SAME key the frontend
-- receive/same-project-transfer paths use, so the two converge on one row instead of
-- forking into duplicates. Auto-create in B copying title/sku/unit/notes from the
-- source item when no match. (Unique enforcement of that identity is staged into a
-- later step with the frontend; until then a concurrent first-time create can still
-- duplicate -- the same low-severity race as the existing receive path.)
--
-- Hardening: enforce_inventory_movement_project_integrity converts the latent
-- raw-write hole above into a hard error -- every inventory_movements row must
-- reference an item (and, when set, a location) in its own project. Same-project
-- transfers, receipts, issues and adjustments already satisfy this, so it is
-- backward compatible; it only ever affects new INSERT/UPDATEs.

alter table public.orders
  add column if not exists transfer_group_id uuid,
  add column if not exists counterparty_project_id uuid references public.projects(id) on delete set null,
  add column if not exists counterparty_location_id uuid references public.inventory_locations(id) on delete set null,
  add column if not exists transfer_direction text check (transfer_direction in ('out', 'in'));

-- Index the linkage columns: counterparty_* are FKs with ON DELETE SET NULL (so a
-- project/location delete would otherwise seq-scan orders) and transfer_group_id is
-- the natural paired-order lookup key. Matches the repo's per-FK indexing convention.
create index idx_orders_transfer_group_id on public.orders(transfer_group_id);
create index idx_orders_counterparty_project_id on public.orders(counterparty_project_id);
create index idx_orders_counterparty_location_id on public.orders(counterparty_location_id);

-- ---------------------------------------------------------------------------
-- Movement project-integrity guard (BEFORE the existing AFTER balance-sync).
-- ---------------------------------------------------------------------------
create or replace function public.enforce_inventory_movement_project_integrity()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item_project uuid;
  v_loc_project uuid;
begin
  select project_id into v_item_project
  from public.inventory_items
  where id = new.inventory_item_id;

  if v_item_project is distinct from new.project_id then
    raise exception
      'inventory_movements project_id % does not match item % project %',
      new.project_id, new.inventory_item_id, v_item_project
      using errcode = '23514';
  end if;

  if new.inventory_location_id is not null then
    select project_id into v_loc_project
    from public.inventory_locations
    where id = new.inventory_location_id;

    if v_loc_project is distinct from new.project_id then
      raise exception
        'inventory_movements project_id % does not match location % project %',
        new.project_id, new.inventory_location_id, v_loc_project
        using errcode = '23514';
    end if;
  end if;

  return new;
end;
$$;

create trigger enforce_inventory_movement_project_integrity_biu
before insert or update on public.inventory_movements
for each row execute function public.enforce_inventory_movement_project_integrity();

-- ---------------------------------------------------------------------------
-- Cross-project stock-transfer permission gate (H2). You may use a project's
-- stock if you own or co-own it, OR have full financial-data access (sensitive
-- detail = effective_finance_visibility 'detail'). Stricter than
-- can_write_project_content on the role axis (a plain contractor is NOT enough)
-- and broader on the finance axis. Applied to BOTH the source and destination
-- project below. NOTE: this can grant the transfer to a finance-detail member who
-- is otherwise read-only under content RLS; that is the intended product rule.
-- ---------------------------------------------------------------------------
create or replace function public.can_use_project_stock(p_project_id uuid)
returns boolean
language sql
stable
as $$
  -- coalesce to false: can_view_sensitive_detail returns NULL for a non-member
  -- (effective_finance_visibility is NULL), and a NULL result would make the
  -- caller's `if not can_use_project_stock(...)` skip the THEN branch in plpgsql,
  -- silently bypassing the authz check. Always return a real boolean.
  select coalesce(
    public.has_project_role(p_project_id, array['owner', 'co_owner'])
      or public.can_view_sensitive_detail(p_project_id),
    false
  )
$$;

revoke all on function public.can_use_project_stock(uuid) from public;
grant execute on function public.can_use_project_stock(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- The cross-project transfer RPC.
-- ---------------------------------------------------------------------------
create or replace function public.place_cross_project_stock_transfer(
  p_from_project uuid,
  p_to_project uuid,
  p_from_location uuid,
  p_to_location uuid,
  p_lines jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_group_id uuid := gen_random_uuid();
  v_now timestamptz := now();
  v_from_order_id uuid;
  v_to_order_id uuid;
  v_line jsonb;
  v_from_item_id uuid;
  v_to_item_id uuid;
  v_src_proc_item uuid;
  v_title text;
  v_unit text;
  v_sku text;
  v_notes text;
  v_qty numeric(14,3);
  v_price_cents bigint;
  v_total_cents bigint;
  v_available numeric(14,3);
  v_from_line_id uuid;
  v_to_line_id uuid;
  v_line_count integer := 0;
begin
  -- 1. Authorization. Definer bypasses RLS, so check both projects explicitly.
  if v_user is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;
  if p_from_project is null or p_to_project is null
     or p_from_location is null or p_to_location is null then
    raise exception 'Source and destination project and location are required'
      using errcode = '22023';
  end if;
  if p_from_project = p_to_project then
    raise exception 'Use the same-project transfer for moves within one project'
      using errcode = '22023';
  end if;
  if not public.can_use_project_stock(p_from_project) then
    raise exception 'Not authorized to move stock out of the source project'
      using errcode = '42501';
  end if;
  if not public.can_use_project_stock(p_to_project) then
    raise exception 'Not authorized to receive stock into the destination project'
      using errcode = '42501';
  end if;

  -- 2. Locations must belong to their stated projects (defense in depth; the
  --    integrity trigger is the hard backstop on the movement rows).
  if not exists (
    select 1 from public.inventory_locations
    where id = p_from_location and project_id = p_from_project
  ) then
    raise exception 'Source location does not belong to the source project'
      using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.inventory_locations
    where id = p_to_location and project_id = p_to_project
  ) then
    raise exception 'Destination location does not belong to the destination project'
      using errcode = '22023';
  end if;

  if p_lines is null
     or jsonb_typeof(p_lines) <> 'array'
     or jsonb_array_length(p_lines) = 0 then
    raise exception 'No transfer lines provided' using errcode = '22023';
  end if;

  -- 3. Two linked order headers (status 'received', empty supplier, like the
  --    same-project transfer). Created up front; the whole call is atomic, so a
  --    later per-line failure rolls these back too.
  insert into public.orders (
    project_id, supplier_name, status, ordered_at, created_by,
    transfer_group_id, counterparty_project_id, counterparty_location_id, transfer_direction
  ) values (
    p_from_project, '', 'received', v_now, v_user,
    v_group_id, p_to_project, p_to_location, 'out'
  )
  returning id into v_from_order_id;

  insert into public.orders (
    project_id, supplier_name, status, ordered_at, created_by,
    transfer_group_id, counterparty_project_id, counterparty_location_id, transfer_direction
  ) values (
    p_to_project, '', 'received', v_now, v_user,
    v_group_id, p_from_project, p_from_location, 'in'
  )
  returning id into v_to_order_id;

  -- 4. Per line: resolve items, check availability, write lines + movements.
  for v_line in select value from jsonb_array_elements(p_lines)
  loop
    v_from_item_id := nullif(v_line ->> 'from_item_id', '')::uuid;
    v_src_proc_item := nullif(v_line ->> 'procurement_item_id', '')::uuid;
    v_title := trim(coalesce(v_line ->> 'title', ''));
    v_unit := trim(coalesce(v_line ->> 'unit', ''));
    v_sku := nullif(trim(coalesce(v_line ->> 'sku', '')), '');
    v_notes := nullif(trim(coalesce(v_line ->> 'spec', '')), '');
    v_qty := coalesce((v_line ->> 'qty')::numeric, 0);
    v_price_cents := nullif(v_line ->> 'actual_unit_price_cents', '')::numeric::bigint;

    if v_qty <= 0 then
      raise exception 'Quantity must be positive for "%"', coalesce(nullif(v_title, ''), 'item')
        using errcode = '22023';
    end if;

    -- Reject a procurement_item_id that is not in the source project. Untrusted,
    -- it would attach foreign-project item metadata to A's order line/movement and
    -- leak through summary/evidence RPCs that join order_lines to procurement_items
    -- by id only (see header).
    if v_src_proc_item is not null
       and not exists (
         select 1
         from public.procurement_items
         where id = v_src_proc_item
           and project_id = p_from_project
       ) then
      raise exception 'Procurement item % is not in the source project', v_src_proc_item
        using errcode = '22023';
    end if;

    -- 4a. Resolve the SOURCE item in A. Prefer the explicit id (the client has it
    --     from the stock row); fall back to normalized title+unit+sku match.
    --     Canonical title/unit/sku/notes come from the A row either way.
    if v_from_item_id is not null then
      select ii.title, ii.unit, ii.sku, ii.notes
      into v_title, v_unit, v_sku, v_notes
      from public.inventory_items ii
      where ii.id = v_from_item_id
        and ii.project_id = p_from_project;
      if not found then
        raise exception 'Source item % is not in the source project', v_from_item_id
          using errcode = '22023';
      end if;
    else
      if v_unit = '' then
        raise exception 'Unit is required for "%"', coalesce(nullif(v_title, ''), 'item')
          using errcode = '22023';
      end if;
      select ii.id, ii.title, ii.unit, ii.sku, ii.notes
      into v_from_item_id, v_title, v_unit, v_sku, v_notes
      from public.inventory_items ii
      where ii.project_id = p_from_project
        and ii.identity_key = public.inventory_item_identity(v_title, v_notes, v_unit)
      order by ii.created_at asc, ii.id asc
      limit 1;
      if not found then
        raise exception 'Item "%" (%) was not found in the source project',
          v_title, coalesce(v_sku, v_unit)
          using errcode = '22023';
      end if;
    end if;

    -- 4b. Availability at the source location (friendly error; the balance
    --     CHECK and apply_inventory_balance_delta are the concurrency backstop).
    select coalesce(sum(ib.quantity), 0)
    into v_available
    from public.inventory_balances ib
    where ib.project_id = p_from_project
      and ib.inventory_item_id = v_from_item_id
      and ib.inventory_location_id = p_from_location;

    if v_available < v_qty then
      raise exception 'Not enough stock to transfer "%": % available, % requested',
        v_title, v_available, v_qty
        using errcode = 'P0001';
    end if;

    -- 4c. Resolve-or-create the DESTINATION item in B by the shared canonical
    --     identity, copying the catalog fields from the source item.
    select ii.id
    into v_to_item_id
    from public.inventory_items ii
    where ii.project_id = p_to_project
      and ii.identity_key = public.inventory_item_identity(v_title, v_notes, v_unit)
    order by ii.created_at asc, ii.id asc
    limit 1;

    if not found then
      insert into public.inventory_items (project_id, title, sku, unit, notes)
      values (p_to_project, v_title, v_sku, v_unit, v_notes)
      returning id into v_to_item_id;
    end if;

    v_total_cents := case
      when v_price_cents is null then null
      else round(v_price_cents * v_qty)::bigint
    end;

    -- 4d. Order lines. Source line keeps A's procurement_item_id; destination
    --     line is a pure receipt (procurement_item_id = NULL) -- see header.
    insert into public.order_lines (
      order_id, procurement_item_id, title, quantity, unit, unit_price_cents, total_price_cents
    ) values (
      v_from_order_id, v_src_proc_item, v_title, v_qty, v_unit, v_price_cents, v_total_cents
    )
    returning id into v_from_line_id;

    insert into public.order_lines (
      order_id, procurement_item_id, title, quantity, unit, unit_price_cents, total_price_cents
    ) values (
      v_to_order_id, null, v_title, v_qty, v_unit, v_price_cents, v_total_cents
    )
    returning id into v_to_line_id;

    -- 4e. The two self-consistent movements. Each fires the AFTER balance-sync
    --     under its own project; each passes the integrity trigger.
    insert into public.inventory_movements (
      project_id, inventory_item_id, inventory_location_id,
      order_line_id, procurement_item_id, movement_type, delta_qty, created_by
    ) values (
      p_from_project, v_from_item_id, p_from_location,
      v_from_line_id, v_src_proc_item, 'transfer', -v_qty, v_user
    );

    insert into public.inventory_movements (
      project_id, inventory_item_id, inventory_location_id,
      order_line_id, procurement_item_id, movement_type, delta_qty, created_by
    ) values (
      p_to_project, v_to_item_id, p_to_location,
      v_to_line_id, null, 'transfer', v_qty, v_user
    );

    v_line_count := v_line_count + 1;
  end loop;

  return jsonb_build_object(
    'transfer_group_id', v_group_id,
    'from_order_id', v_from_order_id,
    'to_order_id', v_to_order_id,
    'from_project_id', p_from_project,
    'to_project_id', p_to_project,
    'line_count', v_line_count
  );
end;
$$;

revoke all on function public.place_cross_project_stock_transfer(uuid, uuid, uuid, uuid, jsonb) from public;
grant execute on function public.place_cross_project_stock_transfer(uuid, uuid, uuid, uuid, jsonb) to authenticated;
