-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260622120000_tighten_price_comparison_finance_gate.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 4 follow-up (audit finding C / codex P1): tighten
-- get_resource_article_price_comparison so the cross-project unit-price aggregate is
-- restricted to projects where the CALLER has 'detail' finance visibility.
--
-- The prior version (20260613120600) gated contributing rows on can_access_project()
-- (plain membership) only. That let a member with finance_visibility = 'summary' or 'none'
-- read other projects' median / average / min / max internal unit prices via the resource
-- modal's price-comparison block. A single accessible "other" project would even expose its
-- exact prices (project_count = 1 -> min = max = median = avg). estimate_resource_lines'
-- normal RLS gates unit_price_cents behind sensitive-detail visibility; this security-definer
-- RPC was bypassing that. We add `effective_finance_visibility(pe.project_id) = 'detail'` to
-- every contributing row so the aggregate only ever includes prices the caller is already
-- entitled to see.
--
-- Signature is unchanged (uuid, uuid) -> jsonb, so the backend-truth typed contract is
-- unaffected (the function is already curated via 20260613120600). Idempotent create-or-replace.

create or replace function public.get_resource_article_price_comparison(
  p_article_id uuid,
  p_exclude_project_id uuid default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  with accessible_lines as (
    select
      erl.unit_price_cents,
      pe.project_id
    from public.estimate_resource_lines erl
    join public.estimate_works ew on ew.id = erl.estimate_work_id
    join public.estimate_versions ev on ev.id = ew.estimate_version_id
    join public.project_estimates pe on pe.id = ev.estimate_id
    where erl.system_resource_article_id = p_article_id
      and erl.unit_price_cents is not null
      and ev.is_current = true
      and (p_exclude_project_id is null or pe.project_id <> p_exclude_project_id)
      and public.can_access_project(pe.project_id)
      -- Finance-detail gate: only aggregate unit prices from projects where the CALLER may see
      -- sensitive finance detail. Membership alone (can_access_project) must NOT expose other
      -- projects' internal unit prices to summary/none finance-visibility members.
      and public.effective_finance_visibility(pe.project_id) = 'detail'
  )
  select jsonb_build_object(
    'article_id', p_article_id,
    'sample_count', count(*),
    'project_count', count(distinct project_id),
    'median_cents', percentile_cont(0.5) within group (order by unit_price_cents)::bigint,
    'avg_cents', round(avg(unit_price_cents))::bigint,
    'min_cents', min(unit_price_cents),
    'max_cents', max(unit_price_cents)
  )
    into v_result
  from accessible_lines;

  return v_result;
end;
$$;

revoke all on function public.get_resource_article_price_comparison(uuid, uuid) from public;
grant execute on function public.get_resource_article_price_comparison(uuid, uuid) to authenticated;
