-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260630130000_cross_project_transfer_procurement_item_on_destination.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Fix: attach procurement_item_id to the DESTINATION (receiving) side of a cross-project transfer.
--
-- place_cross_project_stock_transfer moves stock p_from_project -> p_to_project. The
-- procurement_item_id in p_lines is the procurement NEED being fulfilled, which belongs to
-- the RECEIVING project (p_to_project), not the source. The original RPC put it on the
-- source order line / OUT movement and validated it against p_from_project, which rejected a
-- legitimate transfer: the procurement modal in project A pulls B's leftover stock to fulfill
-- A's need, so the frontend (correctly) passes A's procurement_item_id with p_from = B,
-- p_to = A. A's item is not in B, so the source-side check raised
-- "Procurement item ... is not in the source project" (22023).
--
-- Corrected asymmetry: the DESTINATION (p_to) order line + IN movement carry the
-- procurement_item_id, validated to belong to p_to_project, so the transfer links to and
-- fulfils the receiving project's need. The SOURCE (p_from) order line + OUT movement set it
-- to NULL (the source has no procurement need for this material, and referencing a
-- foreign-project procurement item there would leak its metadata through the summary/evidence
-- RPCs that join order_lines to procurement_items by id only). Only the RPC body changes;
-- everything else from 20260630120000 stays.

create or replace function public.place_cross_project_stock_transfer(
  p_from_project uuid,
  p_to_project uuid,
  p_from_location uuid,
  p_to_location uuid,
  p_lines jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_group_id uuid := gen_random_uuid();
  v_now timestamptz := now();
  v_from_order_id uuid;
  v_to_order_id uuid;
  v_line jsonb;
  v_from_item_id uuid;
  v_to_item_id uuid;
  v_proc_item uuid;
  v_title text;
  v_unit text;
  v_sku text;
  v_notes text;
  v_qty numeric(14,3);
  v_price_cents bigint;
  v_total_cents bigint;
  v_available numeric(14,3);
  v_from_line_id uuid;
  v_to_line_id uuid;
  v_line_count integer := 0;
begin
  -- 1. Authorization. Definer bypasses RLS, so check both projects explicitly.
  if v_user is null then
    raise exception 'Not authenticated' using errcode = '28000';
  end if;
  if p_from_project is null or p_to_project is null
     or p_from_location is null or p_to_location is null then
    raise exception 'Source and destination project and location are required'
      using errcode = '22023';
  end if;
  if p_from_project = p_to_project then
    raise exception 'Use the same-project transfer for moves within one project'
      using errcode = '22023';
  end if;
  if not public.can_use_project_stock(p_from_project) then
    raise exception 'Not authorized to move stock out of the source project'
      using errcode = '42501';
  end if;
  if not public.can_use_project_stock(p_to_project) then
    raise exception 'Not authorized to receive stock into the destination project'
      using errcode = '42501';
  end if;

  -- 2. Locations must belong to their stated projects.
  if not exists (
    select 1 from public.inventory_locations
    where id = p_from_location and project_id = p_from_project
  ) then
    raise exception 'Source location does not belong to the source project'
      using errcode = '22023';
  end if;
  if not exists (
    select 1 from public.inventory_locations
    where id = p_to_location and project_id = p_to_project
  ) then
    raise exception 'Destination location does not belong to the destination project'
      using errcode = '22023';
  end if;

  if p_lines is null
     or jsonb_typeof(p_lines) <> 'array'
     or jsonb_array_length(p_lines) = 0 then
    raise exception 'No transfer lines provided' using errcode = '22023';
  end if;

  -- 3. Two linked order headers (status 'received', empty supplier). Atomic: a later
  --    per-line failure rolls these back too.
  insert into public.orders (
    project_id, supplier_name, status, ordered_at, created_by,
    transfer_group_id, counterparty_project_id, counterparty_location_id, transfer_direction
  ) values (
    p_from_project, '', 'received', v_now, v_user,
    v_group_id, p_to_project, p_to_location, 'out'
  )
  returning id into v_from_order_id;

  insert into public.orders (
    project_id, supplier_name, status, ordered_at, created_by,
    transfer_group_id, counterparty_project_id, counterparty_location_id, transfer_direction
  ) values (
    p_to_project, '', 'received', v_now, v_user,
    v_group_id, p_from_project, p_from_location, 'in'
  )
  returning id into v_to_order_id;

  -- 4. Per line: resolve items, check availability, write lines + movements.
  for v_line in select value from jsonb_array_elements(p_lines)
  loop
    v_from_item_id := nullif(v_line ->> 'from_item_id', '')::uuid;
    v_proc_item := nullif(v_line ->> 'procurement_item_id', '')::uuid;
    v_title := trim(coalesce(v_line ->> 'title', ''));
    v_unit := trim(coalesce(v_line ->> 'unit', ''));
    v_sku := nullif(trim(coalesce(v_line ->> 'sku', '')), '');
    v_notes := nullif(trim(coalesce(v_line ->> 'spec', '')), '');
    v_qty := coalesce((v_line ->> 'qty')::numeric, 0);
    v_price_cents := nullif(v_line ->> 'actual_unit_price_cents', '')::numeric::bigint;

    if v_qty <= 0 then
      raise exception 'Quantity must be positive for "%"', coalesce(nullif(v_title, ''), 'item')
        using errcode = '22023';
    end if;

    -- The procurement_item_id is the fulfilled need; it belongs to the DESTINATION
    -- (receiving) project. Reject anything not in p_to_project: a foreign-project id would
    -- leak its metadata through the summary/evidence RPCs that join order_lines to
    -- procurement_items by id only.
    if v_proc_item is not null
       and not exists (
         select 1
         from public.procurement_items
         where id = v_proc_item
           and project_id = p_to_project
       ) then
      raise exception 'Procurement item % is not in the destination project', v_proc_item
        using errcode = '22023';
    end if;

    -- 4a. Resolve the SOURCE item in p_from_project (by explicit id, else by identity).
    if v_from_item_id is not null then
      select ii.title, ii.unit, ii.sku, ii.notes
      into v_title, v_unit, v_sku, v_notes
      from public.inventory_items ii
      where ii.id = v_from_item_id
        and ii.project_id = p_from_project;
      if not found then
        raise exception 'Source item % is not in the source project', v_from_item_id
          using errcode = '22023';
      end if;
    else
      if v_unit = '' then
        raise exception 'Unit is required for "%"', coalesce(nullif(v_title, ''), 'item')
          using errcode = '22023';
      end if;
      select ii.id, ii.title, ii.unit, ii.sku, ii.notes
      into v_from_item_id, v_title, v_unit, v_sku, v_notes
      from public.inventory_items ii
      where ii.project_id = p_from_project
        and ii.identity_key = public.inventory_item_identity(v_title, v_notes, v_unit)
      order by ii.created_at asc, ii.id asc
      limit 1;
      if not found then
        raise exception 'Item "%" (%) was not found in the source project',
          v_title, coalesce(v_sku, v_unit)
          using errcode = '22023';
      end if;
    end if;

    -- 4b. Availability at the source location.
    select coalesce(sum(ib.quantity), 0)
    into v_available
    from public.inventory_balances ib
    where ib.project_id = p_from_project
      and ib.inventory_item_id = v_from_item_id
      and ib.inventory_location_id = p_from_location;

    if v_available < v_qty then
      raise exception 'Not enough stock to transfer "%": % available, % requested',
        v_title, v_available, v_qty
        using errcode = 'P0001';
    end if;

    -- 4c. Resolve-or-create the DESTINATION item in p_to_project by canonical identity.
    select ii.id
    into v_to_item_id
    from public.inventory_items ii
    where ii.project_id = p_to_project
      and ii.identity_key = public.inventory_item_identity(v_title, v_notes, v_unit)
    order by ii.created_at asc, ii.id asc
    limit 1;

    if not found then
      insert into public.inventory_items (project_id, title, sku, unit, notes)
      values (p_to_project, v_title, v_sku, v_unit, v_notes)
      returning id into v_to_item_id;
    end if;

    v_total_cents := case
      when v_price_cents is null then null
      else round(v_price_cents * v_qty)::bigint
    end;

    -- 4d. Order lines. The DESTINATION (receiving) line carries procurement_item_id (the
    --     fulfilled need, in p_to_project); the SOURCE line is a pure issue (NULL).
    insert into public.order_lines (
      order_id, procurement_item_id, title, quantity, unit, unit_price_cents, total_price_cents
    ) values (
      v_from_order_id, null, v_title, v_qty, v_unit, v_price_cents, v_total_cents
    )
    returning id into v_from_line_id;

    insert into public.order_lines (
      order_id, procurement_item_id, title, quantity, unit, unit_price_cents, total_price_cents
    ) values (
      v_to_order_id, v_proc_item, v_title, v_qty, v_unit, v_price_cents, v_total_cents
    )
    returning id into v_to_line_id;

    -- 4e. The two self-consistent movements. The IN (destination) movement carries
    --     procurement_item_id so the transfer counts toward the receiving project's need.
    insert into public.inventory_movements (
      project_id, inventory_item_id, inventory_location_id,
      order_line_id, procurement_item_id, movement_type, delta_qty, created_by
    ) values (
      p_from_project, v_from_item_id, p_from_location,
      v_from_line_id, null, 'transfer', -v_qty, v_user
    );

    insert into public.inventory_movements (
      project_id, inventory_item_id, inventory_location_id,
      order_line_id, procurement_item_id, movement_type, delta_qty, created_by
    ) values (
      p_to_project, v_to_item_id, p_to_location,
      v_to_line_id, v_proc_item, 'transfer', v_qty, v_user
    );

    v_line_count := v_line_count + 1;
  end loop;

  return jsonb_build_object(
    'transfer_group_id', v_group_id,
    'from_order_id', v_from_order_id,
    'to_order_id', v_to_order_id,
    'from_project_id', p_from_project,
    'to_project_id', p_to_project,
    'line_count', v_line_count
  );
end;
$$;

revoke all on function public.place_cross_project_stock_transfer(uuid, uuid, uuid, uuid, jsonb) from public;
grant execute on function public.place_cross_project_stock_transfer(uuid, uuid, uuid, uuid, jsonb) to authenticated;
