-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260507120000_rebuild_org_insert_delete_policies.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 2 hotfix #5 — rebuild organizations INSERT/DELETE policies.
--
-- Reproduced on prod with a real authenticated JWT (sub matches profile,
-- current_profile_id() returns the user's id, identical JWT inserts into
-- projects past the projects_insert policy with the same
-- "owner_profile_id = auth.uid()" check). Yet INSERT into organizations
-- returns 42501 "new row violates row-level security policy" no matter
-- whether owner_profile_id is supplied or omitted.
--
-- The two policies have identical syntax in their respective creation
-- migrations, which means the live state on prod for organizations
-- diverged from the intended definition (likely the policy was never
-- materialized despite the migration applying — same migration also
-- created helper functions that ARE present, so partial-apply isn't
-- ruled out).
--
-- Fix: defensively drop-and-recreate organizations_insert and
-- organizations_delete to the canonical definition. Idempotent — if the
-- live policy already matches, the rebuild is a no-op semantically.
-- organizations_select and organizations_update were already rebuilt by
-- the 20260506150000 recursion fix, so they are not touched here.

drop policy if exists organizations_insert on public.organizations;
drop policy if exists organizations_delete on public.organizations;

create policy organizations_insert on public.organizations
for insert
to authenticated
with check (owner_profile_id = auth.uid());

create policy organizations_delete on public.organizations
for delete
to authenticated
using (owner_profile_id = auth.uid());
