-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260716205000_payment_intents_operation_identity_key.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create unique index uq_payment_intents_id_profile_id
  on public.payment_intents (id, profile_id);
