-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260502120000_estimate_planned_dates_and_lag.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Persist planned dates and dependency lag for the estimate-v2 work_schedule (Gantt) tab.
--
-- Today these values live only in the rovno frontend localStorage cache, so they
-- are lost on F5 / sign-out. This migration adds the columns the consumer needs
-- to round-trip them through Supabase:
--   estimate_works.planned_start  timestamptz, nullable — bar start date
--   estimate_works.planned_end    timestamptz, nullable — bar end date
--   estimate_dependencies.lag_days integer not null default 0 — FS-link lag
--
-- All three are additive, no backfill needed: existing rows get NULL planned
-- dates (frontend already handles dateless works) and `lag_days = 0` (the
-- existing default behaviour).

alter table public.estimate_works
  add column if not exists planned_start timestamptz,
  add column if not exists planned_end   timestamptz;

alter table public.estimate_dependencies
  add column if not exists lag_days integer not null default 0;
