-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260712130000_estimate_projection_infra.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Sync stabilization P1: server-side projection infrastructure.
--
-- The estimate→(tasks/procurement/HR) projection moves from a client-orchestrated
-- multi-request pipeline into one atomic RPC (20260712130200). This migration adds
-- the concurrency/revision anchors on project_estimates and the project_sync_events
-- ledger that carries cross-session sync signals (realtime consumers arrive in P2;
-- the publication statement lives in 20260712130100, excluded from the curated
-- mirror because ALTER PUBLICATION is not a supported curated statement).
--
-- Columns:
--   * draft_seq — compare-and-set token for the client-side draft save
--     (saveCurrentEstimateDraft): the final statement of a save is
--     UPDATE ... SET draft_seq = draft_seq + 1 WHERE draft_seq = <loaded>;
--     0 rows = another session saved in between = conflict, client re-hydrates.
--   * projection_revision — the client content-hash echoed by the last successful
--     sync_estimate_projection call (UI correlation only, NOT ordered).
--   * projection_seq — server-monotonic projection counter (strict ordering truth).
--   * projection_synced_at / projection_actor — observability of the last projection.

alter table public.project_estimates add column draft_seq bigint not null default 0;
alter table public.project_estimates add column projection_revision text;
alter table public.project_estimates add column projection_seq bigint not null default 0;
alter table public.project_estimates add column projection_synced_at timestamptz;
alter table public.project_estimates add column projection_actor uuid;

alter table public.project_estimates
  add constraint project_estimates_projection_actor_fkey
  foreign key (projection_actor) references public.profiles(id) on delete set null;

-- One estimate root per project is the invariant the whole pipeline assumes
-- (the client loads "the" estimate, the projection RPC raises on multiples).
-- The client's check-then-insert root creation can race two fresh sessions
-- into two roots, which would permanently break projection for that project;
-- make the invariant a constraint. Staging audited clean 2026-07-12; prod must
-- be audited (same GROUP BY/HAVING query) before spush.
create unique index idx_project_estimates_project_id_unique
  on public.project_estimates (project_id);

-- Coordination metadata is server-owned. The table-level UPDATE grant plus the
-- content-writer policy would otherwise let any writer forge/reset the
-- projection bookkeeping or jump draft_seq (breaking the CAS and, near bigint
-- overflow, future projections). End-user roles may only advance draft_seq by
-- exactly one (the save CAS); the SECURITY DEFINER projection RPC runs as the
-- function owner and is exempt.
create or replace function public.guard_estimate_coordination_columns()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if current_user not in ('authenticated', 'anon') then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.draft_seq := 0;
    new.projection_revision := null;
    new.projection_seq := 0;
    new.projection_synced_at := null;
    new.projection_actor := null;
    return new;
  end if;

  if new.projection_revision is distinct from old.projection_revision
     or new.projection_seq is distinct from old.projection_seq
     or new.projection_synced_at is distinct from old.projection_synced_at
     or new.projection_actor is distinct from old.projection_actor
  then
    raise exception 'projection metadata is server-owned' using errcode = '42501';
  end if;

  if new.draft_seq is distinct from old.draft_seq
     and new.draft_seq <> old.draft_seq + 1
  then
    raise exception 'draft_seq may only advance by one' using errcode = '42501';
  end if;

  return new;
end;
$$;

revoke all on function public.guard_estimate_coordination_columns() from public;

create trigger guard_estimate_coordination_columns
  before insert or update on public.project_estimates
  for each row execute function public.guard_estimate_coordination_columns();

-- Cross-session sync ledger: one row per sync-relevant write burst. Readable by
-- every project member (the ledger itself carries no money/PII — consumers react
-- by refetching through their own RLS-gated reads). INSERT is limited to the
-- 'estimate_draft' kind for authenticated writers (the client draft-save tail);
-- all other kinds are written by SECURITY DEFINER RPCs or statement triggers (P2).
create table public.project_sync_events (
  id bigint generated always as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  kind text not null check (kind in ('projection', 'estimate_draft', 'tasks', 'checklist', 'procurement', 'hr', 'hr_payments', 'members')),
  revision text check (revision is null or char_length(revision) <= 200),
  actor_profile_id uuid default auth.uid() references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index idx_project_sync_events_project_id_id on public.project_sync_events(project_id, id desc);
-- The actor FK is ON DELETE SET NULL; without this index every profile
-- deletion seq-scans the ever-growing ledger. Retention (pg_cron prune)
-- arrives with the P2 consumers.
create index idx_project_sync_events_actor_profile_id on public.project_sync_events(actor_profile_id);

alter table public.project_sync_events enable row level security;

create policy project_sync_events_select on public.project_sync_events
  for select to authenticated
  using (public.can_access_project(project_id));

create policy project_sync_events_insert on public.project_sync_events
  for insert to authenticated
  with check (
    public.can_write_project_content(project_id)
    and kind = 'estimate_draft'
    and (actor_profile_id is null or actor_profile_id = auth.uid())
  );

grant select, insert on table public.project_sync_events to authenticated;
grant select, insert on table public.project_sync_events to service_role;
-- The identity-sequence usage grant lives in 20260712130100 (the curated parser
-- does not model sequence grants).
