-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260326203000_owner_transfer_and_member_identity_guard.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Preserve owner-transfer launch behavior and close member-row reassignment bypasses.
-- Scope:
-- - keep projects_update semantics as already established in later migrations
-- - hard-block project_members identity reassignment via UPDATE
-- - include used_credits in delegation trigger fast-path no-op checks

create or replace function public.enforce_project_member_delegation()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid;
  v_owner uuid;
  v_setting text;
begin
  select p.owner_profile_id
  into v_owner
  from public.projects p
  where p.id = new.project_id;

  -- Canonical owner membership row: enforced elsewhere; skip delegation.
  if new.role = 'owner'
     and v_owner is not null
     and new.profile_id = v_owner then
    return new;
  end if;

  -- Ownership transfer: demote former owner member row to co_owner.
  if tg_op = 'UPDATE'
     and old.role = 'owner'
     and new.role = 'co_owner'
     and old.profile_id is distinct from v_owner then
    return new;
  end if;

  v_setting := current_setting('app.member_delegate_actor', true);

  if v_setting is not null and length(trim(v_setting)) > 0 then
    v_actor := v_setting::uuid;
  else
    v_actor := auth.uid();
  end if;

  if v_actor is null then
    raise exception 'Member delegation check could not resolve actor';
  end if;

  if tg_op = 'UPDATE' then
    if old.profile_id is distinct from new.profile_id then
      raise exception 'Project member identity reassignment is not allowed';
    end if;

    if old.profile_id is not distinct from new.profile_id
       and old.role is not distinct from new.role
       and old.ai_access is not distinct from new.ai_access
       and old.finance_visibility is not distinct from new.finance_visibility
       and old.internal_docs_visibility is not distinct from new.internal_docs_visibility
       and old.viewer_regime is not distinct from new.viewer_regime
       and old.credit_limit is not distinct from new.credit_limit
       and old.used_credits is not distinct from new.used_credits then
      return new;
    end if;
  end if;

  perform public.assert_project_participant_delegate_ok(
    v_actor,
    new.project_id,
    new.role,
    new.ai_access,
    new.finance_visibility,
    new.internal_docs_visibility
  );

  return new;
end;
$$;
