-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260423000000_profile_tutorial_state.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Add tutorial tracking fields to profiles.
-- tutorials_completed: array of tutorial keys the user has seen.
-- onboarding_completed_at: timestamp of when user finished the onboarding wizard (null = not done yet).

alter table public.profiles
  add column if not exists onboarding_completed_at timestamptz,
  add column if not exists tutorials_completed text[] not null default '{}';

-- Append a tutorial key to profiles.tutorials_completed (idempotent).
create or replace function public.append_tutorial_completed(
  p_profile_id uuid,
  p_key text
) returns void
language sql
security definer
as $$
  update public.profiles
  set tutorials_completed = array_append(
    array_remove(tutorials_completed, p_key),
    p_key
  )
  where id = p_profile_id;
$$;
