-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260414150000_wave4_tasks_ai_operational_evidence_rpc.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Wave 4: narrow tasks read surface for ai-inference (Layer C).
-- Security: SECURITY DEFINER with explicit gates; capped checklist/comments per task; no task.description.

create or replace function public.get_tasks_ai_operational_evidence(
  p_project_id uuid,
  p_task_limit integer default 25,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_task_limit, 25), 1), 50);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_ai text;
  v_tasks jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('tasks', '[]'::jsonb);
  end if;

  if not public.can_access_project(p_project_id) then
    return jsonb_build_object('tasks', '[]'::jsonb);
  end if;

  v_ai := public.effective_ai_access_for_profile(p_project_id);
  if v_ai is null or v_ai = 'none' then
    return jsonb_build_object('tasks', '[]'::jsonb);
  end if;

  select coalesce(
    (
      with task_rows as (
        select
          t.id,
          t.title,
          t.status,
          t.stage_id,
          ps.title as stage_title,
          t.assignee_profile_id,
          t.due_at,
          t.completed_at,
          t.updated_at
        from public.tasks t
        join public.project_stages ps
          on ps.id = t.stage_id
        where t.project_id = p_project_id
        order by t.updated_at desc, t.id desc
        offset v_offset
        limit v_limit
      )
      select jsonb_agg(
        jsonb_build_object(
          'task_id', tr.id,
          'title', tr.title,
          'status', tr.status,
          'stage_id', tr.stage_id,
          'stage_title', tr.stage_title,
          'assignee_profile_id', tr.assignee_profile_id,
          'due_at', tr.due_at,
          'completed_at', tr.completed_at,
          'updated_at', tr.updated_at,
          'checklist_items', coalesce(cl.items, '[]'::jsonb),
          'recent_comments', coalesce(cm.items, '[]'::jsonb)
        )
        order by tr.updated_at desc, tr.id desc
      )
      from task_rows tr
      left join lateral (
        select coalesce(
          jsonb_agg(
            jsonb_build_object(
              'title', ci.title,
              'is_done', ci.is_done
            )
            order by ci.sort_order
          ),
          '[]'::jsonb
        ) as items
        from (
          select tci.title, tci.is_done, tci.sort_order
          from public.task_checklist_items tci
          where tci.task_id = tr.id
          order by tci.sort_order
          limit 8
        ) ci
      ) cl on true
      left join lateral (
        select coalesce(
          jsonb_agg(
            jsonb_build_object(
              'created_at', c.created_at,
              'body', left(c.body, 400)
            )
            order by c.created_at desc
          ),
          '[]'::jsonb
        ) as items
        from (
          select tc.created_at, tc.body
          from public.task_comments tc
          where tc.task_id = tr.id
          order by tc.created_at desc
          limit 3
        ) c
      ) cm on true
    ),
    '[]'::jsonb
  )
  into v_tasks;

  return jsonb_build_object('tasks', coalesce(v_tasks, '[]'::jsonb));
end;
$$;

revoke all on function public.get_tasks_ai_operational_evidence(uuid, integer, integer) from public;
grant execute on function public.get_tasks_ai_operational_evidence(uuid, integer, integer) to authenticated;
