-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260506160000_import_documents_creates_versions.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 2 hotfix #4 — imported documents weren't appearing in the
-- project Documents tab even though import_documents_to_project reported
-- success.
--
-- Cause: the frontend's project documents fetch (shapeDocumentsWithVersions
-- in src/data/documents-media-source.ts) drops any documents row that has
-- zero document_versions. The original import RPC inserted documents rows
-- only — no document_versions — so links never showed up.
--
-- Fix: when importing, also create a document_versions row that points at
-- the source document's current storage_object. The new doc thereby
-- delegates its preview/download path to the source storage object, which
-- matches the link-not-copy semantics from the Session 2 brief.
--
-- Source-side resolution:
--   workspace: pick the workspace_document_versions row with is_current=true
--              (fall back to most-recent by version_number if no current).
--   org      : same against org_document_versions.

create or replace function public.import_documents_to_project(
  p_project_id uuid,
  p_source_kind text,
  p_source_doc_ids uuid[]
)
returns setof public.documents
language plpgsql
security definer
set search_path = public
as $$
declare
  v_source_id uuid;
  v_inserted public.documents%rowtype;
  v_workspace_row public.workspace_documents%rowtype;
  v_org_row public.org_documents%rowtype;
  v_storage_object_id uuid;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not public.can_write_project_content(p_project_id) then
    raise exception 'Not authorized to add documents to project %', p_project_id;
  end if;

  if p_source_kind not in ('workspace', 'org') then
    raise exception 'Invalid source_kind: %', p_source_kind;
  end if;

  if p_source_doc_ids is null or array_length(p_source_doc_ids, 1) is null then
    return;
  end if;

  foreach v_source_id in array p_source_doc_ids loop
    if p_source_kind = 'workspace' then
      select *
      into v_workspace_row
      from public.workspace_documents
      where id = v_source_id
        and owner_profile_id = auth.uid();

      if not found then
        raise exception 'Workspace document % not accessible', v_source_id;
      end if;

      select wdv.storage_object_id
      into v_storage_object_id
      from public.workspace_document_versions wdv
      where wdv.workspace_document_id = v_source_id
      order by wdv.is_current desc, wdv.version_number desc
      limit 1;

      insert into public.documents (
        project_id,
        type,
        title,
        origin,
        description,
        created_by,
        linked_external_kind,
        linked_workspace_document_id
      )
      values (
        p_project_id,
        coalesce(v_workspace_row.type, 'knowledge_base'),
        v_workspace_row.title,
        'manual',
        v_workspace_row.description,
        auth.uid(),
        'workspace',
        v_source_id
      )
      returning * into v_inserted;
    else
      select *
      into v_org_row
      from public.org_documents
      where id = v_source_id
        and public.is_org_member(org_id);

      if not found then
        raise exception 'Org document % not accessible', v_source_id;
      end if;

      select odv.storage_object_id
      into v_storage_object_id
      from public.org_document_versions odv
      where odv.org_document_id = v_source_id
      order by odv.is_current desc, odv.version_number desc
      limit 1;

      insert into public.documents (
        project_id,
        type,
        title,
        origin,
        description,
        created_by,
        linked_external_kind,
        linked_org_document_id
      )
      values (
        p_project_id,
        coalesce(v_org_row.type, 'knowledge_base'),
        v_org_row.title,
        'manual',
        v_org_row.description,
        auth.uid(),
        'org',
        v_source_id
      )
      returning * into v_inserted;
    end if;

    -- Always create a single version row so the frontend's version-required
    -- shaping (shapeDocumentsWithVersions) doesn't drop the imported doc.
    -- storage_object_id may be null when the source has no uploaded file
    -- yet — the document still renders, just without a preview path.
    -- document_versions has no status/visibility_class columns; the parent
    -- document carries any visibility metadata.
    insert into public.document_versions (
      document_id,
      storage_object_id,
      version_number,
      is_current,
      created_by
    )
    values (
      v_inserted.id,
      v_storage_object_id,
      1,
      true,
      auth.uid()
    );

    return next v_inserted;
  end loop;

  return;
end;
$$;
