-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260306160000_extensions_and_base_helpers.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Enable required extension(s)
create extension if not exists pgcrypto;

-- Reusable trigger helper to keep updated_at current on row updates
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
