-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260508120000_fix_orgs_select_policy_returning_and_guc_name.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Two-part fix unblocking organization creation end-to-end.
--
-- Part 1 (the 42501 spiral):
-- INSERT INTO organizations ... RETURNING id under role authenticated raised
-- 42501 "new row violates row-level security policy" despite WITH CHECK
-- evaluating to true. RETURNING re-evaluates the SELECT USING expression
-- against the just-inserted row. The previous policy was
--   USING (public.is_org_member(id))
-- and is_org_member is SECURITY DEFINER STABLE — STABLE functions share the
-- caller's snapshot, which on an INSERT is fixed BEFORE the new row exists.
-- Both EXISTS subqueries inside is_org_member therefore find nothing for the
-- row being inserted (the organizations row itself, and the org_members row
-- the AFTER INSERT trigger writes during the same statement), so the SELECT
-- USING returned false and PostgreSQL raised the RLS violation on RETURNING.
--
-- Fix: short-circuit the SELECT policy on owner_profile_id = auth.uid().
-- That branch reads owner_profile_id straight from the row (always visible
-- to RETURNING — it IS the new row) and compares it to a session GUC (no
-- snapshot involved), so the just-inserted owner can read the row back.
-- Member access still falls through to is_org_member for non-owner reads.
--
-- Part 2 (separate but real bug surfaced while cleaning up probe rows):
-- mark_organization_deleting() called
--   set_config('rovno.deleting_org_id_' || old.id::text, '1', true)
-- which produces names like rovno.deleting_org_id_<uuid-with-hyphens>.
-- Postgres rejects hyphens in custom GUC names with 42602
-- "invalid configuration parameter name", so DELETE FROM organizations
-- failed before any cascade could happen. Replace hyphens with underscores
-- in the suffix; enforce_org_member_last_owner reads the same shape.

drop policy if exists organizations_select on public.organizations;
create policy organizations_select on public.organizations
  for select
  to authenticated
  using (
    owner_profile_id = auth.uid()
    or public.is_org_member(id)
  );

create or replace function public.mark_organization_deleting()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform set_config(
    'rovno.deleting_org_id_' || replace(old.id::text, '-', '_'),
    '1',
    true
  );
  return old;
end;
$$;

revoke all on function public.mark_organization_deleting() from public;

create or replace function public.enforce_org_member_last_owner()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_org_id uuid;
  v_was_owner boolean;
  v_remaining integer;
begin
  if tg_op = 'DELETE' then
    v_org_id := old.org_id;
    v_was_owner := old.role = 'owner';

    if current_setting(
         'rovno.deleting_org_id_' || replace(v_org_id::text, '-', '_'),
         true
       ) = '1' then
      return old;
    end if;
  else
    if old.role = 'owner' and new.role <> 'owner' then
      v_org_id := old.org_id;
      v_was_owner := true;
    else
      return new;
    end if;
  end if;

  if not v_was_owner then
    return case when tg_op = 'DELETE' then old else new end;
  end if;

  select count(*) into v_remaining
  from public.org_members om
  where om.org_id = v_org_id
    and om.role = 'owner'
    and (tg_op = 'DELETE' and om.id <> old.id
         or tg_op = 'UPDATE' and om.id <> new.id);

  if v_remaining = 0 then
    raise exception 'Cannot remove the last owner of organization %', v_org_id;
  end if;

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;
