-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260317133000_storage_bucket_config_table.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create table public.storage_bucket_config (
  key text primary key,
  bucket text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint storage_bucket_config_key_check
    check (key in ('documents', 'media')),
  constraint storage_bucket_config_bucket_nonempty
    check (length(trim(bucket)) > 0)
);

insert into public.storage_bucket_config (key, bucket)
values
  ('documents', 'project-documents'),
  ('media', 'project-media')
on conflict (key) do update
set
  bucket = excluded.bucket,
  updated_at = now();

revoke all on table public.storage_bucket_config from public;
revoke all on table public.storage_bucket_config from anon;
revoke all on table public.storage_bucket_config from authenticated;

create or replace function public.prepare_project_media_upload(
  p_project_id uuid,
  p_media_type text,
  p_client_filename text,
  p_mime_type text,
  p_size_bytes bigint,
  p_caption text default null
)
returns table (
  upload_intent_id uuid,
  bucket text,
  object_path text,
  filename text,
  mime_type text,
  size_bytes bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_bucket text;
  v_filename text;
  v_intent_id uuid := gen_random_uuid();
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  if not public.can_write_project_content(p_project_id) then
    raise exception 'Insufficient permissions';
  end if;

  select c.bucket
    into v_bucket
  from public.storage_bucket_config c
  where c.key = 'media';

  if v_bucket is null or trim(v_bucket) = '' then
    raise exception 'Media upload bucket is not configured';
  end if;

  v_filename := public.sanitize_uploaded_filename(p_client_filename);

  insert into public.project_media_upload_intents (
    id,
    project_id,
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    media_type,
    caption,
    created_by
  )
  values (
    v_intent_id,
    p_project_id,
    v_bucket,
    format('projects/%s/media/%s/%s', p_project_id, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes,
    nullif(trim(p_media_type), ''),
    nullif(trim(p_caption), ''),
    v_uid
  );

  return query
  select
    v_intent_id,
    v_bucket,
    format('projects/%s/media/%s/%s', p_project_id, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes;
end;
$$;

create or replace function public.prepare_document_upload(
  p_project_id uuid,
  p_type text,
  p_title text,
  p_client_filename text,
  p_mime_type text,
  p_size_bytes bigint,
  p_description text default null
)
returns table (
  upload_intent_id uuid,
  bucket text,
  object_path text,
  filename text,
  mime_type text,
  size_bytes bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_bucket text;
  v_filename text;
  v_intent_id uuid := gen_random_uuid();
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  if not public.can_write_project_content(p_project_id) then
    raise exception 'Insufficient permissions';
  end if;

  if coalesce(trim(p_type), '') = '' then
    raise exception 'Document type is required';
  end if;

  if coalesce(trim(p_title), '') = '' then
    raise exception 'Document title is required';
  end if;

  select c.bucket
    into v_bucket
  from public.storage_bucket_config c
  where c.key = 'documents';

  if v_bucket is null or trim(v_bucket) = '' then
    raise exception 'Document upload bucket is not configured';
  end if;

  v_filename := public.sanitize_uploaded_filename(p_client_filename);

  insert into public.document_upload_intents (
    id,
    project_id,
    type,
    title,
    description,
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    created_by
  )
  values (
    v_intent_id,
    p_project_id,
    trim(p_type),
    trim(p_title),
    nullif(trim(p_description), ''),
    v_bucket,
    format('projects/%s/documents/%s/%s', p_project_id, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes,
    v_uid
  );

  return query
  select
    v_intent_id,
    v_bucket,
    format('projects/%s/documents/%s/%s', p_project_id, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes;
end;
$$;