-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260414120000_wave1_get_ai_project_snapshot.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Wave 1: Layer A compact project snapshot for AI inference (contract Phase 2 start).
-- Security: SECURITY DEFINER with explicit gates on every read; grant authenticated only.

create or replace function public.get_ai_project_snapshot(p_project_id uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_role text;
  v_ai text;
  v_fin text;
  v_docs text;
  v_title text;
  v_ptype text;
  v_pmode text;
  v_ai_desc text;
  v_estimate_present boolean := false;
  v_estimate_status text;
  v_assistant_estimate_status text;
begin
  if v_uid is null then
    return null;
  end if;

  if not public.can_access_project(p_project_id) then
    return null;
  end if;

  v_ai := public.effective_ai_access_for_profile(p_project_id);
  if v_ai is null or v_ai = 'none' then
    return null;
  end if;

  v_role := public.project_role_for_profile(p_project_id, v_uid);
  if v_role is null then
    return null;
  end if;

  v_fin := coalesce(public.effective_finance_visibility(p_project_id), 'none');
  v_docs := coalesce(public.effective_internal_docs_visibility(p_project_id), 'none');

  select p.title, p.project_type, p.project_mode, p.ai_description
  into v_title, v_ptype, v_pmode, v_ai_desc
  from public.projects p
  where p.id = p_project_id;

  if not found then
    return null;
  end if;

  select exists (
    select 1
    from public.project_estimates pe
    where pe.project_id = p_project_id
  )
  into v_estimate_present;

  select pe.status
  into v_estimate_status
  from public.project_estimates pe
  where pe.project_id = p_project_id
  order by pe.updated_at desc, pe.created_at desc
  limit 1;

  -- DB vocabulary -> assistant-facing labels (fieldNotes.estimateStatus); 1:1 for core statuses.
  v_assistant_estimate_status := case
    when not coalesce(v_estimate_present, false) then null::text
    when v_estimate_status = 'draft' then 'draft'
    when v_estimate_status = 'approved' then 'approved'
    when v_estimate_status = 'archived' then 'archived'
    else coalesce(v_estimate_status, 'unknown')
  end;

  return jsonb_build_object(
    'snapshotVersion', 1,
    'identity', jsonb_build_object(
      'projectId', p_project_id,
      'title', v_title,
      'projectType', v_ptype,
      'projectMode', v_pmode
    ),
    'authority', jsonb_build_object(
      'userRole', v_role,
      'aiAccessEnvelope', v_ai,
      'effectiveVisibilityEnvelope', jsonb_build_object(
        'financeVisibility', v_fin,
        'internalDocsVisibility', v_docs
      )
    ),
    'summary', jsonb_build_object(
      'shortProjectDescription', v_ai_desc,
      'estimatePresence', coalesce(v_estimate_present, false),
      'estimateStatus', v_assistant_estimate_status,
      'procurementCountsByStatus', null,
      'hrCountsByStatus', null,
      'participantsSummary', null,
      'recentActivitySlice', null
    )
  );
end;
$$;

revoke all on function public.get_ai_project_snapshot(uuid) from public;
grant execute on function public.get_ai_project_snapshot(uuid) to authenticated;
