-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260630110000_inventory_canonical_identity.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Shared, DB-level canonical identity for inventory_items.
--
-- Problem: inventory items are deduped only in the app layer, and the dedup key is
-- not consistent. The frontend receive + same-project-transfer paths key items on
-- inventoryItemMatchKey = normalizeName(title) | normalizeName(notes) |
-- lower(trim(unit)) (rovno/src/data/orders-source.ts:684-694,
-- rovno/src/lib/procurement-utils.ts normalizeName), while the new
-- place_cross_project_stock_transfer RPC originally keyed on title+unit+sku. Two
-- paths resolving the same physical material to different rows fragment on-hand
-- balance, and there is no shared definition.
--
-- Fix (product decision: "shared DB canonical identity"): one immutable identity
-- string, computed the same way everywhere, materialized as a generated column.
--
-- normalize_inventory_text replicates normalizeName: lower -> fold whitespace to a
-- single regular space -> trim -> collapse -> strip all but [a-z а-я ё 0-9, space,
-- . x × -]. The strip runs AFTER the collapse, matching the JS ("a , b" -> "a  b" on
-- both sides). inventory_item_identity = normalized title | normalized notes |
-- lower(trim(unit)); unit is only lower/edge-trimmed, never punctuation-stripped,
-- mirroring unit.trim().toLowerCase().
--
-- Whitespace parity (VALIDATED ON STAGING, PostgreSQL 17.6, collation en_US.UTF-8):
-- JS \s matches NBSP and the other Unicode whitespace codepoints; on this server
-- Postgres \s ALSO matches all of them EXCEPT U+FEFF (BOM / zero-width no-break
-- space). So the only explicit handling needed is replacing U+FEFF (chr(65279)) with
-- a space up front; \s then handles NBSP, narrow/figure/ideographic spaces, line/para
-- separators, etc. normalize_inventory_text was diffed against the JS normalizeName
-- over a battery (NBSP, FEFF, ideographic/thin space, punctuation, ×, double-space)
-- and matched on every case. lower() also folds Cyrillic correctly under this
-- collation. Re-run that diff on the prod server before the unique-index step ships
-- (Postgres \s Unicode behavior is locale/version dependent).

create function public.normalize_inventory_text(p_text text)
returns text
language sql
immutable
set search_path = public, extensions, pg_catalog
as $$
  select regexp_replace(                                          -- 4. strip to keep-set
           regexp_replace(                                        -- 3. collapse runs
             regexp_replace(                                      -- 2. trim edges
               replace(lower(coalesce(p_text, '')), chr(65279), ' '),  -- 1. lower; U+FEFF -> ' ' (PG \s misses it)
               '^\s+|\s+$', '', 'g'),
             '\s+', ' ', 'g'),
           '[^a-zа-яё0-9 .x×-]', '', 'g')
$$;

create function public.inventory_item_identity(p_title text, p_notes text, p_unit text)
returns text
language sql
immutable
set search_path = public, extensions, pg_catalog
as $$
  select public.normalize_inventory_text(p_title)
      || '|' || public.normalize_inventory_text(p_notes)
      || '|' || lower(regexp_replace(
                  replace(coalesce(p_unit, ''), chr(65279), ' '),
                  '^\s+|\s+$', '', 'g'))
$$;

alter table public.inventory_items
  add column identity_key text
  generated always as (public.inventory_item_identity(title, notes, unit)) stored;

create index idx_inventory_items_project_identity on public.inventory_items (project_id, identity_key);

-- STAGED ENFORCEMENT (deliberate): this migration ships the identity + a NON-unique
-- index for fast lookup, and converges place_cross_project_stock_transfer onto it. It
-- does NOT yet add a UNIQUE constraint: a hard unique index would make existing
-- frontend item-insert paths (receive, same-project transfer) fail with 23505 the
-- moment SQL normalization diverges from JS normalizeName on any edge input, and
-- those paths are not yet upsert-safe. The unique index is the explicit final step,
-- to land WITH the phase-2 frontend change that switches those inserts to upsert on
-- (project_id, identity_key):
--   create unique index inventory_items_project_identity_key
--     on public.inventory_items (project_id, identity_key);
-- That step is also where any pre-existing duplicates must first be deduped. The only
-- FK referrers of inventory_items are inventory_movements and inventory_balances
-- (both ON DELETE CASCADE), so a dedup repoints inventory_movements.inventory_item_id
-- to the surviving row, folds inventory_balances quantities into it, and deletes the
-- duplicate items -- authored only after a staging dup-count, against the real rows.
