-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260317121000_storage_upload_rpcs.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create function public.prepare_project_media_upload(
  p_project_id uuid,
  p_media_type text,
  p_client_filename text,
  p_mime_type text,
  p_size_bytes bigint,
  p_caption text
)
returns table (
  upload_intent_id uuid,
  bucket text,
  object_path text,
  filename text,
  mime_type text,
  size_bytes bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_upload_intent_id uuid := gen_random_uuid();
  v_bucket text;
  v_filename text;
  v_basename text;
  v_extension text;
  v_sanitized_filename text;
  v_mime_type text := nullif(btrim(p_mime_type), '');
  v_caption text := nullif(btrim(p_caption), '');
  v_object_path text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not public.can_write_project_content(p_project_id) then
    raise exception 'Project write access required';
  end if;

  if nullif(btrim(p_media_type), '') is null then
    raise exception 'Media type is required';
  end if;

  if p_size_bytes is not null and p_size_bytes < 0 then
    raise exception 'Upload size cannot be negative';
  end if;

  v_bucket := nullif(btrim(current_setting('app.storage_upload_bucket', true)), '');

  if v_bucket is null then
    raise exception 'Storage upload bucket is not configured';
  end if;

  v_filename := coalesce(p_client_filename, '');
  v_filename := regexp_replace(v_filename, '^.*[\\/]', '');
  v_filename := regexp_replace(v_filename, '[[:cntrl:]]', '', 'g');
  v_filename := regexp_replace(v_filename, '[\\/]+', '', 'g');
  v_filename := regexp_replace(v_filename, '\s+', ' ', 'g');
  v_filename := btrim(v_filename);
  v_extension := substring(v_filename from '(\.[A-Za-z0-9]{1,16})$');
  v_basename := regexp_replace(v_filename, '(\.[A-Za-z0-9]{1,16})$', '');
  v_basename := lower(v_basename);
  v_basename := regexp_replace(v_basename, '[^a-z0-9._ -]+', '-', 'g');
  v_basename := regexp_replace(v_basename, '[ ._-]+', '-', 'g');
  v_basename := btrim(v_basename, '-');

  if v_basename = '' then
    v_basename := 'file';
  end if;

  v_extension := lower(coalesce(v_extension, ''));
  v_sanitized_filename := v_basename || v_extension;
  v_object_path := format('projects/%s/media/%s/%s', p_project_id, v_upload_intent_id, v_sanitized_filename);

  insert into public.project_media_upload_intents (
    id,
    project_id,
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    media_type,
    caption,
    created_by
  )
  values (
    v_upload_intent_id,
    p_project_id,
    v_bucket,
    v_object_path,
    v_sanitized_filename,
    v_mime_type,
    p_size_bytes,
    btrim(p_media_type),
    v_caption,
    auth.uid()
  );

  return query
  select
    v_upload_intent_id,
    v_bucket,
    v_object_path,
    v_sanitized_filename,
    v_mime_type,
    p_size_bytes;
end;
$$;

create function public.finalize_project_media_upload(p_upload_intent_id uuid)
returns table (
  project_media_id uuid,
  storage_object_id uuid,
  project_id uuid,
  bucket text,
  object_path text,
  filename text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_intent public.project_media_upload_intents%rowtype;
  v_storage_object_id uuid;
  v_project_media_id uuid;
  v_object_exists boolean;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_intent
  from public.project_media_upload_intents
  where id = p_upload_intent_id
  for update;

  if not found then
    raise exception 'Upload intent not found';
  end if;

  if v_intent.created_by <> auth.uid() then
    raise exception 'Upload intent does not belong to current user';
  end if;

  if not public.can_write_project_content(v_intent.project_id) then
    raise exception 'Project write access required';
  end if;

  if v_intent.project_media_id is not null then
    return query
    select
      pm.id,
      pm.storage_object_id,
      pm.project_id,
      so.bucket,
      so.object_path,
      so.filename
    from public.project_media pm
    join public.storage_objects so
      on so.id = pm.storage_object_id
    where pm.id = v_intent.project_media_id
      and so.bucket = v_intent.bucket
      and so.object_path = v_intent.object_path;

    if found then
      return;
    end if;

    raise exception 'Upload intent is finalized but linked project media is unavailable';
  end if;

  select exists (
    select 1
    from storage.objects so
    where so.bucket_id = v_intent.bucket
      and so.name = v_intent.object_path
  )
  into v_object_exists;

  if not v_object_exists then
    raise exception 'Storage object is not accessible';
  end if;

  insert into public.storage_objects (
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    uploaded_by
  )
  values (
    v_intent.bucket,
    v_intent.object_path,
    v_intent.filename,
    v_intent.mime_type,
    v_intent.size_bytes,
    v_intent.created_by
  )
  on conflict (bucket, object_path) do nothing;

  select so.id
  into v_storage_object_id
  from public.storage_objects so
  where so.bucket = v_intent.bucket
    and so.object_path = v_intent.object_path;

  if v_storage_object_id is null then
    raise exception 'Storage object linkage could not be resolved';
  end if;

  insert into public.project_media (
    project_id,
    storage_object_id,
    uploaded_by,
    media_type,
    caption
  )
  values (
    v_intent.project_id,
    v_storage_object_id,
    v_intent.created_by,
    v_intent.media_type,
    v_intent.caption
  )
  returning id
  into v_project_media_id;

  update public.project_media_upload_intents
  set project_media_id = v_project_media_id,
      finalized_at = coalesce(finalized_at, now())
  where id = v_intent.id;

  return query
  select
    pm.id,
    pm.storage_object_id,
    pm.project_id,
    so.bucket,
    so.object_path,
    so.filename
  from public.project_media pm
  join public.storage_objects so
    on so.id = pm.storage_object_id
  where pm.id = v_project_media_id;
end;
$$;

create function public.prepare_document_upload(
  p_project_id uuid,
  p_type text,
  p_title text,
  p_client_filename text,
  p_mime_type text,
  p_size_bytes bigint,
  p_description text
)
returns table (
  upload_intent_id uuid,
  bucket text,
  object_path text,
  filename text,
  mime_type text,
  size_bytes bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_upload_intent_id uuid := gen_random_uuid();
  v_bucket text;
  v_filename text;
  v_basename text;
  v_extension text;
  v_sanitized_filename text;
  v_type text := nullif(btrim(p_type), '');
  v_title text := nullif(btrim(p_title), '');
  v_mime_type text := nullif(btrim(p_mime_type), '');
  v_description text := nullif(btrim(p_description), '');
  v_object_path text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if not public.can_write_project_content(p_project_id) then
    raise exception 'Project write access required';
  end if;

  if v_type is null then
    raise exception 'Document type is required';
  end if;

  if v_title is null then
    raise exception 'Document title is required';
  end if;

  if p_size_bytes is not null and p_size_bytes < 0 then
    raise exception 'Upload size cannot be negative';
  end if;

  v_bucket := nullif(btrim(current_setting('app.storage_upload_bucket', true)), '');

  if v_bucket is null then
    raise exception 'Storage upload bucket is not configured';
  end if;

  v_filename := coalesce(p_client_filename, '');
  v_filename := regexp_replace(v_filename, '^.*[\\/]', '');
  v_filename := regexp_replace(v_filename, '[[:cntrl:]]', '', 'g');
  v_filename := regexp_replace(v_filename, '[\\/]+', '', 'g');
  v_filename := regexp_replace(v_filename, '\s+', ' ', 'g');
  v_filename := btrim(v_filename);
  v_extension := substring(v_filename from '(\.[A-Za-z0-9]{1,16})$');
  v_basename := regexp_replace(v_filename, '(\.[A-Za-z0-9]{1,16})$', '');
  v_basename := lower(v_basename);
  v_basename := regexp_replace(v_basename, '[^a-z0-9._ -]+', '-', 'g');
  v_basename := regexp_replace(v_basename, '[ ._-]+', '-', 'g');
  v_basename := btrim(v_basename, '-');

  if v_basename = '' then
    v_basename := 'file';
  end if;

  v_extension := lower(coalesce(v_extension, ''));
  v_sanitized_filename := v_basename || v_extension;
  v_object_path := format('projects/%s/documents/%s/%s', p_project_id, v_upload_intent_id, v_sanitized_filename);

  insert into public.document_upload_intents (
    id,
    project_id,
    type,
    title,
    description,
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    created_by
  )
  values (
    v_upload_intent_id,
    p_project_id,
    v_type,
    v_title,
    v_description,
    v_bucket,
    v_object_path,
    v_sanitized_filename,
    v_mime_type,
    p_size_bytes,
    auth.uid()
  );

  return query
  select
    v_upload_intent_id,
    v_bucket,
    v_object_path,
    v_sanitized_filename,
    v_mime_type,
    p_size_bytes;
end;
$$;

create function public.finalize_document_upload(p_upload_intent_id uuid)
returns table (
  document_id uuid,
  document_version_id uuid,
  storage_object_id uuid,
  project_id uuid,
  bucket text,
  object_path text,
  filename text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_intent public.document_upload_intents%rowtype;
  v_storage_object_id uuid;
  v_document_id uuid;
  v_document_version_id uuid;
  v_existing_storage_object_id uuid;
  v_object_exists boolean;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_intent
  from public.document_upload_intents
  where id = p_upload_intent_id
  for update;

  if not found then
    raise exception 'Upload intent not found';
  end if;

  if v_intent.created_by <> auth.uid() then
    raise exception 'Upload intent does not belong to current user';
  end if;

  if not public.can_write_project_content(v_intent.project_id) then
    raise exception 'Project write access required';
  end if;

  select exists (
    select 1
    from storage.objects so
    where so.bucket_id = v_intent.bucket
      and so.name = v_intent.object_path
  )
  into v_object_exists;

  if not v_object_exists then
    raise exception 'Storage object is not accessible';
  end if;

  insert into public.storage_objects (
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    uploaded_by
  )
  values (
    v_intent.bucket,
    v_intent.object_path,
    v_intent.filename,
    v_intent.mime_type,
    v_intent.size_bytes,
    v_intent.created_by
  )
  on conflict (bucket, object_path) do nothing;

  select so.id
  into v_storage_object_id
  from public.storage_objects so
  where so.bucket = v_intent.bucket
    and so.object_path = v_intent.object_path;

  if v_storage_object_id is null then
    raise exception 'Storage object linkage could not be resolved';
  end if;

  if v_intent.document_id is not null then
    v_document_id := v_intent.document_id;

    select dv.id, dv.storage_object_id
    into v_document_version_id, v_existing_storage_object_id
    from public.document_versions dv
    where dv.document_id = v_document_id
      and dv.version_number = 1
    limit 1;

    if v_document_version_id is null then
      insert into public.document_versions (
        document_id,
        storage_object_id,
        version_number,
        is_current,
        created_by
      )
      values (
        v_document_id,
        v_storage_object_id,
        1,
        true,
        v_intent.created_by
      )
      returning id
      into v_document_version_id;
    elsif v_existing_storage_object_id is distinct from v_storage_object_id then
      raise exception 'Upload intent is finalized but linked document version does not match the reserved storage object';
    end if;

    update public.document_upload_intents
    set finalized_at = coalesce(finalized_at, now())
    where id = v_intent.id;

    return query
    select
      d.id,
      dv.id,
      so.id,
      d.project_id,
      so.bucket,
      so.object_path,
      so.filename
    from public.documents d
    join public.document_versions dv
      on dv.document_id = d.id
     and dv.version_number = 1
    join public.storage_objects so
      on so.id = dv.storage_object_id
    where d.id = v_document_id
      and so.bucket = v_intent.bucket
      and so.object_path = v_intent.object_path;

    if found then
      return;
    end if;

    raise exception 'Upload intent is finalized but linked document is unavailable';
  end if;

  insert into public.documents (
    project_id,
    type,
    title,
    origin,
    description,
    created_by
  )
  values (
    v_intent.project_id,
    v_intent.type,
    v_intent.title,
    'uploaded',
    v_intent.description,
    v_intent.created_by
  )
  returning id
  into v_document_id;

  insert into public.document_versions (
    document_id,
    storage_object_id,
    version_number,
    is_current,
    created_by
  )
  values (
    v_document_id,
    v_storage_object_id,
    1,
    true,
    v_intent.created_by
  )
  returning id
  into v_document_version_id;

  update public.document_upload_intents
  set document_id = v_document_id,
      finalized_at = coalesce(finalized_at, now())
  where id = v_intent.id;

  return query
  select
    d.id,
    dv.id,
    so.id,
    d.project_id,
    so.bucket,
    so.object_path,
    so.filename
  from public.documents d
  join public.document_versions dv
    on dv.document_id = d.id
   and dv.version_number = 1
  join public.storage_objects so
    on so.id = dv.storage_object_id
  where d.id = v_document_id;
end;
$$;
