-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260604120100_get_card_on_file_prefer_binding.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- get_card_on_file(): теперь учитывает смену карты (card_bindings), а не только
-- последний подтверждённый платёж. Возвращает last-4 + бренд самой свежей карты:
-- берём более позднюю по времени из (а) последней ACTIVE-привязки в card_bindings и
-- (б) последнего confirmed payment_intents с Pan. Так сразу после "Изменить карту"
-- UI показывает новую карту, ещё до первого автосписания по ней.
--
-- По-прежнему отдаём ТОЛЬКО last4 + brand; rebill_id и остальное уведомление на
-- клиент не уходят. auth.uid()-scoping: каждый видит только свою карту, аноним — ничего.
-- Бренд инферится из реального BIN-префикса в маскированном PAN (одинаково для обоих
-- источников).

create or replace function public.get_card_on_file()
returns table (last4 text, brand text)
language sql
security definer
set search_path = public
as $$
  with candidates as (
    select cb.pan_masked as pan, cb.bound_at as ts
    from public.card_bindings cb
    where cb.profile_id = auth.uid()
      and cb.status = 'active'
      and nullif(cb.pan_masked, '') is not null
    union all
    select pi.last_notification->>'Pan' as pan, pi.confirmed_at as ts
    from public.payment_intents pi
    where pi.profile_id = auth.uid()
      and pi.status = 'confirmed'
      and pi.last_notification ? 'Pan'
      and nullif(pi.last_notification->>'Pan', '') is not null
  ),
  latest as (
    select pan
    from candidates
    order by ts desc nulls last
    limit 1
  )
  select
    right(latest.pan, 4) as last4,
    case
      when left(latest.pan, 1) = '4' then 'Visa'
      when left(latest.pan, 4) between '2200' and '2204' then 'МИР'
      when left(latest.pan, 2) between '51' and '55' then 'Mastercard'
      when left(latest.pan, 4) between '2221' and '2720' then 'Mastercard'
      else null
    end as brand
  from latest;
$$;

revoke all on function public.get_card_on_file() from public;
-- Supabase's default GRANT EXECUTE ... TO anon is NOT removed by `revoke from public`
-- (audit L1), so revoke it explicitly for consistency with the payment RPCs. The
-- function is auth.uid()-scoped, so an anon caller would get zero rows regardless.
revoke execute on function public.get_card_on_file() from anon;
grant execute on function public.get_card_on_file() to authenticated;
