-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260629120000_add_procurement_item_detail_columns.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Persist the procurement item-detail editor's field set on public.procurement_items.
--
-- The detail editor surfaces notes, a required-by date, a preferred supplier, a preferred
-- inventory location, and the actual (vs planned) unit price, but only the original
-- create-time columns are stored today, so for real (authenticated) users these edits are
-- written to the in-memory store and lost on reload. Add the backing columns so the editor
-- can persist them through the existing procurement_items UPDATE path.
--
-- Attachments are intentionally NOT added here: local-file attachments use an ephemeral
-- in-browser blob: URL with no Supabase Storage upload flow, so persisting them would store
-- a dead link. Attachments stay client-only until a real upload flow exists.
--
-- All columns are nullable: procurement_items is a populated table, so no NOT NULL-without-
-- default is added and no backfill is required.
--
-- required_by_date is text (an ISO date string the frontend already produces), not a date
-- column, because the backend-truth mirror generator does not yet map the SQL `date` type
-- and would emit it as `unknown`. text maps cleanly to `string | null`.
--
-- location_preferred_id references public.inventory_locations(id) on delete set null: a
-- preferred location is advisory metadata, so deleting the location must not cascade-delete
-- the procurement item -- it just clears the preference (matches inventory_movements.
-- inventory_location_id semantics in 20260306163500).
--
-- The existing procurement_items RLS policies (20260306170000) gate on project_id at the row
-- level, not per column, so no new policy or grant is needed. The set_procurement_items_updated_at
-- trigger keeps updated_at current on edits; this migration does not touch updated_at.

alter table public.procurement_items
  add column notes text,
  add column required_by_date text,
  add column supplier_preferred text,
  add column location_preferred_id uuid references public.inventory_locations(id) on delete set null,
  add column actual_unit_price_cents bigint check (actual_unit_price_cents is null or actual_unit_price_cents >= 0);

create index idx_procurement_items_location_preferred_id on public.procurement_items(location_preferred_id);
