-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260415120000_wave6_participants_activity_ai_evidence_rpcs.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Wave 6: bounded participants + activity read surfaces for ai-inference (Layer C secondary).
-- Security: SECURITY DEFINER with explicit gates; hard caps; activity never exposes payload jsonb.
-- HR-shaped activity rows are omitted for callers without can_access_hr_domain (defense in depth vs table RLS).

create or replace function public.get_project_participants_ai_evidence(
  p_project_id uuid,
  p_limit integer default 30,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 30), 1), 50);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_ai text;
  v_participants jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('participants', '[]'::jsonb);
  end if;

  if not public.can_access_project(p_project_id) then
    return jsonb_build_object('participants', '[]'::jsonb);
  end if;

  v_ai := public.effective_ai_access_for_profile(p_project_id);
  if v_ai is null or v_ai = 'none' then
    return jsonb_build_object('participants', '[]'::jsonb);
  end if;

  select coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'profile_id', rows.profile_id,
          'role', rows.role,
          'viewer_regime', rows.viewer_regime,
          'joined_at', rows.joined_at,
          'display_name', rows.display_name
        )
        order by rows.joined_at asc, rows.profile_id asc
      )
      from (
        select
          pm.profile_id,
          pm.role,
          pm.viewer_regime,
          pm.joined_at,
          left(coalesce(pr.full_name, ''), 120) as display_name
        from public.project_members pm
        left join public.profiles pr
          on pr.id = pm.profile_id
        where pm.project_id = p_project_id
        order by pm.joined_at asc, pm.profile_id asc
        offset v_offset
        limit v_limit
      ) rows
    ),
    '[]'::jsonb
  )
  into v_participants;

  return jsonb_build_object('participants', coalesce(v_participants, '[]'::jsonb));
end;
$$;

revoke all on function public.get_project_participants_ai_evidence(uuid, integer, integer) from public;
grant execute on function public.get_project_participants_ai_evidence(uuid, integer, integer) to authenticated;

create or replace function public.get_activity_ai_evidence(
  p_project_id uuid,
  p_limit integer default 20,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 20), 1), 50);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_ai text;
  v_can_hr boolean;
  v_events jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('events', '[]'::jsonb);
  end if;

  if not public.can_access_project(p_project_id) then
    return jsonb_build_object('events', '[]'::jsonb);
  end if;

  v_ai := public.effective_ai_access_for_profile(p_project_id);
  if v_ai is null or v_ai = 'none' then
    return jsonb_build_object('events', '[]'::jsonb);
  end if;

  v_can_hr := public.can_access_hr_domain(p_project_id);

  select coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'event_id', rows.id,
          'created_at', rows.created_at,
          'action_type', rows.action_type,
          'entity_type', rows.entity_type,
          'entity_id', rows.entity_id,
          'actor_profile_id', rows.actor_profile_id,
          'actor_display_name', rows.actor_display_name
        )
        order by rows.created_at desc, rows.id desc
      )
      from (
        select
          ae.id,
          ae.created_at,
          ae.action_type,
          ae.entity_type,
          ae.entity_id,
          ae.actor_profile_id,
          left(coalesce(ap.full_name, ''), 80) as actor_display_name
        from public.activity_events ae
        left join public.profiles ap
          on ap.id = ae.actor_profile_id
        where ae.project_id = p_project_id
          and (
            v_can_hr
            or lower(coalesce(ae.entity_type, '')) not like 'hr%'
          )
        order by ae.created_at desc, ae.id desc
        offset v_offset
        limit v_limit
      ) rows
    ),
    '[]'::jsonb
  )
  into v_events;

  return jsonb_build_object('events', coalesce(v_events, '[]'::jsonb));
end;
$$;

revoke all on function public.get_activity_ai_evidence(uuid, integer, integer) from public;
grant execute on function public.get_activity_ai_evidence(uuid, integer, integer) to authenticated;
