-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260306160500_core_profiles_and_preferences.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  locale text not null default 'en' check (locale in ('ru', 'en', 'de', 'fr')),
  timezone text not null default 'UTC',
  plan text not null default 'free' check (plan in ('free', 'pro', 'business')),
  credits_free integer not null default 0 check (credits_free >= 0),
  credits_paid integer not null default 0 check (credits_paid >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index idx_profiles_email_unique
  on public.profiles (lower(email))
  where email is not null;

create table public.profile_settings (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  role_title text,
  phone text,
  bio text,
  signature_block text,
  currency text not null default 'RUB' check (currency in ('RUB', 'USD', 'EUR', 'GBP')),
  units text not null default 'metric' check (units in ('metric', 'imperial')),
  date_format text not null default 'dd.MM.yyyy' check (date_format in ('dd.MM.yyyy', 'MM/dd/yyyy', 'yyyy-MM-dd')),
  week_start text not null default 'monday' check (week_start in ('monday', 'sunday')),
  ai_output_language text not null default 'auto' check (ai_output_language in ('ru', 'en', 'auto')),
  automation_level text not null default 'assisted' check (automation_level in ('manual', 'assisted', 'full', 'observer')),
  ai_data_usage_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notification_preferences (
  profile_id uuid primary key references public.profiles(id) on delete cascade,
  in_app_enabled boolean not null default true,
  email_enabled boolean not null default false,
  digest_frequency text not null default 'instant' check (digest_frequency in ('instant', 'daily', 'weekly')),
  event_toggles jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger set_profile_settings_updated_at
before update on public.profile_settings
for each row execute function public.set_updated_at();

create trigger set_notification_preferences_updated_at
before update on public.notification_preferences
for each row execute function public.set_updated_at();
