-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260705191000_p31_procurement_received_columns.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- P3.1 (β): persisted receipt progress on procurement_items.
--
-- mark_procurement_received (bot write-action) needs "how much of this item
-- already arrived" to validate qty + already_received <= ordered. Receipt
-- state has so far only existed as inventory_movements rows keyed by
-- order_line_id, but movements require a NOT NULL inventory_item_id and
-- there is no find-or-create helper for inventory items — resolving one on
-- every bot receipt would drag the whole canonical-identity machinery into
-- an MVP flow. Per the P3.1 master doc (open question 3) the MVP records
-- receipts directly on the procurement item and skips movements; the
-- movements-based order_lines pipeline is unaffected.
--
-- received_qty is cumulative across partial receipts. received_at tracks the
-- most recent receipt.

alter table public.procurement_items
  add column received_qty numeric(14,3) not null default 0
    check (received_qty >= 0);

alter table public.procurement_items
  add column received_at timestamptz;
