-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260415130000_wave7_documents_media_ai_metadata_evidence.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Wave 7: bounded documents + project media metadata for ai-inference (Layer C).
-- Security: SECURITY DEFINER with explicit gates; hard caps; visibility matches documents_select / project_media_select;
-- no document body, description, OCR, or storage content — metadata only.

create or replace function public.get_documents_ai_metadata_evidence(
  p_project_id uuid,
  p_limit integer default 25,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 25), 1), 50);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_ai text;
  v_docs jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('documents', '[]'::jsonb);
  end if;

  if not public.can_access_project(p_project_id) then
    return jsonb_build_object('documents', '[]'::jsonb);
  end if;

  v_ai := public.effective_ai_access_for_profile(p_project_id);
  if v_ai is null or v_ai = 'none' then
    return jsonb_build_object('documents', '[]'::jsonb);
  end if;

  select coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'document_id', rows.id,
          'title', rows.title,
          'origin', rows.origin,
          'visibility_class', rows.visibility_class,
          'created_at', rows.created_at,
          'updated_at', rows.updated_at,
          'type_or_category', rows.type,
          'created_by_profile_id', rows.created_by,
          'created_by_display_name', rows.created_by_display_name,
          'linked_project_entity', jsonb_build_object(
            'kind', 'project',
            'project_id', p_project_id
          )
        )
        order by rows.updated_at desc, rows.id desc
      )
      from (
        select
          d.id,
          d.title,
          d.origin,
          d.visibility_class,
          d.created_at,
          d.updated_at,
          d.type,
          d.created_by,
          left(coalesce(pr.full_name, ''), 120) as created_by_display_name
        from public.documents d
        left join public.profiles pr
          on pr.id = d.created_by
        where d.project_id = p_project_id
          and (
            d.visibility_class = 'shared_project'
            or public.can_view_internal_documents(p_project_id)
          )
        order by d.updated_at desc, d.id desc
        offset v_offset
        limit v_limit
      ) rows
    ),
    '[]'::jsonb
  )
  into v_docs;

  return jsonb_build_object('documents', coalesce(v_docs, '[]'::jsonb));
end;
$$;

revoke all on function public.get_documents_ai_metadata_evidence(uuid, integer, integer) from public;
grant execute on function public.get_documents_ai_metadata_evidence(uuid, integer, integer) to authenticated;

create or replace function public.get_project_media_ai_metadata_evidence(
  p_project_id uuid,
  p_limit integer default 25,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_limit integer := least(greatest(coalesce(p_limit, 25), 1), 50);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_ai text;
  v_media jsonb;
begin
  if v_uid is null then
    return jsonb_build_object('media', '[]'::jsonb);
  end if;

  if not public.can_access_project(p_project_id) then
    return jsonb_build_object('media', '[]'::jsonb);
  end if;

  v_ai := public.effective_ai_access_for_profile(p_project_id);
  if v_ai is null or v_ai = 'none' then
    return jsonb_build_object('media', '[]'::jsonb);
  end if;

  select coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'media_id', rows.id,
          'title_or_name', rows.title_or_name,
          'visibility_class', rows.visibility_class,
          'created_at', rows.created_at,
          'media_type', rows.media_type,
          'uploaded_by_profile_id', rows.uploaded_by,
          'uploaded_by_display_name', rows.uploaded_by_display_name,
          'linked_project_entity', jsonb_build_object(
            'kind', 'project',
            'project_id', p_project_id
          )
        )
        order by rows.created_at desc, rows.id desc
      )
      from (
        select
          pm.id,
          left(
            coalesce(
              nullif(trim(pm.caption), ''),
              coalesce(so.filename, '')
            ),
            200
          ) as title_or_name,
          pm.visibility_class,
          pm.created_at,
          pm.media_type,
          pm.uploaded_by,
          left(coalesce(pr.full_name, ''), 120) as uploaded_by_display_name
        from public.project_media pm
        join public.storage_objects so
          on so.id = pm.storage_object_id
        left join public.profiles pr
          on pr.id = pm.uploaded_by
        where pm.project_id = p_project_id
          and (
            pm.visibility_class = 'shared_project'
            or public.can_view_internal_documents(p_project_id)
          )
        order by pm.created_at desc, pm.id desc
        offset v_offset
        limit v_limit
      ) rows
    ),
    '[]'::jsonb
  )
  into v_media;

  return jsonb_build_object('media', coalesce(v_media, '[]'::jsonb));
end;
$$;

revoke all on function public.get_project_media_ai_metadata_evidence(uuid, integer, integer) from public;
grant execute on function public.get_project_media_ai_metadata_evidence(uuid, integer, integer) to authenticated;
