-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260613120600_get_resource_article_price_comparison.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 4 — get_resource_article_price_comparison: cross-project price stats
-- for a canonical resource article, powering the resource modal's "История цен"
-- finance-comparison block (your price vs median / average across other projects).
--
--   get_resource_article_price_comparison(p_article_id, p_exclude_project_id default null)
--     Returns jsonb {
--       article_id, sample_count, project_count,
--       median_cents, avg_cents, min_cents, max_cents
--     }
--
-- It aggregates unit_price_cents from estimate_resource_lines linked to this
-- system_resource_article_id, across the CURRENT estimate version of each project
-- the caller can access. Pass p_exclude_project_id to leave the project the user
-- is currently viewing out of the "other projects" comparison.
--
-- Authorization (critical): security definer lets the function read across
-- projects, but every contributing project is gated by can_access_project()
-- (membership check using the caller's auth.uid()), so prices never leak from
-- projects the caller cannot see. Empty / no-access result → counts 0 and null
-- stats (frontend shows "no comparison data"). Grant to authenticated only.

create or replace function public.get_resource_article_price_comparison(
  p_article_id uuid,
  p_exclude_project_id uuid default null
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  with accessible_lines as (
    select
      erl.unit_price_cents,
      pe.project_id
    from public.estimate_resource_lines erl
    join public.estimate_works ew on ew.id = erl.estimate_work_id
    join public.estimate_versions ev on ev.id = ew.estimate_version_id
    join public.project_estimates pe on pe.id = ev.estimate_id
    where erl.system_resource_article_id = p_article_id
      and erl.unit_price_cents is not null
      and ev.is_current = true
      and (p_exclude_project_id is null or pe.project_id <> p_exclude_project_id)
      and public.can_access_project(pe.project_id)
  )
  select jsonb_build_object(
    'article_id', p_article_id,
    'sample_count', count(*),
    'project_count', count(distinct project_id),
    'median_cents', percentile_cont(0.5) within group (order by unit_price_cents)::bigint,
    'avg_cents', round(avg(unit_price_cents))::bigint,
    'min_cents', min(unit_price_cents),
    'max_cents', max(unit_price_cents)
  )
    into v_result
  from accessible_lines;

  return v_result;
end;
$$;

revoke all on function public.get_resource_article_price_comparison(uuid, uuid) from public;
grant execute on function public.get_resource_article_price_comparison(uuid, uuid) to authenticated;
