-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260512132310_estimate_templates_schema.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 3.1 — EstimateTemplate schema (4 tables, indexes, triggers).
--
-- Templates mirror the live-estimate hierarchy
--   EstimateTemplate → TemplateStage → TemplateWork → TemplateResourceLine
-- so the apply-template-to-estimate RPC is a straight tree copy. Owners are
-- polymorphic (system | org | profile) with `owner_id` nullable only when
-- `owner_kind = 'system'`. Children do not carry their own owner; access is
-- inherited from the parent EstimateTemplate via RLS (helpers and policies
-- ship in the companion migration 20260512132320_template_rls.sql).
--
-- Locked architectural decisions (from Cowork discovery iterations 1-4):
--   * `parameter_definitions jsonb` lives on stages/works as a placeholder
--     so a future "parametric multiplier" subsession can add coefficients
--     without a schema break. No parameter logic ships in 3.1.
--   * `published_to_public` + `contact_block jsonb` are part of the
--     publication flow; the moderation queue itself is Session 7+. The
--     rovno.ai system seed is implicitly published.
--   * `default_cost_unit_cents` / `default_markup_bps` / `default_discount_bps`
--     stay nullable on template_resource_lines because system seeds carry
--     no prices. Org/profile templates may set them.
--
-- Resource-type vocabulary matches the canonical 6-value set aligned in
-- 20260428120000_resource_types_alignment.sql (`material, tool, labor,
-- subcontractor, overhead, other`). The apply RPC copies these values
-- straight into `estimate_resource_lines.resource_type` without remap.

create table public.estimate_templates (
  id uuid primary key default gen_random_uuid(),
  owner_kind text not null check (owner_kind in ('system','org','profile')),
  owner_id uuid,
  title text not null,
  description text not null default '',
  scope text not null default 'general'
    check (scope in ('ИЖС','ремонт','ландшафт','баня','гараж','инженерка','коммерческое','general')),
  cover_image_url text,
  published_to_public boolean not null default false,
  contact_block jsonb,
  source text not null default 'user'
    check (source in ('system','user','imported_xlsx')),
  source_version text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint estimate_templates_owner_id_consistency
    check (
      (owner_kind = 'system' and owner_id is null)
      or (owner_kind = 'org' and owner_id is not null)
      or (owner_kind = 'profile' and owner_id is not null)
    ),
  constraint estimate_templates_title_nonempty
    check (length(trim(title)) > 0)
);

create index idx_estimate_templates_owner
  on public.estimate_templates(owner_kind, owner_id);

create index idx_estimate_templates_scope
  on public.estimate_templates(scope);

create index idx_estimate_templates_published
  on public.estimate_templates(published_to_public)
  where published_to_public = true;

-- Enforce single rovno.ai canonical template at the schema level. The seed
-- migration's `on conflict do nothing` relies on this for idempotency
-- against `supabase db reset`.
create unique index estimate_templates_system_singleton
  on public.estimate_templates(owner_kind)
  where owner_kind = 'system';

create trigger set_estimate_templates_updated_at
before update on public.estimate_templates
for each row execute function public.set_updated_at();

create table public.template_stages (
  id uuid primary key default gen_random_uuid(),
  estimate_template_id uuid not null references public.estimate_templates(id) on delete cascade,
  title text not null,
  description text not null default '',
  scope_tag text not null default 'general',
  sort_hint integer not null default 100,
  parameter_definitions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint template_stages_title_nonempty
    check (length(trim(title)) > 0)
);

create index idx_template_stages_template
  on public.template_stages(estimate_template_id);

create trigger set_template_stages_updated_at
before update on public.template_stages
for each row execute function public.set_updated_at();

create table public.template_works (
  id uuid primary key default gen_random_uuid(),
  template_stage_id uuid not null references public.template_stages(id) on delete cascade,
  title text not null,
  description text not null default '',
  sort_hint integer not null default 100,
  parameter_definitions jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint template_works_title_nonempty
    check (length(trim(title)) > 0)
);

create index idx_template_works_stage
  on public.template_works(template_stage_id);

create trigger set_template_works_updated_at
before update on public.template_works
for each row execute function public.set_updated_at();

create table public.template_resource_lines (
  id uuid primary key default gen_random_uuid(),
  template_work_id uuid not null references public.template_works(id) on delete cascade,
  system_resource_article_id uuid references public.system_resource_articles(id) on delete set null,
  title text not null,
  resource_type text not null
    check (resource_type in ('material','tool','labor','subcontractor','overhead','other')),
  unit_display text not null,
  qty_default numeric(14,3) not null default 1
    check (qty_default >= 0),
  default_cost_unit_cents bigint
    check (default_cost_unit_cents is null or default_cost_unit_cents >= 0),
  default_markup_bps integer
    check (default_markup_bps is null or (default_markup_bps >= 0 and default_markup_bps <= 10000)),
  default_discount_bps integer
    check (default_discount_bps is null or (default_discount_bps >= 0 and default_discount_bps <= 10000)),
  sort_hint integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint template_resource_lines_title_nonempty
    check (length(trim(title)) > 0)
);

create index idx_template_resource_lines_work
  on public.template_resource_lines(template_work_id);

create index idx_template_resource_lines_article
  on public.template_resource_lines(system_resource_article_id)
  where system_resource_article_id is not null;

create trigger set_template_resource_lines_updated_at
before update on public.template_resource_lines
for each row execute function public.set_updated_at();
