-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260408120000_estimate_line_pricing_params.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
alter table public.estimate_resource_lines
  add column markup_bps integer
    check (markup_bps is null or (markup_bps >= 0 and markup_bps <= 10000));

alter table public.estimate_resource_lines
  add column discount_bps_override integer
    check (discount_bps_override is null or (discount_bps_override >= 0 and discount_bps_override <= 10000));
