-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260516120000_extend_billing_provider_to_tbank.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Расширяет список разрешённых провайдеров биллинга на 'tbank'.
-- Существующая миграция 20260306165000_billing_launch_tables.sql разрешала только 'stripe'.
-- Stripe оставляем для возможного использования в будущем (USD/EUR подписки).
--
-- Не ломающая миграция: DROP CONSTRAINT + ADD CONSTRAINT с расширенным списком.

-- billing_customers.provider
alter table public.billing_customers
  drop constraint if exists billing_customers_provider_check;
alter table public.billing_customers
  add constraint billing_customers_provider_check
  check (provider in ('stripe', 'tbank'));

-- subscriptions.provider
alter table public.subscriptions
  drop constraint if exists subscriptions_provider_check;
alter table public.subscriptions
  add constraint subscriptions_provider_check
  check (provider in ('stripe', 'tbank'));
