-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260407190000_track4_upload_visibility_class.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Track 4: binary visibility_class on document/media upload pipeline (shared_project | internal).
-- Aligns prepare/finalize RPCs with documents.project_media visibility_class + existing guard triggers.

alter table public.document_upload_intents
  add column visibility_class text not null default 'shared_project'
  check (visibility_class in ('shared_project', 'internal'));

alter table public.project_media_upload_intents
  add column visibility_class text not null default 'shared_project'
  check (visibility_class in ('shared_project', 'internal'));

drop function if exists public.prepare_document_upload(uuid, text, text, text, text, bigint, text);

create function public.prepare_document_upload(
  p_project_id uuid,
  p_type text,
  p_title text,
  p_client_filename text,
  p_mime_type text,
  p_size_bytes bigint,
  p_description text default null,
  p_visibility_class text default 'shared_project'
)
returns table (
  upload_intent_id uuid,
  bucket text,
  object_path text,
  filename text,
  mime_type text,
  size_bytes bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_bucket text;
  v_filename text;
  v_intent_id uuid := gen_random_uuid();
  v_vis text;
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  if not public.can_write_project_content(p_project_id) then
    raise exception 'Insufficient permissions';
  end if;

  if coalesce(trim(p_type), '') = '' then
    raise exception 'Document type is required';
  end if;

  if coalesce(trim(p_title), '') = '' then
    raise exception 'Document title is required';
  end if;

  v_vis := coalesce(nullif(lower(trim(p_visibility_class)), ''), 'shared_project');
  if v_vis not in ('shared_project', 'internal') then
    raise exception 'Invalid visibility_class';
  end if;

  if v_vis = 'internal' and not public.can_view_internal_documents(p_project_id) then
    raise exception 'Insufficient permissions for internal document visibility';
  end if;

  select c.bucket
    into v_bucket
  from public.storage_bucket_config c
  where c.key = 'documents';

  if v_bucket is null or trim(v_bucket) = '' then
    raise exception 'Document upload bucket is not configured';
  end if;

  v_filename := public.sanitize_uploaded_filename(p_client_filename);

  insert into public.document_upload_intents (
    id,
    project_id,
    type,
    title,
    description,
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    created_by,
    visibility_class
  )
  values (
    v_intent_id,
    p_project_id,
    trim(p_type),
    trim(p_title),
    nullif(trim(p_description), ''),
    v_bucket,
    format('projects/%s/documents/%s/%s', p_project_id, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes,
    v_uid,
    v_vis
  );

  return query
  select
    v_intent_id,
    v_bucket,
    format('projects/%s/documents/%s/%s', p_project_id, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes;
end;
$$;

revoke all on function public.prepare_document_upload(uuid, text, text, text, text, bigint, text, text) from public;
grant execute on function public.prepare_document_upload(uuid, text, text, text, text, bigint, text, text) to authenticated;

create or replace function public.finalize_document_upload(p_upload_intent_id uuid)
returns table (
  document_id uuid,
  document_version_id uuid,
  storage_object_id uuid,
  project_id uuid,
  bucket text,
  object_path text,
  filename text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_intent public.document_upload_intents%rowtype;
  v_storage_object_id uuid;
  v_document_id uuid;
  v_document_version_id uuid;
  v_existing_storage_object_id uuid;
  v_object_exists boolean;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_intent
  from public.document_upload_intents
  where id = p_upload_intent_id
  for update;

  if not found then
    raise exception 'Upload intent not found';
  end if;

  if v_intent.created_by <> auth.uid() then
    raise exception 'Upload intent does not belong to current user';
  end if;

  if not public.can_write_project_content(v_intent.project_id) then
    raise exception 'Project write access required';
  end if;

  select exists (
    select 1
    from storage.objects so
    where so.bucket_id = v_intent.bucket
      and so.name = v_intent.object_path
  )
  into v_object_exists;

  if not v_object_exists then
    raise exception 'Storage object is not accessible';
  end if;

  insert into public.storage_objects (
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    uploaded_by
  )
  values (
    v_intent.bucket,
    v_intent.object_path,
    v_intent.filename,
    v_intent.mime_type,
    v_intent.size_bytes,
    v_intent.created_by
  )
  on conflict on constraint storage_objects_bucket_object_path_key do nothing;

  select so.id
  into v_storage_object_id
  from public.storage_objects so
  where so.bucket = v_intent.bucket
    and so.object_path = v_intent.object_path;

  if v_storage_object_id is null then
    raise exception 'Storage object linkage could not be resolved';
  end if;

  if v_intent.document_id is not null then
    v_document_id := v_intent.document_id;

    select dv.id, dv.storage_object_id
    into v_document_version_id, v_existing_storage_object_id
    from public.document_versions dv
    where dv.document_id = v_document_id
      and dv.version_number = 1
    limit 1;

    if v_document_version_id is null then
      insert into public.document_versions (
        document_id,
        storage_object_id,
        version_number,
        is_current,
        created_by
      )
      values (
        v_document_id,
        v_storage_object_id,
        1,
        true,
        v_intent.created_by
      )
      returning id
      into v_document_version_id;
    elsif v_existing_storage_object_id is distinct from v_storage_object_id then
      raise exception 'Upload intent is finalized but linked document version does not match the reserved storage object';
    end if;

    update public.document_upload_intents
    set finalized_at = coalesce(finalized_at, now())
    where id = v_intent.id;

    return query
    select
      d.id,
      dv.id,
      so.id,
      d.project_id,
      so.bucket,
      so.object_path,
      so.filename
    from public.documents d
    join public.document_versions dv
      on dv.document_id = d.id
     and dv.version_number = 1
    join public.storage_objects so
      on so.id = dv.storage_object_id
    where d.id = v_document_id
      and so.bucket = v_intent.bucket
      and so.object_path = v_intent.object_path;

    if found then
      return;
    end if;

    raise exception 'Upload intent is finalized but linked document is unavailable';
  end if;

  insert into public.documents (
    project_id,
    type,
    title,
    origin,
    description,
    created_by,
    visibility_class
  )
  values (
    v_intent.project_id,
    v_intent.type,
    v_intent.title,
    'uploaded',
    v_intent.description,
    v_intent.created_by,
    v_intent.visibility_class
  )
  returning id
  into v_document_id;

  insert into public.document_versions (
    document_id,
    storage_object_id,
    version_number,
    is_current,
    created_by
  )
  values (
    v_document_id,
    v_storage_object_id,
    1,
    true,
    v_intent.created_by
  )
  returning id
  into v_document_version_id;

  update public.document_upload_intents
  set document_id = v_document_id,
      finalized_at = coalesce(finalized_at, now())
  where id = v_intent.id;

  return query
  select
    d.id,
    dv.id,
    so.id,
    d.project_id,
    so.bucket,
    so.object_path,
    so.filename
  from public.documents d
  join public.document_versions dv
    on dv.document_id = d.id
   and dv.version_number = 1
  join public.storage_objects so
    on so.id = dv.storage_object_id
  where d.id = v_document_id;
end;
$$;

drop function if exists public.prepare_project_media_upload(uuid, text, text, text, bigint, text, uuid, boolean);

create function public.prepare_project_media_upload(
  p_project_id uuid,
  p_media_type text,
  p_client_filename text,
  p_mime_type text,
  p_size_bytes bigint,
  p_caption text default null,
  p_task_id uuid default null,
  p_is_final boolean default false,
  p_visibility_class text default 'shared_project'
)
returns table (
  upload_intent_id uuid,
  bucket text,
  object_path text,
  filename text,
  mime_type text,
  size_bytes bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_bucket text;
  v_filename text;
  v_intent_id uuid := gen_random_uuid();
  v_vis text;
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  if not public.can_write_project_content(p_project_id) then
    raise exception 'Insufficient permissions';
  end if;

  if p_is_final and p_task_id is null then
    raise exception 'Final media requires task_id';
  end if;

  if p_task_id is not null then
    if not exists (
      select 1
      from public.tasks t
      where t.id = p_task_id
        and t.project_id = p_project_id
    ) then
      raise exception 'Task must belong to project';
    end if;
  end if;

  v_vis := coalesce(nullif(lower(trim(p_visibility_class)), ''), 'shared_project');
  if v_vis not in ('shared_project', 'internal') then
    raise exception 'Invalid visibility_class';
  end if;

  if v_vis = 'internal' and not public.can_view_internal_documents(p_project_id) then
    raise exception 'Insufficient permissions for internal media visibility';
  end if;

  select c.bucket
    into v_bucket
  from public.storage_bucket_config c
  where c.key = 'media';

  if v_bucket is null or trim(v_bucket) = '' then
    raise exception 'Media upload bucket is not configured';
  end if;

  v_filename := public.sanitize_uploaded_filename(p_client_filename);

  insert into public.project_media_upload_intents (
    id,
    project_id,
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    media_type,
    caption,
    task_id,
    is_final,
    created_by,
    visibility_class
  )
  values (
    v_intent_id,
    p_project_id,
    v_bucket,
    format('projects/%s/media/%s/%s', p_project_id, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes,
    nullif(trim(p_media_type), ''),
    nullif(trim(p_caption), ''),
    p_task_id,
    p_is_final,
    v_uid,
    v_vis
  );

  return query
  select
    v_intent_id,
    v_bucket,
    format('projects/%s/media/%s/%s', p_project_id, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes;
end;
$$;

revoke all on function public.prepare_project_media_upload(uuid, text, text, text, bigint, text, uuid, boolean, text) from public;
grant execute on function public.prepare_project_media_upload(uuid, text, text, text, bigint, text, uuid, boolean, text) to authenticated;

create or replace function public.finalize_project_media_upload(
  p_upload_intent_id uuid,
  p_task_id uuid default null,
  p_is_final boolean default null
)
returns table (
  project_media_id uuid,
  storage_object_id uuid,
  project_id uuid,
  bucket text,
  object_path text,
  filename text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_intent public.project_media_upload_intents%rowtype;
  v_storage_object_id uuid;
  v_project_media_id uuid;
  v_object_exists boolean;
  v_effective_task_id uuid;
  v_effective_is_final boolean;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_intent
  from public.project_media_upload_intents
  where id = p_upload_intent_id
  for update;

  if not found then
    raise exception 'Upload intent not found';
  end if;

  if v_intent.created_by <> auth.uid() then
    raise exception 'Upload intent does not belong to current user';
  end if;

  if not public.can_write_project_content(v_intent.project_id) then
    raise exception 'Project write access required';
  end if;

  v_effective_task_id := coalesce(p_task_id, v_intent.task_id);
  v_effective_is_final := coalesce(p_is_final, v_intent.is_final, false);

  if v_effective_is_final and v_effective_task_id is null then
    raise exception 'Final media requires task_id';
  end if;

  if v_effective_task_id is not null then
    if not exists (
      select 1
      from public.tasks t
      where t.id = v_effective_task_id
        and t.project_id = v_intent.project_id
    ) then
      raise exception 'Task must belong to project';
    end if;
  end if;

  if v_intent.project_media_id is not null then
    update public.project_media
    set task_id = v_effective_task_id,
        is_final = v_effective_is_final
    where id = v_intent.project_media_id;

    update public.project_media_upload_intents
    set task_id = v_effective_task_id,
        is_final = v_effective_is_final,
        finalized_at = coalesce(finalized_at, now())
    where id = v_intent.id;

    return query
    select
      pm.id,
      pm.storage_object_id,
      pm.project_id,
      so.bucket,
      so.object_path,
      so.filename
    from public.project_media pm
    join public.storage_objects so
      on so.id = pm.storage_object_id
    where pm.id = v_intent.project_media_id
      and so.bucket = v_intent.bucket
      and so.object_path = v_intent.object_path;

    if found then
      return;
    end if;

    raise exception 'Upload intent is finalized but linked project media is unavailable';
  end if;

  select exists (
    select 1
    from storage.objects so
    where so.bucket_id = v_intent.bucket
      and so.name = v_intent.object_path
  )
  into v_object_exists;

  if not v_object_exists then
    raise exception 'Storage object is not accessible';
  end if;

  insert into public.storage_objects (
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    uploaded_by
  )
  values (
    v_intent.bucket,
    v_intent.object_path,
    v_intent.filename,
    v_intent.mime_type,
    v_intent.size_bytes,
    v_intent.created_by
  )
  on conflict on constraint storage_objects_bucket_object_path_key do nothing;

  select so.id
  into v_storage_object_id
  from public.storage_objects so
  where so.bucket = v_intent.bucket
    and so.object_path = v_intent.object_path;

  if v_storage_object_id is null then
    raise exception 'Storage object linkage could not be resolved';
  end if;

  insert into public.project_media (
    project_id,
    storage_object_id,
    uploaded_by,
    media_type,
    caption,
    task_id,
    is_final,
    visibility_class
  )
  values (
    v_intent.project_id,
    v_storage_object_id,
    v_intent.created_by,
    v_intent.media_type,
    v_intent.caption,
    v_effective_task_id,
    v_effective_is_final,
    v_intent.visibility_class
  )
  returning id
  into v_project_media_id;

  update public.project_media_upload_intents
  set project_media_id = v_project_media_id,
      task_id = v_effective_task_id,
      is_final = v_effective_is_final,
      finalized_at = coalesce(finalized_at, now())
  where id = v_intent.id;

  return query
  select
    pm.id,
    pm.storage_object_id,
    pm.project_id,
    so.bucket,
    so.object_path,
    so.filename
  from public.project_media pm
  join public.storage_objects so
    on so.id = pm.storage_object_id
  where pm.id = v_project_media_id;
end;
$$;
