-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260306164000_hr_domain.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create table public.hr_items (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  project_stage_id uuid references public.project_stages(id) on delete set null,
  estimate_work_id uuid references public.estimate_works(id) on delete set null,
  task_id uuid references public.tasks(id) on delete set null,
  title text not null,
  description text,
  compensation_type text not null default 'fixed' check (compensation_type in ('hourly', 'daily', 'fixed')),
  planned_cost_cents bigint check (planned_cost_cents is null or planned_cost_cents >= 0),
  actual_cost_cents bigint check (actual_cost_cents is null or actual_cost_cents >= 0),
  status text not null default 'planned' check (status in ('planned', 'in_progress', 'completed', 'cancelled')),
  start_at timestamptz,
  end_at timestamptz,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_hr_items_project_id on public.hr_items(project_id);
create index idx_hr_items_project_stage_id on public.hr_items(project_stage_id);
create index idx_hr_items_estimate_work_id on public.hr_items(estimate_work_id);
create index idx_hr_items_task_id on public.hr_items(task_id);

create table public.hr_item_assignees (
  id uuid primary key default gen_random_uuid(),
  hr_item_id uuid not null references public.hr_items(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  role_label text,
  created_at timestamptz not null default now(),
  unique (hr_item_id, profile_id)
);

create index idx_hr_item_assignees_hr_item_id on public.hr_item_assignees(hr_item_id);
create index idx_hr_item_assignees_profile_id on public.hr_item_assignees(profile_id);

create table public.hr_payments (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  hr_item_id uuid references public.hr_items(id) on delete set null,
  paid_to_profile_id uuid references public.profiles(id) on delete set null,
  amount_cents bigint not null check (amount_cents >= 0),
  status text not null default 'planned' check (status in ('planned', 'paid', 'cancelled')),
  paid_at timestamptz,
  notes text,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create index idx_hr_payments_project_id on public.hr_payments(project_id);
create index idx_hr_payments_hr_item_id on public.hr_payments(hr_item_id);
create index idx_hr_payments_paid_to_profile_id on public.hr_payments(paid_to_profile_id);

create trigger set_hr_items_updated_at
before update on public.hr_items
for each row execute function public.set_updated_at();
