-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260512132330_contractor_profiles_schema.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 3.1 — contractor_profiles "Визитная карточка" table.
--
-- One profile per organization (enforced by a unique index on org_id). The
-- moderation lifecycle (`draft → pending_moderation → published → archived`)
-- is plumbed here but the queue itself ships in Session 7+. Wave-1 usage in
-- Session 3.2 will create `draft` rows when a user uploads a Визитная
-- карточка; promotion to `published` is manual via Studio for now.
--
-- The unique-per-org constraint also acts as the natural index for
-- "fetch this org's card" — no separate non-unique index needed (codex
-- P2 lesson from Session 3.0).

create table public.contractor_profiles (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.organizations(id) on delete cascade,
  display_name text not null,
  contacts jsonb not null default '{}'::jsonb,
  region text,
  specializations text[] not null default '{}',
  experience_years integer,
  avatar_url text,
  description text,
  status text not null default 'draft'
    check (status in ('draft','pending_moderation','published','archived')),
  moderated_at timestamptz,
  moderated_by uuid references public.profiles(id) on delete set null,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint contractor_profiles_display_name_nonempty
    check (length(trim(display_name)) > 0),
  constraint contractor_profiles_experience_years_nonnegative
    check (experience_years is null or experience_years >= 0)
);

create unique index idx_contractor_profiles_one_per_org
  on public.contractor_profiles(org_id);

create index idx_contractor_profiles_status
  on public.contractor_profiles(status);

create index idx_contractor_profiles_published
  on public.contractor_profiles(status)
  where status = 'published';

create trigger set_contractor_profiles_updated_at
before update on public.contractor_profiles
for each row execute function public.set_updated_at();

grant select, insert, update, delete on table
  public.contractor_profiles
to authenticated;

alter table public.contractor_profiles enable row level security;

-- Org members may read their org's card; published cards are public to any
-- authenticated user (used by future "find contractor" UI). Writes require
-- can_manage_org (owner/admin).
create policy contractor_profiles_select on public.contractor_profiles
  for select
  to authenticated
  using (
    status = 'published'
    or public.is_org_member(org_id)
  );

create policy contractor_profiles_insert on public.contractor_profiles
  for insert
  to authenticated
  with check (public.can_manage_org(org_id));

create policy contractor_profiles_update on public.contractor_profiles
  for update
  to authenticated
  using (public.can_manage_org(org_id))
  with check (public.can_manage_org(org_id));

create policy contractor_profiles_delete on public.contractor_profiles
  for delete
  to authenticated
  using (public.can_manage_org(org_id));
