-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260306162000_storage_documents_and_media.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create table public.storage_objects (
  id uuid primary key default gen_random_uuid(),
  bucket text not null,
  object_path text not null,
  filename text not null,
  mime_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  checksum text,
  uploaded_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (bucket, object_path)
);

create index idx_storage_objects_uploaded_by on public.storage_objects(uploaded_by);

create table public.documents (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  type text not null,
  title text not null,
  origin text not null default 'manual' check (origin in ('project_creation', 'uploaded', 'manual', 'ai_generated')),
  description text,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_documents_project_id on public.documents(project_id);

create table public.document_versions (
  id uuid primary key default gen_random_uuid(),
  document_id uuid not null references public.documents(id) on delete cascade,
  storage_object_id uuid references public.storage_objects(id) on delete set null,
  version_number integer not null check (version_number > 0),
  is_current boolean not null default false,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique (document_id, version_number)
);

create index idx_document_versions_document_id on public.document_versions(document_id);
create unique index idx_document_versions_current_per_document
  on public.document_versions(document_id)
  where is_current = true;

create table public.project_media (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  storage_object_id uuid not null references public.storage_objects(id) on delete cascade,
  uploaded_by uuid references public.profiles(id) on delete set null,
  media_type text not null,
  caption text,
  created_at timestamptz not null default now()
);

create index idx_project_media_project_id on public.project_media(project_id);
create index idx_project_media_storage_object_id on public.project_media(storage_object_id);

create trigger set_documents_updated_at
before update on public.documents
for each row execute function public.set_updated_at();
