-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260325133000_break_projects_project_members_rls_cycle.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Break remaining RLS recursion cycle between project_members and projects.
--
-- Observed cycle after 20260325130000:
--   profiles_select -> project_members_select -> EXISTS(projects)
--   -> projects_select -> EXISTS(project_members) -> ...
--
-- Fix strategy:
-- - Introduce SECURITY DEFINER helper for owner check on projects.
-- - Recreate project_members policies to use helper instead of direct EXISTS(projects ...).
-- This avoids invoking projects RLS while evaluating project_members RLS.

create or replace function public.is_project_owner_for_actor(
  p_project_id uuid,
  p_actor uuid
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.projects p
    where p.id = p_project_id
      and p.owner_profile_id = p_actor
  )
$$;

revoke all on function public.is_project_owner_for_actor(uuid, uuid) from public;
grant execute on function public.is_project_owner_for_actor(uuid, uuid) to authenticated;

drop policy if exists project_members_select on public.project_members;

create policy project_members_select on public.project_members
for select
to authenticated
using (
  profile_id = auth.uid()
  or public.is_project_owner_for_actor(project_id, auth.uid())
);

drop policy if exists project_members_insert on public.project_members;

create policy project_members_insert on public.project_members
for insert
to authenticated
with check (
  public.is_project_owner_for_actor(project_id, auth.uid())
  and (
    role <> 'owner'
    or profile_id = (
      select p.owner_profile_id
      from public.projects p
      where p.id = project_id
    )
  )
);

drop policy if exists project_members_update on public.project_members;

create policy project_members_update on public.project_members
for update
to authenticated
using (
  public.is_project_owner_for_actor(project_id, auth.uid())
  and profile_id <> (
    select p.owner_profile_id
    from public.projects p
    where p.id = project_id
  )
)
with check (
  public.is_project_owner_for_actor(project_id, auth.uid())
  and profile_id <> (
    select p.owner_profile_id
    from public.projects p
    where p.id = project_id
  )
);

drop policy if exists project_members_delete on public.project_members;

create policy project_members_delete on public.project_members
for delete
to authenticated
using (
  public.is_project_owner_for_actor(project_id, auth.uid())
  and profile_id <> (
    select p.owner_profile_id
    from public.projects p
    where p.id = project_id
  )
);

