-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260513140000_p0_derived_chat_key_for_ai_sessions.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- P0 deterministic chat memory key for cross-channel session sharing.
--
-- Goal: a Telegram bot, web rovno.ai, and a Mini App all referring to the
-- same project memory for the same user must resolve to the same row in
-- public.project_ai_chat_sessions. Today chat_id is an arbitrary uuid
-- generated by the client, which forces every client to know which chat_id
-- a given (profile_id, project_id) belongs to.
--
-- Approach: add a generated stored column derived_chat_key whose value is
-- uuid_v5(NS, profile_id || ':' || project_id). The namespace UUID lives
-- in a single IMMUTABLE helper function public._ai_chat_key_namespace() so
-- the constant appears in exactly one place. Any client can recompute the
-- key locally with the same algorithm or via public.resolve_ai_chat_key,
-- and the unique index guarantees at most one session row per (profile,
-- project).
--
-- v5 implementation note. We compute UUIDv5 manually via pgcrypto's
-- digest(..., 'sha1') rather than depending on the uuid-ossp extension's
-- uuid_generate_v5. Two reasons:
--   1) The curated backend-truth parser at
--      scripts/generate-backend-truth.mjs:1644 only allows the pgcrypto
--      extension. uuid-ossp would force a parser change.
--   2) On self-host (api.rovno.ai) uuid-ossp availability is not
--      guaranteed without the contrib package; pgcrypto is already a hard
--      dependency of the schema and is enabled in the very first migration.
-- Both pgcrypto.digest and a PL/pgSQL function declared IMMUTABLE qualify
-- for use inside a generated stored column expression. The byte layout
-- below follows RFC 4122 section 4.3 verbatim (sha1, version 5, RFC 4122
-- variant), so the values match what TypeScript / JavaScript / Python
-- v5 libraries produce for the same (namespace, name) pair.
--
-- Existing get_ai_chat_session_continuity / append_ai_chat_session_turns
-- are left untouched in this migration. The bot reaches them through
-- ai-inference with a minted user JWT (auth.uid() = profile_id), so the
-- existing access checks continue to apply. The append RPC is amended in
-- a follow-up migration to play correctly with the new unique index.
--
-- Operational pre-flight before applying in ANY environment:
--
--   1) No (profile_id, project_id) duplicates may exist:
--        select profile_id, project_id, count(*)
--          from public.project_ai_chat_sessions
--         group by 1, 2
--        having count(*) > 1;
--      Any row returned means the unique index step below will fail.
--      Expected on staging today: zero rows (web is not wired to
--      ai-inference yet). Reconcile duplicates manually before apply.
--
--   2) Sample table size to know how long the ACCESS EXCLUSIVE rewrite
--      from adding a generated stored column will hold the lock:
--        select count(*) as session_rows
--          from public.project_ai_chat_sessions;
--      Staging is empty / near-empty. Prod (api.rovno.ai self-host)
--      should be sampled before spush so we plan the lock window.
--
-- Reference: docs/rovno-bots-plan.md section 4.4.


-- =====================================================================
-- Namespace helper.
--
-- Single source of truth for the v5 namespace used by both
--   * the derived_chat_key generated column on project_ai_chat_sessions
--   * the public.resolve_ai_chat_key helper exposed to clients
-- Both must agree byte-for-byte; embedding the literal in two places
-- would be a silent-drift trap.
--
-- Marked IMMUTABLE so PostgreSQL accepts the function inside a generated
-- column expression. Never change the function body after this migration
-- applies in any environment: changing it shifts every derived_chat_key
-- and orphans every existing session row.
-- =====================================================================

create or replace function public._ai_chat_key_namespace()
returns uuid
language sql
immutable
parallel safe
as $$
  select '5b1a2c3d-4e5f-4a6b-8c9d-0e1f2a3b4c5d'::uuid
$$;

revoke all on function public._ai_chat_key_namespace() from public;
grant execute on function public._ai_chat_key_namespace() to authenticated;

-- =====================================================================
-- _ai_chat_key_uuid_v5
--
-- RFC 4122 section 4.3 UUIDv5 implemented via pgcrypto. Internal helper
-- (underscore-prefixed); callers should use public.resolve_ai_chat_key
-- which provides the project/profile-shaped signature.
--
-- Implementation steps (RFC 4122 4.3):
--   1) sha1(namespace_bytes || name_bytes)
--   2) take the first 16 bytes
--   3) overwrite high nibble of byte 6 with 0x5 (version)
--   4) overwrite high two bits of byte 8 with 0b10 (RFC 4122 variant)
--   5) emit as canonical 8-4-4-4-12 UUID string
-- =====================================================================

create or replace function public._ai_chat_key_uuid_v5(
  p_namespace uuid,
  p_name text
)
returns uuid
language plpgsql
immutable
parallel safe
as $$
declare
  ns_bytes bytea;
  hash     bytea;
  raw      bytea;
  hex_str  text;
begin
  ns_bytes := decode(replace(p_namespace::text, '-', ''), 'hex');
  hash     := digest(ns_bytes || convert_to(p_name, 'UTF8'), 'sha1');
  raw      := substring(hash from 1 for 16);

  -- byte 6 high nibble = 0x5 (version)
  raw := set_byte(raw, 6, (get_byte(raw, 6) & 15) | 80);
  -- byte 8 high two bits = 0b10 (RFC 4122 variant)
  raw := set_byte(raw, 8, (get_byte(raw, 8) & 63) | 128);

  hex_str := encode(raw, 'hex');
  return (
    substring(hex_str, 1, 8)  || '-' ||
    substring(hex_str, 9, 4)  || '-' ||
    substring(hex_str, 13, 4) || '-' ||
    substring(hex_str, 17, 4) || '-' ||
    substring(hex_str, 21, 12)
  )::uuid;
end;
$$;

revoke all on function public._ai_chat_key_uuid_v5(uuid, text) from public;
grant execute on function public._ai_chat_key_uuid_v5(uuid, text) to authenticated;

-- =====================================================================
-- Generated stored column. Uses the namespace and v5 helpers so the UUID
-- literal lives in exactly one place (the namespace function body above)
-- and the v5 algorithm in exactly one place (the v5 helper body above).
-- =====================================================================

alter table public.project_ai_chat_sessions
  add column derived_chat_key uuid not null
  generated always as (
    public._ai_chat_key_uuid_v5(
      public._ai_chat_key_namespace(),
      profile_id::text || ':' || project_id::text
    )
  ) stored;

-- (Schema-level COMMENT ON COLUMN intentionally omitted: the curated
-- backend-truth parser does not support COMMENT ON statements and no
-- other migration in DEFAULT_SOURCE_FILES uses them. The semantics of
-- derived_chat_key live in the header comment above and in
-- docs/rovno-bots-plan.md.)

-- =====================================================================
-- Unique index. Guarantees at most one chat session per (profile, project)
-- across all channels. The pre-existing (project_id, profile_id) btree
-- index is non-unique and remains for lookup performance.
-- =====================================================================

create unique index uq_project_ai_chat_sessions_derived_chat_key
  on public.project_ai_chat_sessions (derived_chat_key);

-- =====================================================================
-- resolve_ai_chat_key
--
-- Public helper so clients (ai-inference Edge Function, web, bot service)
-- can canonically compute the chat key without hardcoding the namespace
-- or knowing the v5 byte layout. IMMUTABLE so callers can use it inline
-- in expressions and joins. Shares the namespace through
-- _ai_chat_key_namespace() and the v5 algorithm through
-- _ai_chat_key_uuid_v5().
-- =====================================================================

create or replace function public.resolve_ai_chat_key(
  p_profile_id uuid,
  p_project_id uuid
)
returns uuid
language sql
immutable
parallel safe
as $$
  select public._ai_chat_key_uuid_v5(
    public._ai_chat_key_namespace(),
    p_profile_id::text || ':' || p_project_id::text
  )
$$;

revoke all on function public.resolve_ai_chat_key(uuid, uuid) from public;
grant execute on function public.resolve_ai_chat_key(uuid, uuid) to authenticated;
-- service_role retains execute by default.
