-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260604120000_create_card_bindings.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Таблица card_bindings: трекинг сессий привязки карты (AddCard) для смены способа
-- оплаты ("Изменить карту"). В отличие от payment_intents это НЕ платёж: нет ни
-- суммы, ни order_id — только результат привязки карты к CustomerKey (= profile_id)
-- на стороне Т-Банка.
--
-- Поток:
--   1. tbank-add-card зовёт /v2/AddCard и вставляет row: status='pending', request_key.
--   2. Пользователь вводит карту в addcardIframe (или на hosted-странице AddCard);
--      сам PAN мы не видим (не PCI). По завершении Т-Банк шлёт уведомление
--      NotificationType=AddCard на NotificationURL терминала (tbank-notification):
--      Status ACTIVE/INACTIVE + RebillId + CardId + Pan.
--   3. tbank-notification обновляет row (status, rebill_id, card_id, pan_masked,
--      bound_at) и переносит свежий rebill_id в subscriptions.rebill_id текущей
--      подписки, чтобы следующее автосписание шло уже по новой карте.
--
-- Безопасность: rebill_id — токен рекуррентных списаний. В ЭТОЙ таблице он закрыт от
-- клиента: RLS включён БЕЗ политик для anon/authenticated, поэтому читает/пишет только
-- service_role (edge-функции, в обход RLS), а маскированный last-4 отдаётся владельцу
-- ТОЛЬКО через SECURITY DEFINER функцию get_card_on_file().
-- ВАЖНО (audit M5): это НЕ делает rebill_id полностью недоступным клиенту. Владелец
-- по-прежнему может прочитать subscriptions.rebill_id / payment_intents.rebill_id СВОИХ
-- строк (RLS-скоуп auth.uid(); пред-существующее поведение, column-level revoke нет).
-- Это own-data и не списываемо без TBANK_PASSWORD. Если нужен жёсткий инвариант
-- «rebill_id никогда не на клиенте» — добавить revoke select(rebill_id) на те таблицы.
--
-- COMMENT ON и `if not exists` не используются — backend-truth парсер их не поддерживает.

create table public.card_bindings (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null default 'tbank' check (provider in ('tbank')),
  request_key text not null unique,
  status text not null default 'pending' check (status in (
    'pending',
    'active',
    'inactive',
    'rejected'
  )),
  check_type text,
  rebill_id text,
  card_id text,
  pan_masked text,
  bound_at timestamptz,
  last_notification jsonb,
  error_code text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_card_bindings_profile on public.card_bindings(profile_id);
create index idx_card_bindings_active on public.card_bindings(profile_id, bound_at desc)
  where status = 'active';

create trigger set_card_bindings_updated_at
before update on public.card_bindings
for each row execute function public.set_updated_at();

alter table public.card_bindings enable row level security;
