-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260306164500_activity_and_notifications.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create table public.activity_events (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  actor_profile_id uuid references public.profiles(id) on delete set null,
  entity_type text not null,
  entity_id uuid,
  action_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index idx_activity_events_project_id on public.activity_events(project_id);
create index idx_activity_events_actor_profile_id on public.activity_events(actor_profile_id);
create index idx_activity_events_project_created_at
  on public.activity_events(project_id, created_at desc);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  project_id uuid references public.projects(id) on delete cascade,
  type text not null,
  title text not null,
  body text,
  is_read boolean not null default false,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index idx_notifications_profile_id on public.notifications(profile_id);
create index idx_notifications_project_id on public.notifications(project_id);
create index idx_notifications_profile_is_read_created_at
  on public.notifications(profile_id, is_read, created_at desc);
