-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260611120100_get_portfolio_finance_snapshot.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Portfolio finance rollup for Home → Финансы (finance-suite Phase 4, spec Part 3 §7.0).
--
-- One RPC returns every non-archived project the caller is a member of, with per-project
-- finance aggregates, portfolio totals, and a status pipeline — so the Home page no longer
-- depends on hydrating the browser estimate store per project.
--
-- The expressions deliberately MIRROR the frontend sources of truth:
--   * contract/cost: the layer-A snapshot expressions (get_ai_project_snapshot) —
--     cost = Σ estimate_resource_lines.total_price_cents (cost basis, себестоимость),
--     contract = Σ coalesce(discounted_client_total_price_cents, client_total_price_cents)
--     over the CURRENT estimate version (= frontend taxableBaseCents, ex-VAT).
--   * spent / to-be-paid: src/lib/estimate-v2/rollups.ts computeFactFromDataSources.
--     Frontend status mapping note: DB order status 'partially_received' maps to frontend
--     'placed' (orders-source.ts), so applied = placed|partially_received|received and
--     "open orders" = placed|partially_received. Order "kind" does not exist in the DB:
--     an order is a stock transfer iff any of its lines has a movement_type='transfer'
--     inventory movement (orders-source.ts kind derivation); transfers are excluded from
--     supplier spend but DO fulfil requested quantities (computeRemainingRequestedQty).
--   * completion: ProjectEstimate taskCompletion — works of the current version linked to
--     a task via task_checklist_items.estimate_work_id; earliest-created linked task wins;
--     done = that task's status = 'done'.
--   * visibility: effective_finance_visibility per project; money is returned only for
--     'detail' rows, others are redacted to nulls and excluded from totals — mirroring
--     applySensitiveDetailToEstimateV2FinanceSnapshot on the frontend.
--
-- Risk-flag thresholds MUST stay in sync with rovno src/lib/finance/thresholds.ts
-- (UTILIZATION_RISK_GAP_PP = 20, THIN_MARGIN_PCT = 10).
--
-- Known accepted divergences from the browser model (documented for calibration):
--   * schedule_behind_days uses the current works range end as the baseline proxy (the
--     browser-only schedule baseline snapshot is not persisted server-side).
--   * client-only "orphaned" flags on procurement/HR items do not exist in the DB and are
--     treated as not-orphaned.
--   * hr_payments are counted with status <> 'cancelled' (the app only ever writes 'paid').

create or replace function public.get_portfolio_finance_snapshot()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
with my_projects as (
  select p.id, p.title
  from public.projects p
  join public.project_members pm
    on pm.project_id = p.id
   and pm.profile_id = auth.uid()
  where p.archived_at is null
),
fin as (
  select mp.id, coalesce(public.effective_finance_visibility(mp.id), 'none') as vis
  from my_projects mp
),
cur as (
  -- One current version per estimate is enforced by a unique index, but a single root
  -- per project is only app-enforced (check-then-insert), so dedupe defensively like
  -- the layer-A snapshot does: the most recently touched root wins.
  select distinct on (pe.project_id)
    pe.project_id,
    ev.id as version_id,
    coalesce(
      pe.execution_status,
      case when pe.status = 'approved' then 'in_work' else 'planning' end
    ) as status
  from public.project_estimates pe
  join public.estimate_versions ev
    on ev.estimate_id = pe.id
   and ev.is_current
  where pe.project_id in (select id from my_projects)
  order by pe.project_id, pe.updated_at desc, ev.created_at desc
),
est as (
  select
    c.project_id,
    coalesce(sum(rl.total_price_cents), 0)::bigint as cost_cents,
    coalesce(sum(coalesce(rl.discounted_client_total_price_cents, rl.client_total_price_cents)), 0)::bigint as contract_cents,
    min(ew.planned_start) as planned_start,
    max(ew.planned_end) as planned_end
  from cur c
  join public.estimate_works ew on ew.estimate_version_id = c.version_id
  left join public.estimate_resource_lines rl on rl.estimate_work_id = ew.id
  group by c.project_id
),
task_progress as (
  select
    c.project_id,
    count(*)::int as tasks_total,
    count(*) filter (where lt.status = 'done')::int as tasks_done
  from cur c
  join public.estimate_works ew on ew.estimate_version_id = c.version_id
  join lateral (
    select t.status
    from public.task_checklist_items tci
    join public.tasks t on t.id = tci.task_id
    where tci.estimate_work_id = ew.id
    order by t.created_at asc
    limit 1
  ) lt on true
  group by c.project_id
),
transfer_orders as (
  -- Frontend kind derivation: any transfer movement on a line ⇒ the whole order is a move.
  -- Scoped to the caller's projects so the hot path never scans other tenants' movements.
  select distinct ol.order_id
  from public.inventory_movements im
  join public.order_lines ol on ol.id = im.order_line_id
  where im.movement_type = 'transfer'
    and im.project_id in (select id from my_projects)
),
line_received as (
  -- Frontend line.receivedQty: positive receipt-like movements per order line.
  select im.order_line_id, sum(im.delta_qty) as received_qty
  from public.inventory_movements im
  where im.order_line_id is not null
    and im.delta_qty > 0
    and im.movement_type in ('receipt', 'transfer')
    and im.project_id in (select id from my_projects)
  group by im.order_line_id
),
item_actual_price as (
  -- Frontend item.actualUnitPrice (procurement-source): the latest priced line on an
  -- APPLIED order, newest order first with line recency as the tiebreak.
  select distinct on (ol.procurement_item_id)
    ol.procurement_item_id,
    ol.unit_price_cents
  from public.order_lines ol
  join public.orders o on o.id = ol.order_id
  where ol.unit_price_cents is not null
    and ol.procurement_item_id is not null
    and o.status in ('placed', 'partially_received', 'received')
    and o.project_id in (select id from my_projects)
  order by ol.procurement_item_id, o.updated_at desc, ol.created_at desc
),
proc_spent as (
  -- rollups.ts: applied supplier orders, FULL line qty, price chain
  -- line.actual ?? line.planned(≡item.planned) ?? item.actual ?? item.planned ?? 0.
  select
    o.project_id,
    sum(round(coalesce(ol.unit_price_cents, pi.planned_unit_price_cents, iap.unit_price_cents, 0) * ol.quantity))::bigint as cents
  from public.orders o
  join public.order_lines ol on ol.order_id = o.id
  left join public.procurement_items pi on pi.id = ol.procurement_item_id
  left join item_actual_price iap on iap.procurement_item_id = ol.procurement_item_id
  where o.project_id in (select id from my_projects)
    and o.status in ('placed', 'partially_received', 'received')
    and not exists (select 1 from transfer_orders tr where tr.order_id = o.id)
  group by o.project_id
),
hr_paid as (
  select hp.project_id, sum(hp.amount_cents)::bigint as cents
  from public.hr_payments hp
  where hp.project_id in (select id from my_projects)
    and hp.status <> 'cancelled'
  group by hp.project_id
),
proc_to_pay as (
  -- rollups.ts toBePaid: planned price × (remaining-to-order + open-on-placed-orders).
  -- Remaining counts fulfilment from ALL applied orders (stock moves fulfil requests too);
  -- open qty counts open supplier orders only.
  select
    pi.project_id,
    sum(round(coalesce(pi.planned_unit_price_cents, 0) * (
      greatest(pi.quantity - coalesce(f.fulfilled, 0), 0) + coalesce(oo.open_qty, 0)
    )))::bigint as cents
  from public.procurement_items pi
  left join lateral (
    select sum(ol.quantity) as fulfilled
    from public.order_lines ol
    join public.orders o on o.id = ol.order_id
    where ol.procurement_item_id = pi.id
      and o.status in ('placed', 'partially_received', 'received')
  ) f on true
  left join lateral (
    select sum(greatest(ol.quantity - coalesce(lr.received_qty, 0), 0)) as open_qty
    from public.order_lines ol
    join public.orders o on o.id = ol.order_id
    left join line_received lr on lr.order_line_id = ol.id
    where ol.procurement_item_id = pi.id
      and o.status in ('placed', 'partially_received')
      and not exists (select 1 from transfer_orders tr where tr.order_id = o.id)
  ) oo on true
  where pi.project_id in (select id from my_projects)
    and pi.status <> 'cancelled'
  group by pi.project_id
),
hr_to_pay as (
  select
    hi.project_id,
    sum(greatest(coalesce(hi.planned_cost_cents, 0) - coalesce(p.paid, 0), 0))::bigint as cents
  from public.hr_items hi
  left join lateral (
    select sum(hp.amount_cents) as paid
    from public.hr_payments hp
    where hp.hr_item_id = hi.id
      and hp.status <> 'cancelled'
  ) p on true
  where hi.project_id in (select id from my_projects)
    and hi.status <> 'cancelled'
  group by hi.project_id
),
base_rows as (
  select
    mp.id,
    mp.title,
    f.vis,
    coalesce(c.status, 'planning') as status,
    (c.project_id is not null) as has_estimate,
    coalesce(e.contract_cents, 0) as contract_cents,
    coalesce(e.cost_cents, 0) as cost_cents,
    coalesce(ps.cents, 0) + coalesce(hp.cents, 0) as spent_cents,
    coalesce(ptp.cents, 0) + coalesce(htp.cents, 0) as to_be_paid_cents,
    coalesce(tp.tasks_done, 0) as tasks_done,
    coalesce(tp.tasks_total, 0) as tasks_total,
    e.planned_start,
    e.planned_end,
    case
      when coalesce(c.status, 'planning') in ('in_work', 'paused')
        and e.planned_end is not null
        and e.planned_end::date < current_date
        and coalesce(tp.tasks_total, 0) > coalesce(tp.tasks_done, 0)
      then (current_date - e.planned_end::date)::int
      else 0
    end as schedule_behind_days
  from my_projects mp
  join fin f on f.id = mp.id
  left join cur c on c.project_id = mp.id
  left join est e on e.project_id = mp.id
  left join task_progress tp on tp.project_id = mp.id
  left join proc_spent ps on ps.project_id = mp.id
  left join hr_paid hp on hp.project_id = mp.id
  left join proc_to_pay ptp on ptp.project_id = mp.id
  left join hr_to_pay htp on htp.project_id = mp.id
),
derived as (
  select
    r.*,
    (r.contract_cents - r.cost_cents) as margin_cents,
    case when r.contract_cents > 0
      then round((r.contract_cents - r.cost_cents)::numeric * 100 / r.contract_cents, 1)
    end as margin_pct,
    case when r.cost_cents > 0
      then round(r.spent_cents::numeric * 100 / r.cost_cents, 1)
    end as percent_spent,
    case when r.tasks_total > 0
      then round(r.tasks_done::numeric * 100 / r.tasks_total, 1)
    end as percent_complete
  from base_rows r
),
flagged as (
  select
    d.*,
    case
      when d.vis <> 'detail' then '[]'::jsonb
      else (
        select coalesce(jsonb_agg(flag), '[]'::jsonb)
        from (
          -- Thresholds mirror rovno src/lib/finance/thresholds.ts.
          select 'overspend' as flag
          where (d.spent_cents > d.cost_cents and d.spent_cents > 0)
             or (d.percent_spent is not null and d.percent_complete is not null
                 and d.percent_spent - d.percent_complete >= 20)
          union all
          select 'behind'
          where d.schedule_behind_days > 0
          union all
          select 'thin_margin'
          where d.margin_pct is not null and d.margin_pct < 10
        ) flags
      )
    end as risk_flags
  from derived d
)
select jsonb_build_object(
  'projects', coalesce(
    (
      select jsonb_agg(
        jsonb_build_object(
          'project_id', fl.id,
          'title', fl.title,
          'status', fl.status,
          'finance_visibility', fl.vis,
          'has_estimate', fl.has_estimate,
          'contract_value_cents', case when fl.vis = 'detail' then fl.contract_cents end,
          'cost_cents',           case when fl.vis = 'detail' then fl.cost_cents end,
          'margin_cents',         case when fl.vis = 'detail' then fl.margin_cents end,
          'margin_pct',           case when fl.vis = 'detail' then fl.margin_pct end,
          'spent_cents',          case when fl.vis = 'detail' then fl.spent_cents end,
          'percent_spent',        case when fl.vis = 'detail' then fl.percent_spent end,
          'to_be_paid_cents',     case when fl.vis = 'detail' then fl.to_be_paid_cents end,
          'tasks_done', fl.tasks_done,
          'tasks_total', fl.tasks_total,
          'percent_complete', fl.percent_complete,
          'planned_start', fl.planned_start,
          'planned_end', fl.planned_end,
          'schedule_behind_days', fl.schedule_behind_days,
          'risk_flags', fl.risk_flags
        )
        order by fl.title asc
      )
      from flagged fl
    ),
    '[]'::jsonb
  ),
  'totals', (
    select jsonb_build_object(
      'contract_value_cents', coalesce(sum(fl.contract_cents) filter (where fl.vis = 'detail'), 0),
      'cost_cents',           coalesce(sum(fl.cost_cents) filter (where fl.vis = 'detail'), 0),
      'margin_cents',         coalesce(sum(fl.margin_cents) filter (where fl.vis = 'detail'), 0),
      'margin_pct', case
        when coalesce(sum(fl.contract_cents) filter (where fl.vis = 'detail'), 0) > 0
        then round(
          sum(fl.margin_cents) filter (where fl.vis = 'detail')::numeric * 100
            / sum(fl.contract_cents) filter (where fl.vis = 'detail'),
          1
        )
      end,
      'spent_cents',          coalesce(sum(fl.spent_cents) filter (where fl.vis = 'detail'), 0),
      'to_be_paid_cents',     coalesce(sum(fl.to_be_paid_cents) filter (where fl.vis = 'detail'), 0),
      'active_count',         count(*) filter (where fl.status <> 'finished'),
      'at_risk_count',        count(*) filter (where fl.vis = 'detail' and fl.risk_flags <> '[]'::jsonb),
      'avg_percent_complete', round(avg(fl.percent_complete) filter (where fl.vis = 'detail'), 1),
      'redacted_project_count', count(*) filter (where fl.vis <> 'detail')
    )
    from flagged fl
  ),
  'pipeline', (
    select jsonb_build_object(
      'planning', jsonb_build_object(
        'count', count(*) filter (where fl.status = 'planning'),
        'contract_value_cents',
          coalesce(sum(fl.contract_cents) filter (where fl.status = 'planning' and fl.vis = 'detail'), 0)
      ),
      'in_work', jsonb_build_object(
        'count', count(*) filter (where fl.status in ('in_work', 'paused')),
        'contract_value_cents',
          coalesce(sum(fl.contract_cents) filter (where fl.status in ('in_work', 'paused') and fl.vis = 'detail'), 0),
        'backlog_cents',
          coalesce(sum(
            round(fl.contract_cents * (1 - coalesce(fl.percent_complete, 0) / 100))
          ) filter (where fl.status in ('in_work', 'paused') and fl.vis = 'detail'), 0)
      ),
      'finished', jsonb_build_object(
        'count', count(*) filter (where fl.status = 'finished'),
        'contract_value_cents',
          coalesce(sum(fl.contract_cents) filter (where fl.status = 'finished' and fl.vis = 'detail'), 0)
      )
    )
    from flagged fl
  )
)
$$;

revoke all on function public.get_portfolio_finance_snapshot() from public;
grant execute on function public.get_portfolio_finance_snapshot() to authenticated;
