-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260514120000_org_document_folders.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 3.2.1b — Org-scoped folders for org_documents.
--
-- Adds a flat (single-level) folder concept to organization documents:
--   * Table public.org_document_folders with case-insensitive unique
--     (org_id, lower(name)) so "Materials" and "materials" do not coexist
--     and surprise users
--   * Nullable column public.org_documents.folder_id with FK on delete set null
--   * Trigger guard on org_documents that enforces same-org folder_id AND
--     manager-only folder placement on BOTH insert and update paths. (The
--     read RLS policy on org_document_folders is is_org_member, so any
--     member can list folder IDs — meaning the insert path also needs the
--     can_manage_org gate, not just the same-org check.)
--   * Normalize trigger on org_document_folders that trim()s the name on
--     every insert/update so direct table writes by managers produce the
--     same stored value as RPC writes
--   * SECURITY DEFINER RPCs for create/rename/delete/move with explicit
--     can_manage_org checks and friendlier duplicate-name errors (P0001
--     instead of raw 23505 unique_violation)
--
-- Read scope: any org member (via is_org_member).
-- Write scope: only org managers (via can_manage_org), matching the product
-- decision that folder taxonomy is an org-managed feature, not a free-for-all.
--
-- Documents move from "Без папки" (folder_id IS NULL) to a specific folder
-- via move_org_document_to_folder. When a folder is deleted, ON DELETE SET
-- NULL puts its documents back into "Без папки".

-- 1. Folders table -----------------------------------------------------------

create table public.org_document_folders (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references public.organizations(id) on delete cascade,
  name        text not null check (char_length(trim(name)) between 1 and 80),
  created_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index idx_org_document_folders_org on public.org_document_folders(org_id);

-- Case-insensitive uniqueness so "Materials" and "materials" cannot
-- coexist in the same org. Combined with the normalize trigger below,
-- this prevents the common "I made a folder but it does not show up
-- alphabetically next to the duplicate I just typed" frustration.
create unique index idx_org_document_folders_org_lower_name
  on public.org_document_folders (org_id, lower(name));

-- Trim whitespace from folder names on every write so direct table updates
-- (managers have RLS write access) cannot diverge from the trimmed values
-- the RPCs would have produced.
create or replace function public.normalize_org_document_folder_name()
returns trigger
language plpgsql
as $$
begin
  if new.name is not null then
    new.name := trim(new.name);
  end if;
  return new;
end;
$$;

create trigger trg_normalize_org_document_folder_name
before insert or update of name on public.org_document_folders
for each row execute function public.normalize_org_document_folder_name();

create trigger set_org_document_folders_updated_at
before update on public.org_document_folders
for each row execute function public.set_updated_at();

-- 2. folder_id column on org_documents ---------------------------------------

alter table public.org_documents
  add column folder_id uuid
    references public.org_document_folders(id) on delete set null;

-- NOTE on locking: org_documents is small at the time this migration ships
-- (Session 2 introduced the table, low row count), so a plain CREATE INDEX
-- is acceptable. If the table grows materially before this migration is
-- replayed against a populated environment, prefer a separate non-
-- transactional migration with CREATE INDEX CONCURRENTLY.
create index idx_org_documents_folder on public.org_documents(folder_id);

-- 3. Trigger guard: enforce same-org folder_id AND manager-only placement ---

create or replace function public.guard_org_document_folder_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_folder_org uuid;
begin
  -- Insert path: if folder_id is provided, BOTH (a) the caller must be a
  -- manager and (b) the folder must belong to the same org. The earlier
  -- "non-manager cannot reference a folder anyway" assumption is wrong —
  -- the read RLS on org_document_folders is is_org_member, so any member
  -- can read folder IDs and slip one into an insert payload. We close
  -- that gap here.
  if tg_op = 'INSERT' and new.folder_id is not null then
    if not public.can_manage_org(new.org_id) then
      raise exception 'Forbidden: only org managers may place documents in folders on create'
        using errcode = '42501';
    end if;
    select org_id into v_folder_org
      from public.org_document_folders
     where id = new.folder_id;
    if v_folder_org is null or v_folder_org <> new.org_id then
      raise exception 'Folder % does not belong to org %', new.folder_id, new.org_id
        using errcode = 'P0001';
    end if;
    return new;
  end if;

  -- Update path: only inspect when folder_id is actually changing.
  if tg_op = 'UPDATE' and new.folder_id is distinct from old.folder_id then
    if not public.can_manage_org(new.org_id) then
      raise exception 'Forbidden: only org managers may move documents between folders'
        using errcode = '42501';
    end if;
    if new.folder_id is not null then
      select org_id into v_folder_org
        from public.org_document_folders
       where id = new.folder_id;
      if v_folder_org is null or v_folder_org <> new.org_id then
        raise exception 'Folder % does not belong to org %', new.folder_id, new.org_id
          using errcode = 'P0001';
      end if;
    end if;
  end if;

  return new;
end;
$$;

create trigger trg_guard_org_document_folder_change
before insert or update on public.org_documents
for each row execute function public.guard_org_document_folder_change();

-- 4. RLS ---------------------------------------------------------------------

grant select, insert, update, delete on table public.org_document_folders to authenticated;

alter table public.org_document_folders enable row level security;

create policy "org_document_folders_member_read" on public.org_document_folders
  for select using (public.is_org_member(org_id));

create policy "org_document_folders_manager_insert" on public.org_document_folders
  for insert with check (public.can_manage_org(org_id));

create policy "org_document_folders_manager_update" on public.org_document_folders
  for update using (public.can_manage_org(org_id))
            with check (public.can_manage_org(org_id));

create policy "org_document_folders_manager_delete" on public.org_document_folders
  for delete using (public.can_manage_org(org_id));

-- 5. RPCs --------------------------------------------------------------------

create or replace function public.create_org_document_folder(p_org_id uuid, p_name text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_row public.org_document_folders%rowtype;
begin
  if not public.can_manage_org(p_org_id) then
    raise exception 'Forbidden: only org managers may create folders'
      using errcode = '42501';
  end if;

  begin
    insert into public.org_document_folders (org_id, name, created_by)
    values (p_org_id, p_name, auth.uid())
    returning * into v_row;
  exception
    when unique_violation then
      raise exception 'Folder with this name already exists in this org'
        using errcode = 'P0001';
  end;

  return to_jsonb(v_row);
end;
$$;

create or replace function public.rename_org_document_folder(p_folder_id uuid, p_new_name text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_org_id uuid;
  v_row public.org_document_folders%rowtype;
begin
  select org_id into v_org_id
    from public.org_document_folders
   where id = p_folder_id;

  if v_org_id is null then
    raise exception 'Folder % not found', p_folder_id using errcode = 'P0002';
  end if;
  if not public.can_manage_org(v_org_id) then
    raise exception 'Forbidden: only org managers may rename folders'
      using errcode = '42501';
  end if;

  begin
    update public.org_document_folders
       set name = p_new_name
     where id = p_folder_id
    returning * into v_row;
  exception
    when unique_violation then
      raise exception 'Folder with this name already exists in this org'
        using errcode = 'P0001';
  end;

  return to_jsonb(v_row);
end;
$$;

create or replace function public.delete_org_document_folder(p_folder_id uuid)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_org_id uuid;
begin
  select org_id into v_org_id
    from public.org_document_folders
   where id = p_folder_id;

  if v_org_id is null then
    -- Idempotent: deleting an already-gone folder is a no-op.
    return;
  end if;
  if not public.can_manage_org(v_org_id) then
    raise exception 'Forbidden: only org managers may delete folders'
      using errcode = '42501';
  end if;

  delete from public.org_document_folders where id = p_folder_id;
end;
$$;

create or replace function public.move_org_document_to_folder(
  p_document_id uuid,
  p_folder_id uuid
)
returns void
language plpgsql
volatile
security definer
set search_path = public
as $$
declare
  v_doc_org_id uuid;
  v_folder_org_id uuid;
begin
  select org_id into v_doc_org_id
    from public.org_documents
   where id = p_document_id;

  if v_doc_org_id is null then
    raise exception 'Org document % not found', p_document_id using errcode = 'P0002';
  end if;
  if not public.can_manage_org(v_doc_org_id) then
    raise exception 'Forbidden: only org managers may move documents between folders'
      using errcode = '42501';
  end if;

  if p_folder_id is not null then
    select org_id into v_folder_org_id
      from public.org_document_folders
     where id = p_folder_id;
    if v_folder_org_id is null or v_folder_org_id <> v_doc_org_id then
      raise exception 'Folder % does not belong to org %', p_folder_id, v_doc_org_id
        using errcode = 'P0001';
    end if;
  end if;

  update public.org_documents
     set folder_id = p_folder_id
   where id = p_document_id;
end;
$$;

-- 6. Grants ------------------------------------------------------------------

revoke all on function public.create_org_document_folder(uuid, text) from public;
revoke all on function public.rename_org_document_folder(uuid, text) from public;
revoke all on function public.delete_org_document_folder(uuid) from public;
revoke all on function public.move_org_document_to_folder(uuid, uuid) from public;

grant execute on function public.create_org_document_folder(uuid, text) to authenticated;
grant execute on function public.rename_org_document_folder(uuid, text) to authenticated;
grant execute on function public.delete_org_document_folder(uuid) to authenticated;
grant execute on function public.move_org_document_to_folder(uuid, uuid) to authenticated;
