-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260406183000_procurement_operational_summary_requested_and_ordered_line_types.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Include procurement items in status `requested` in operational summary (for Requested tab + itemById).
-- Add estimate line id + resource_type on ordered_lines for badge semantics when items were omitted.

create or replace function public.get_procurement_operational_summary(
  p_project_id uuid,
  p_limit integer default 200,
  p_offset integer default 0
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_limit integer := least(greatest(coalesce(p_limit, 200), 1), 500);
  v_offset integer := greatest(coalesce(p_offset, 0), 0);
  v_allowed boolean;
  v_ordered_lines jsonb := '[]'::jsonb;
  v_procurement_items jsonb := '[]'::jsonb;
begin
  v_allowed := public.can_access_project(p_project_id);

  if not v_allowed then
    return jsonb_build_object(
      'ordered_lines', '[]'::jsonb,
      'procurement_items', '[]'::jsonb
    );
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'order_line_id', rows.order_line_id,
        'order_id', rows.order_id,
        'order_status', rows.order_status,
        'ordered_at', rows.ordered_at,
        'delivery_due_at', rows.delivery_due_at,
        'procurement_item_id', rows.procurement_item_id,
        'procurement_item_title', rows.procurement_item_title,
        'estimate_resource_line_id', rows.estimate_resource_line_id,
        'estimate_resource_line_resource_type', rows.estimate_resource_line_resource_type,
        'title', rows.title,
        'quantity', rows.quantity,
        'unit', rows.unit,
        'created_at', rows.created_at
      )
      order by rows.sort_order_ts desc, rows.created_at desc, rows.order_line_id
    ),
    '[]'::jsonb
  )
  into v_ordered_lines
  from (
    select
      ol.id as order_line_id,
      o.id as order_id,
      o.status as order_status,
      o.ordered_at,
      o.delivery_due_at,
      ol.procurement_item_id,
      pi.title as procurement_item_title,
      pi.estimate_resource_line_id,
      erl.resource_type as estimate_resource_line_resource_type,
      ol.title,
      ol.quantity,
      ol.unit,
      ol.created_at,
      coalesce(o.ordered_at, o.created_at) as sort_order_ts
    from public.order_lines ol
    join public.orders o
      on o.id = ol.order_id
    left join public.procurement_items pi
      on pi.id = ol.procurement_item_id
    left join public.estimate_resource_lines erl
      on erl.id = pi.estimate_resource_line_id
    where o.project_id = p_project_id
    order by coalesce(o.ordered_at, o.created_at) desc, ol.created_at desc, ol.id
    offset v_offset
    limit v_limit
  ) rows;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'procurement_item_id', rows.procurement_item_id,
        'estimate_resource_line_id', rows.estimate_resource_line_id,
        'estimate_resource_line_resource_type', rows.estimate_resource_line_resource_type,
        'task_id', rows.task_id,
        'title', rows.title,
        'description', rows.description,
        'category', rows.category,
        'quantity', rows.quantity,
        'unit', rows.unit,
        'status', rows.status,
        'created_at', rows.created_at,
        'updated_at', rows.updated_at
      )
      order by rows.updated_at desc, rows.procurement_item_id
    ),
    '[]'::jsonb
  )
  into v_procurement_items
  from (
    select
      pi.id as procurement_item_id,
      pi.estimate_resource_line_id,
      erl.resource_type as estimate_resource_line_resource_type,
      pi.task_id,
      pi.title,
      pi.description,
      pi.category,
      pi.quantity,
      pi.unit,
      pi.status,
      pi.created_at,
      pi.updated_at
    from public.procurement_items pi
    left join public.estimate_resource_lines erl
      on erl.id = pi.estimate_resource_line_id
    where pi.project_id = p_project_id
      and pi.status <> 'cancelled'
    order by pi.updated_at desc, pi.id
    offset v_offset
    limit v_limit
  ) rows;

  return jsonb_build_object(
    'ordered_lines', v_ordered_lines,
    'procurement_items', v_procurement_items
  );
end;
$$;
