-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260306163000_inventory_foundation.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
create table public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  title text not null,
  sku text,
  unit text not null,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_inventory_items_project_id on public.inventory_items(project_id);

create table public.inventory_locations (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  title text not null,
  description text,
  created_at timestamptz not null default now()
);

create index idx_inventory_locations_project_id on public.inventory_locations(project_id);

create table public.inventory_balances (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  inventory_item_id uuid not null references public.inventory_items(id) on delete cascade,
  inventory_location_id uuid references public.inventory_locations(id) on delete cascade,
  quantity numeric(14,3) not null default 0 check (quantity >= 0),
  updated_at timestamptz not null default now(),
  constraint inventory_balances_project_item_location_key
    unique nulls not distinct (project_id, inventory_item_id, inventory_location_id)
);

create index idx_inventory_balances_project_id on public.inventory_balances(project_id);
create index idx_inventory_balances_inventory_item_id on public.inventory_balances(inventory_item_id);
create index idx_inventory_balances_inventory_location_id on public.inventory_balances(inventory_location_id);

create function public.apply_inventory_balance_delta(
  p_project_id uuid,
  p_inventory_item_id uuid,
  p_inventory_location_id uuid,
  p_delta numeric
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_current_qty numeric(14,3);
  v_next_qty numeric(14,3);
begin
  if p_delta is null then
    raise exception 'Inventory balance delta cannot be null';
  end if;

  if p_delta = 0 then
    return;
  end if;

  insert into public.inventory_balances (
    project_id,
    inventory_item_id,
    inventory_location_id,
    quantity,
    updated_at
  )
  values (
    p_project_id,
    p_inventory_item_id,
    p_inventory_location_id,
    0,
    now()
  )
  on conflict (project_id, inventory_item_id, inventory_location_id)
  do nothing;

  select ib.quantity
  into v_current_qty
  from public.inventory_balances ib
  where ib.project_id = p_project_id
    and ib.inventory_item_id = p_inventory_item_id
    and ib.inventory_location_id is not distinct from p_inventory_location_id
  for update;

  v_next_qty := coalesce(v_current_qty, 0) + p_delta;

  if v_next_qty < 0 then
    raise exception 'Inventory balance cannot go negative for item % at location %', p_inventory_item_id, p_inventory_location_id;
  end if;

  update public.inventory_balances ib
  set quantity = v_next_qty,
      updated_at = now()
  where ib.project_id = p_project_id
    and ib.inventory_item_id = p_inventory_item_id
    and ib.inventory_location_id is not distinct from p_inventory_location_id;
end;
$$;

create function public.sync_inventory_balances()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_new_row jsonb;
  v_old_row jsonb;
  v_new_project_id uuid;
  v_new_inventory_item_id uuid;
  v_new_inventory_location_id uuid;
  v_old_project_id uuid;
  v_old_inventory_item_id uuid;
  v_old_inventory_location_id uuid;
  v_new_delta numeric;
  v_old_delta numeric;
begin
  if tg_op in ('INSERT', 'UPDATE') then
    v_new_row := to_jsonb(new);
    v_new_project_id := (v_new_row ->> 'project_id')::uuid;
    v_new_inventory_item_id := (v_new_row ->> 'inventory_item_id')::uuid;
    v_new_inventory_location_id := coalesce(
      (v_new_row ->> 'inventory_location_id')::uuid,
      (v_new_row ->> 'location_id')::uuid
    );
    v_new_delta := (v_new_row ->> 'delta_qty')::numeric;
  end if;

  if tg_op in ('UPDATE', 'DELETE') then
    v_old_row := to_jsonb(old);
    v_old_project_id := (v_old_row ->> 'project_id')::uuid;
    v_old_inventory_item_id := (v_old_row ->> 'inventory_item_id')::uuid;
    v_old_inventory_location_id := coalesce(
      (v_old_row ->> 'inventory_location_id')::uuid,
      (v_old_row ->> 'location_id')::uuid
    );
    v_old_delta := (v_old_row ->> 'delta_qty')::numeric;
  end if;

  if tg_op = 'INSERT' then
    perform public.apply_inventory_balance_delta(
      v_new_project_id,
      v_new_inventory_item_id,
      v_new_inventory_location_id,
      v_new_delta
    );
    return new;
  end if;

  if tg_op = 'UPDATE' then
    if v_old_project_id is distinct from v_new_project_id
       or v_old_inventory_item_id is distinct from v_new_inventory_item_id
       or v_old_inventory_location_id is distinct from v_new_inventory_location_id then
      perform public.apply_inventory_balance_delta(
        v_old_project_id,
        v_old_inventory_item_id,
        v_old_inventory_location_id,
        -v_old_delta
      );
      perform public.apply_inventory_balance_delta(
        v_new_project_id,
        v_new_inventory_item_id,
        v_new_inventory_location_id,
        v_new_delta
      );
    else
      perform public.apply_inventory_balance_delta(
        v_new_project_id,
        v_new_inventory_item_id,
        v_new_inventory_location_id,
        v_new_delta - v_old_delta
      );
    end if;

    return new;
  end if;

  perform public.apply_inventory_balance_delta(
    v_old_project_id,
    v_old_inventory_item_id,
    v_old_inventory_location_id,
    -v_old_delta
  );

  return old;
end;
$$;

create trigger set_inventory_items_updated_at
before update on public.inventory_items
for each row execute function public.set_updated_at();

create trigger set_inventory_balances_updated_at
before update on public.inventory_balances
for each row execute function public.set_updated_at();
