-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260506130000_fix_org_owner_membership_order.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Session 2 hotfix — addresses Codex P1 finding on rovno#62.
--
-- The original handle_organization_owner_membership demoted the existing
-- owner row BEFORE inserting the replacement. On owner transfer that
-- ordering tripped enforce_org_member_last_owner (BEFORE UPDATE on
-- org_members), which counts remaining role='owner' rows and refuses to
-- leave the org without an owner. Result: every org-ownership transfer
-- raised "Cannot remove the last owner".
--
-- Fix: insert (or upsert) the new owner row first, then demote any other
-- existing owner rows. With the new owner row already present, the
-- last-owner trigger sees a non-zero remaining count during demotion and
-- allows the transition.
--
-- Initial-INSERT path is unchanged (the demote UPDATE matches zero rows
-- when the org is brand-new, so trigger doesn't fire either way).

create or replace function public.handle_organization_owner_membership()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Insert (or claim) the new owner row first so the org always has at
  -- least one role='owner' membership when the demotion below runs.
  insert into public.org_members (org_id, profile_id, role)
  values (new.id, new.owner_profile_id, 'owner')
  on conflict (org_id, profile_id) do update
    set role = 'owner';

  -- Now safely demote any other rows that still claim ownership.
  update public.org_members
  set role = 'admin'
  where org_id = new.id
    and role = 'owner'
    and profile_id <> new.owner_profile_id;

  return new;
end;
$$;
