-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260323110000_storage_project_media_insert_policy.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
drop policy if exists storage_objects_insert_project_media_authenticated on storage.objects;

create policy storage_objects_insert_project_media_authenticated
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'project-media'
  and regexp_match(
    name,
    '^projects/([0-9a-fA-F-]{36})/media/[0-9a-fA-F-]{36}/'
  ) is not null
  and public.can_write_project_content(
    (regexp_match(
      name,
      '^projects/([0-9a-fA-F-]{36})/media/[0-9a-fA-F-]{36}/'
    ))[1]::uuid
  )
);
