-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260509130000_workspace_org_doc_uploads_and_orphan_safe_links.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Two-part migration unblocking the /home upload dialog and org deletion:
--
-- Part 1: documents.linked_external_kind/_id constraint allowed *only* the
-- linked-and-present state. ON DELETE SET NULL on the FK columns now produces
-- a state the constraint rejects (kind = 'org' AND linked_org_document_id is
-- null), so deleting an organization or workspace document fails the cascade.
-- Relax the constraint so an "orphan" link (kind set, id null) is also valid.
-- This lets the frontend keep the historical "imported from org" label even
-- after the source disappears.
--
-- Part 2: 4 new RPCs (prepare/finalize × workspace/org) so the /home upload
-- dialog can attach a file when saving to personal docs or to the active
-- organization, mirroring the existing prepare_document_upload pattern.
-- Plus the storage.objects insert + select policies they require.

-- ---------------------------------------------------------------------------
-- Part 1: orphan-safe documents_link_consistent
-- ---------------------------------------------------------------------------

alter table public.documents
  drop constraint if exists documents_link_consistent;

alter table public.documents
  add constraint documents_link_consistent check (
    (linked_external_kind is null
      and linked_workspace_document_id is null
      and linked_org_document_id is null)
    or (linked_external_kind = 'workspace'
      and linked_org_document_id is null)
    or (linked_external_kind = 'org'
      and linked_workspace_document_id is null)
  );

-- ---------------------------------------------------------------------------
-- Part 2a: storage policies for workspace/org paths inside project-documents
-- ---------------------------------------------------------------------------

drop policy if exists storage_objects_insert_workspace_documents_authenticated on storage.objects;
create policy storage_objects_insert_workspace_documents_authenticated
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'project-documents'
  and regexp_match(
    name,
    '^workspace/([0-9a-fA-F-]{36})/[0-9a-fA-F-]{36}/'
  ) is not null
  and (regexp_match(
    name,
    '^workspace/([0-9a-fA-F-]{36})/[0-9a-fA-F-]{36}/'
  ))[1]::uuid = auth.uid()
);

drop policy if exists storage_objects_insert_org_documents_authenticated on storage.objects;
create policy storage_objects_insert_org_documents_authenticated
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'project-documents'
  and regexp_match(
    name,
    '^orgs/([0-9a-fA-F-]{36})/[0-9a-fA-F-]{36}/'
  ) is not null
  and public.is_org_member(
    (regexp_match(
      name,
      '^orgs/([0-9a-fA-F-]{36})/[0-9a-fA-F-]{36}/'
    ))[1]::uuid
  )
);

-- Extend the existing select policy so workspace/org versions can resolve
-- their storage objects. The simplest approach is two additional select
-- policies that mirror the project one for the new domains.

drop policy if exists storage_objects_select_workspace_documents_authenticated on storage.objects;
create policy storage_objects_select_workspace_documents_authenticated
on storage.objects
for select
to authenticated
using (
  bucket_id = 'project-documents'
  and exists (
    select 1
    from public.workspace_document_versions wdv
    join public.workspace_documents wd on wd.id = wdv.workspace_document_id
    where wd.owner_profile_id = auth.uid()
      and wdv.storage_object_id in (
        select so.id from public.storage_objects so
        where so.bucket = 'project-documents'
          and so.object_path = storage.objects.name
      )
  )
);

drop policy if exists storage_objects_select_org_documents_authenticated on storage.objects;
create policy storage_objects_select_org_documents_authenticated
on storage.objects
for select
to authenticated
using (
  bucket_id = 'project-documents'
  and exists (
    select 1
    from public.org_document_versions odv
    join public.org_documents od on od.id = odv.org_document_id
    where public.is_org_member(od.org_id)
      and odv.storage_object_id in (
        select so.id from public.storage_objects so
        where so.bucket = 'project-documents'
          and so.object_path = storage.objects.name
      )
  )
);

-- ---------------------------------------------------------------------------
-- Part 2b: workspace_documents upload prepare/finalize
-- ---------------------------------------------------------------------------

create or replace function public.prepare_workspace_document_upload(
  p_type text,
  p_title text,
  p_client_filename text,
  p_mime_type text,
  p_size_bytes bigint,
  p_description text default null
)
returns table (
  upload_intent_id uuid,
  bucket text,
  object_path text,
  filename text,
  mime_type text,
  size_bytes bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_bucket text;
  v_filename text;
  v_intent_id uuid := gen_random_uuid();
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  if coalesce(trim(p_type), '') = '' then
    raise exception 'Document type is required';
  end if;

  if coalesce(trim(p_title), '') = '' then
    raise exception 'Document title is required';
  end if;

  select c.bucket
    into v_bucket
  from public.storage_bucket_config c
  where c.key = 'documents';

  if v_bucket is null or trim(v_bucket) = '' then
    raise exception 'Document upload bucket is not configured';
  end if;

  v_filename := public.sanitize_uploaded_filename(p_client_filename);

  insert into public.workspace_document_upload_intents (
    id,
    owner_profile_id,
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    created_by
  )
  values (
    v_intent_id,
    v_uid,
    v_bucket,
    format('workspace/%s/%s/%s', v_uid, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes,
    v_uid
  );

  return query
  select
    v_intent_id,
    v_bucket,
    format('workspace/%s/%s/%s', v_uid, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes;
end;
$$;

revoke all on function public.prepare_workspace_document_upload(text, text, text, text, bigint, text) from public;
grant execute on function public.prepare_workspace_document_upload(text, text, text, text, bigint, text) to authenticated;

create or replace function public.finalize_workspace_document_upload(
  p_upload_intent_id uuid,
  p_type text,
  p_title text,
  p_description text default null
)
returns table (
  workspace_document_id uuid,
  workspace_document_version_id uuid,
  storage_object_id uuid,
  bucket text,
  object_path text,
  filename text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_intent public.workspace_document_upload_intents%rowtype;
  v_storage_object_id uuid;
  v_doc_id uuid;
  v_version_id uuid;
  v_object_exists boolean;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_intent
  from public.workspace_document_upload_intents
  where id = p_upload_intent_id
  for update;

  if not found then
    raise exception 'Upload intent not found';
  end if;

  if v_intent.owner_profile_id <> auth.uid() then
    raise exception 'Upload intent does not belong to current user';
  end if;

  select exists (
    select 1
    from storage.objects so
    where so.bucket_id = v_intent.bucket
      and so.name = v_intent.object_path
  )
  into v_object_exists;

  if not v_object_exists then
    raise exception 'Storage object is not accessible';
  end if;

  insert into public.storage_objects (
    bucket, object_path, filename, mime_type, size_bytes, uploaded_by
  )
  values (
    v_intent.bucket, v_intent.object_path, v_intent.filename,
    v_intent.mime_type, v_intent.size_bytes, v_intent.created_by
  )
  on conflict on constraint storage_objects_bucket_object_path_key do nothing;

  select so.id into v_storage_object_id
  from public.storage_objects so
  where so.bucket = v_intent.bucket
    and so.object_path = v_intent.object_path;

  if v_storage_object_id is null then
    raise exception 'Storage object linkage could not be resolved';
  end if;

  insert into public.workspace_documents (
    owner_profile_id, title, type, origin, description, created_by
  )
  values (
    v_intent.owner_profile_id,
    coalesce(nullif(trim(p_title), ''), v_intent.filename),
    coalesce(nullif(trim(p_type), ''), 'knowledge_base'),
    'uploaded',
    nullif(trim(p_description), ''),
    v_intent.created_by
  )
  returning id into v_doc_id;

  insert into public.workspace_document_versions (
    workspace_document_id, storage_object_id, version_number, is_current
  )
  values (v_doc_id, v_storage_object_id, 1, true)
  returning id into v_version_id;

  update public.workspace_document_upload_intents
  set finalized_at = coalesce(finalized_at, now())
  where id = v_intent.id;

  return query
  select v_doc_id, v_version_id, v_storage_object_id,
         v_intent.bucket, v_intent.object_path, v_intent.filename;
end;
$$;

revoke all on function public.finalize_workspace_document_upload(uuid, text, text, text) from public;
grant execute on function public.finalize_workspace_document_upload(uuid, text, text, text) to authenticated;

-- ---------------------------------------------------------------------------
-- Part 2c: org_documents upload prepare/finalize
-- ---------------------------------------------------------------------------

create or replace function public.prepare_org_document_upload(
  p_org_id uuid,
  p_type text,
  p_title text,
  p_client_filename text,
  p_mime_type text,
  p_size_bytes bigint,
  p_description text default null
)
returns table (
  upload_intent_id uuid,
  bucket text,
  object_path text,
  filename text,
  mime_type text,
  size_bytes bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_bucket text;
  v_filename text;
  v_intent_id uuid := gen_random_uuid();
begin
  if v_uid is null then
    raise exception 'Authentication required';
  end if;

  if not public.is_org_member(p_org_id) then
    raise exception 'Not a member of organization %', p_org_id;
  end if;

  if coalesce(trim(p_type), '') = '' then
    raise exception 'Document type is required';
  end if;

  if coalesce(trim(p_title), '') = '' then
    raise exception 'Document title is required';
  end if;

  select c.bucket
    into v_bucket
  from public.storage_bucket_config c
  where c.key = 'documents';

  if v_bucket is null or trim(v_bucket) = '' then
    raise exception 'Document upload bucket is not configured';
  end if;

  v_filename := public.sanitize_uploaded_filename(p_client_filename);

  insert into public.org_document_upload_intents (
    id,
    org_id,
    bucket,
    object_path,
    filename,
    mime_type,
    size_bytes,
    created_by
  )
  values (
    v_intent_id,
    p_org_id,
    v_bucket,
    format('orgs/%s/%s/%s', p_org_id, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes,
    v_uid
  );

  return query
  select
    v_intent_id,
    v_bucket,
    format('orgs/%s/%s/%s', p_org_id, v_intent_id, v_filename),
    v_filename,
    nullif(trim(p_mime_type), ''),
    p_size_bytes;
end;
$$;

revoke all on function public.prepare_org_document_upload(uuid, text, text, text, text, bigint, text) from public;
grant execute on function public.prepare_org_document_upload(uuid, text, text, text, text, bigint, text) to authenticated;

create or replace function public.finalize_org_document_upload(
  p_upload_intent_id uuid,
  p_type text,
  p_title text,
  p_description text default null
)
returns table (
  org_document_id uuid,
  org_document_version_id uuid,
  storage_object_id uuid,
  bucket text,
  object_path text,
  filename text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_intent public.org_document_upload_intents%rowtype;
  v_storage_object_id uuid;
  v_doc_id uuid;
  v_version_id uuid;
  v_object_exists boolean;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select *
  into v_intent
  from public.org_document_upload_intents
  where id = p_upload_intent_id
  for update;

  if not found then
    raise exception 'Upload intent not found';
  end if;

  if not public.is_org_member(v_intent.org_id) then
    raise exception 'Not a member of organization %', v_intent.org_id;
  end if;

  if v_intent.created_by <> auth.uid() then
    raise exception 'Upload intent does not belong to current user';
  end if;

  select exists (
    select 1
    from storage.objects so
    where so.bucket_id = v_intent.bucket
      and so.name = v_intent.object_path
  )
  into v_object_exists;

  if not v_object_exists then
    raise exception 'Storage object is not accessible';
  end if;

  insert into public.storage_objects (
    bucket, object_path, filename, mime_type, size_bytes, uploaded_by
  )
  values (
    v_intent.bucket, v_intent.object_path, v_intent.filename,
    v_intent.mime_type, v_intent.size_bytes, v_intent.created_by
  )
  on conflict on constraint storage_objects_bucket_object_path_key do nothing;

  select so.id into v_storage_object_id
  from public.storage_objects so
  where so.bucket = v_intent.bucket
    and so.object_path = v_intent.object_path;

  if v_storage_object_id is null then
    raise exception 'Storage object linkage could not be resolved';
  end if;

  insert into public.org_documents (
    org_id, title, type, origin, description, created_by
  )
  values (
    v_intent.org_id,
    coalesce(nullif(trim(p_title), ''), v_intent.filename),
    coalesce(nullif(trim(p_type), ''), 'knowledge_base'),
    'uploaded',
    nullif(trim(p_description), ''),
    v_intent.created_by
  )
  returning id into v_doc_id;

  insert into public.org_document_versions (
    org_document_id, storage_object_id, version_number, is_current
  )
  values (v_doc_id, v_storage_object_id, 1, true)
  returning id into v_version_id;

  update public.org_document_upload_intents
  set finalized_at = coalesce(finalized_at, now())
  where id = v_intent.id;

  return query
  select v_doc_id, v_version_id, v_storage_object_id,
         v_intent.bucket, v_intent.object_path, v_intent.filename;
end;
$$;

revoke all on function public.finalize_org_document_upload(uuid, text, text, text) from public;
grant execute on function public.finalize_org_document_upload(uuid, text, text, text) to authenticated;
