-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260720120000_payment_intents_order_attempt.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- TB-FIX-20260720-01 (fixes TB-H-20260720-01, provider-proven by TB-EXP-20260720-01):
-- T-Bank permanently rejects a second /v2/Init on a reused OrderId (ErrorCode 8,
-- observed for NEW/CONFIRMED/REFUNDED/CANCELED prior states), so the recurrent
-- worker's deterministic per-period order_id admits AT MOST ONE provider session
-- ever. order_attempt is the retry generation for that (subscription, period)
-- claim: the provider-facing OrderId becomes `<order_id>` for attempt 0 and
-- `<order_id>-a<N>` for attempt N (still <= 36 chars, T-Bank's OrderId limit).
-- payment_intents.order_id itself stays IMMUTABLE as the claim/dedup identity
-- (unique (provider, order_id)); only the worker bumps order_attempt, and only
-- after provider evidence that the current attempt's session is dead-terminal
-- (REJECTED / AUTH_FAIL / DEADLINE_EXPIRED / CANCELED — a "burned" OrderId).
-- Checkout intents keep order_attempt = 0 forever (their uuid order_id is
-- single-use by construction).
alter table public.payment_intents
  add column order_attempt smallint not null default 0
    constraint payment_intents_order_attempt_range
      check (order_attempt >= 0 and order_attempt <= 99);
