-- Generated file. Read-only. Regenerate from rovno-db.
-- Do not edit this file directly.
-- Contract precedence: mirrored SQL is the exact audit source within backend-truth.
-- Source: supabase/migrations/20260325123000_restore_projects_select_membership_visibility.sql
-- Regenerate with: node scripts/generate-backend-truth.mjs
-- Restore membership-aware visibility for project reads.
-- This corrects an earlier owner-only `projects_select` hotfix so that
-- accepted non-owner members can still read their project rows.

drop policy if exists projects_select on public.projects;

create policy projects_select on public.projects
for select
to authenticated
using (
  owner_profile_id = auth.uid()
  or exists (
    select 1
    from public.project_members pm
    where pm.project_id = id
      and pm.profile_id = auth.uid()
  )
);

